### ISSUE TITLE
Bug at FileNames.m - crash when Obj.Time is empty

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#106]
D.main('StartJD',[23 5 2023], 'EndJD',[23 5 2023]);

Output argument "DateVec" (and maybe others) not assigned during call to
"convert.strFN2date".

Error in FileNames/julday (line 445)
                DateVec = convert.strFN2date(Obj.Time(FlagN));

Error in FileNames/sortByJD (line 1392)
                JD = Obj(Iobj).julday;

Error in FileNames/groupByCounter (line 1563)
            Result     = Result.sortByJD;

Error in pipeline.DemonLAST/main (line 1253)
                [~, FN_Sci_Groups] =
                FN_Sci.groupByCounter('MinInGroup',Args.MinInGroup,
                'MaxInGroup',Args.MaxInGroup);

**Comment by EranOfek** [comment]
Not enough information and I can't recover the exact bug.
I fixed one related bug - please check again and report.
If it doesn't work put a break point in line 445:
DateVec = convert.strFN2date(Obj.Time(FlagN));
and report the value of 
Obj.Time(FlagN)

Thanks,
Eran

**Comment by EranOfek** [comment]
Fixed
