### ISSUE TITLE
Astrometric solution diverge at edges

### ISSUE THREAD

**Issue by noamse** [EranOfek/AstroPack#108]
The astrometric solution shows a huge trend as a function of pixels. 
Consider different polynomials for the fitting process.

![image](https://github.com/EranOfek/AstroPack/assets/46418997/d2a18233-16df-40be-9aac-14e825b8f6b1)

![image](https://github.com/EranOfek/AstroPack/assets/46418997/b722b855-4463-4121-97c5-81a7583bee0a)

**Comment by EranOfek** [comment]
It seems that there is more fundamental issue.
It is possible that the astrometric solutions are not written correctly into the header.
In addition, there may be also a regularization problem in the solutions.

**Comment by EranOfek** [comment]
For Yossi:
data in euler:/raid/eran/projects/telescopes/LAST/Images_PipeTest/testPipe/LAST.01.02.02/2023/04/25/proc/1/

% to read the image and cat:
AI=AstroImage('LAST.01.02.01_20230425.215635.031_clear_185-02_013_001_015_sci_proc_Image_1.fits','Cat','LAST.01.02.01_20230425.215635.031_clear_185-02_013_001_015_sci_proc_Cat_1.fits');

% the code that check the quality of the astrometric solution:
R=imProc.astrometry.astrometryQualityData(AI); 
% e.g., the median residuals in RA as a function of Y,X:
R.ResidRA_XY.median

% some useful functions:

[Res, AI]=imProc.astrometry.astrometryRefine(AI);
AI.populateWCS;  % to populate the WCS 
% update coordinates in catalog:
AI=imProc.astrometry.addCoordinates2catalog(AI,'UpdateCoo',true)

Question: is the fitWCS function (called by astrometryRefine) is working correctly?
I suspect that the residuals from the best fit are different than the residuals I get when I am using
astrometryQualityData

Thanks,
Eran

**Comment by EranOfek** [comment]
duplicate - closing and adding link.
