### ISSUE TITLE
matlab/Startup/startup.m references matlab/pipeline

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#11]
You have removed matlab/pipeline

https://github.com/EranOfek/AstroPack/blob/620f5f1f98c334644b4a3ebcd611c3f728222e6e/matlab/startup/startup.m#L84

(whatever, I'm not using this startup file, only at times copying pieces of it, it is incompatible with other startup files AFAIU, and anyway I don't find logical that a package file has to be locally modified in order to work)

**Comment by EranOfek** [comment]
The startup file is a function with arguments. As explained in the wiki, the recommendation is to use your own startup file and to call the AstroPack startup with arguments according to your needs.
