### ISSUE TITLE
new pipeline crashed. for LAST.01.04.01 and LAST.01.04.02

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#110]
There is a dark file in the calib directory

>> D.main
Index exceeds the number of array elements (0).

Error in AstroWCS.header2wcs (line 1358)
                if isnumeric(Result(Iobj).CTYPE{1}) &&
                any(isnan(Result(Iobj).CTYPE{1}))

Error in AstroImage/populateWCS (line 1615)
                Obj(Iobj).WCS = AstroWCS.header2wcs(Obj(Iobj).HeaderData,
                Args.header2wcsArgs{:});

Error in AstroImage.readFileNamesObj (line 700)
                Result = populateWCS(Result);

Error in pipeline.DemonLAST/loadCalib (line 1134)
                Obj.CI.Bias = AstroImage.readFileNamesObj(FN_Bias,
                'AddProduct',Args.AddImages);

Error in pipeline.DemonLAST/prepMasterDark (line 868)
                    Obj = Obj.loadCalib('ReadProduct',{'Bias'});

Error in pipeline.DemonLAST/main (line 1225)
                    [Obj, FN_Dark] = Obj.prepMasterDark('Move2raw',true);
 
>>

**Comment by EranOfek** [comment]
Can not reproduce bug (working now).
