### ISSUE TITLE
runPipeLast crashes because moveFiles does not create folders when moving focus images

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#111]
>> pipeline.last.runPipeLAST(1, 'ScienceSearchStr', 'LAST.01.06.01_2023052*_clear_*_science_raw*Image*.fits')
Error using movefile
No such file or directory

Error in io.files.moveFiles (line 94)
        movefile(Source, Destination{Ifile});

Error in pipeline.last.runPipeLAST (line 117)
        Destination = io.files.moveFiles(ListFoc, ListFocRaw, '', '',
        'MkDir',true);

The issue is in line 88 of moveFiles:

A directory is only created if:
if ~ischar(DestPath) && Args.MkDir

However, the default of DestPath is set to '' which is a char. Maybe it should be None instead?

**Comment by noralinn** [comment]
prepMasterDark also failed, because the calib directory didn't exist

**Comment by EranOfek** [comment]
pipeline.last.runPipeLAST is not supported - please use the pipeline.DemonLAST instead.
