### ISSUE TITLE
imUtil.psf.readULTRASATlabDB - link encoded

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#112]
Link encoded in text of this function.
Need to make it available via the Installer class.

**Comment by EranOfek** [comment]
Also add to help info re where the file is saved - the purpose of this function is not clear

**Comment by EranOfek** [comment]
Move all constants to the beginning of code

**Comment by agioffe** [comment]
Do we really wish the user to download the whole raw PSF DB (22 Gb)? I suppose that the 5 digested versions would be enough. If we do not wish it, then the user will never have to use this function.

**Comment by EranOfek** [comment]
This should be part of the external data that can be retrieved using the
Installer class.
eran

**Comment by agioffe** [comment]
Changed the link to the Installer class function. The data is temporarily at WIS Dropbox, and the Installer now knows how to draw them into ~/matlab/data/ULTRASAT/PSF . When our own repository is up, will move the archive there.
