### ISSUE TITLE
bug in imUtil.properSub.translient

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#113]
N = randn(1726,1725);
R = randn(1726, 1725); 
Pn = imUtil.kernel2.gauss(2,[1726 1725]);
Pr = imUtil.kernel2.gauss(2.5,[1726 1725]);
Fn = 1;
Fr = 1;
SigmaN = 1;
SigmaR  = 1;
[Z2,Zhat,Norm] = imUtil.properSub.translient(N.*Fn, R.*Fr, Pn, Pr, SigmaN, SigmaR);
K>> Arrays have incompatible sizes for this operation.

Error in imUtil.properSub.translientAuxiliary (line 67)
    Z2Prefactors = Znom./Zden.*Kxy;

Error in imUtil.properSub.translient (line 84)
    [Z2Prefactors,Norm] = imUtil.properSub.translientAuxiliary(Pnhat, Prhat, SigmaN, SigmaR, 'IsPsfFFT',true,'Eps',Args.Eps);

Error in imProc.sub.properSubtraction (line 139)
        [Z2,Zhat,Norm] = imUtil.properSub.translient(N.*Fn, R.*Fr, Pn, Pr, SigmaN, SigmaR);

**Comment by EranOfek** [comment]
Also, please add optional input argument Fn, Fr (default = 1).

**Comment by EranOfek** [comment]
Fixed by Amir Sharon.

**Comment by EastEriq** [comment]
What is a translient?

Il 29 mag 2023 21:23, EranOfek ***@***.***> ha scritto:

Closed #113<https://github.com/EranOfek/AstroPack/issues/113> as completed.
