### ISSUE TITLE
LAST pipeline fails when creating calibration files

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#118]
`D = pipeline.DemonLAST`
`D.main('StartJD',[25 4 2023], 'ReloadCalib', true);`

fails with:

Error using fitsiolib
CFITSIO library error (105): couldn't create the named file

Error in matlab.io.fits.createFile (line 34)
fptr = fitsiolib('create_file',filename);

Error in FITS.write (line 1007)
                Fptr = matlab.io.fits.createFile(FileName);

Error in AstroImage/write1 (line 1151)
                                    FITS.write(Obj.(DataProp), Name,
                                    'Header',HeaderDataToWrite,...

Error in pipeline.DemonLAST/prepMasterFlat (line 1052)
                        write1(CI.Flat, FileN{1}, 'Image');

Error in pipeline.DemonLAST/main (line 1228)
                    [Obj, FN_Flat] = Obj.prepMasterFlat('Move2raw',true);

Before failing it produced some calibration files (everything from May 30):

ocs@last06e:/last06e/data1/archive/LAST.01.06.01/calib$ ls -l
total 3612592
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:51 LAST.01.06.01_20230331.162654.011_clear_____twflat_proc_Image_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:51 LAST.01.06.01_20230331.162654.011_clear_____twflat_proc_Mask_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:51 LAST.01.06.01_20230331.162654.011_clear_____twflat_proc_Var_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:52 LAST.01.06.01_20230401.162629.412_clear_____twflat_proc_Image_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:52 LAST.01.06.01_20230401.162629.412_clear_____twflat_proc_Mask_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:52 LAST.01.06.01_20230401.162629.412_clear_____twflat_proc_Var_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 28 08:21 LAST.01.06.01_20230419.223153.943_clear_____dark_proc_Image_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 28 08:21 LAST.01.06.01_20230419.223153.943_clear_____dark_proc_Mask_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 28 08:21 LAST.01.06.01_20230419.223153.943_clear_____dark_proc_Var_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:52 LAST.01.06.01_20230424.164228.295_clear_____twflat_proc_Image_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:52 LAST.01.06.01_20230424.164228.295_clear_____twflat_proc_Mask_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 30 08:52 LAST.01.06.01_20230424.164228.295_clear_____twflat_proc_Var_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 28 08:47 LAST.01.06.01_20230425.164256.447_clear_____twflat_proc_Image_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 28 08:47 LAST.01.06.01_20230425.164256.447_clear_____twflat_proc_Mask_1.fits
-rw-rw-r-- 1 ocs ocs 246614400 May 28 08:47 LAST.01.06.01_20230425.164256.447_clear_____twflat_proc_Var_1.fits

**Comment by EranOfek** [comment]
On which computer?

**Comment by EranOfek** [comment]
Can not reproduce the bug of last03e
