### ISSUE TITLE
bug in Component object copy() function

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#122]
AI=AstroImage({ones(100,100)}, 'Mask',{uint32(ones(100,100))},'Exp',{ones(100,100)},'Back',{ones(100,100)});
CI=AI.copy;

% from now on AI and CI should be two sepearte objects:
 
AI.Image(1)=10;
CI.Image(1)  % indeed return 1
AI.Back(1)=10;                
CI.Back(1)  % indeed return 1 

% however:
AI.Exp(1)=10;                
CI.Exp(1)  % return 10 instead of 1

It looks like that the copy() function didn't copy the ExpImage object in the AstroImage ExpData property.
Note that ExpImage is a newly defined class...

**Comment by amir-24** [comment]
Added in AstroImage.copyElement(Obj):

NewObj.ExpData      = Obj.ExpData.copy();

Fixed the issue.
