### ISSUE TITLE
forcedPhotAll not working

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#123]
Running `MS=pipeline.last.forcedPhotAll('BasePath', '/last06e/data1/archive/LAST.01.06.01', 'BasePathArgs',{'SubDir','2023/05/'}, 'Coo',[210.910674637,+54.3116510708], 'FileTemp','LAST*_211+54_*010_sci_proc_Image_*.fits')`  today after pulling from github does not work (it worked on Thursday). 

The error message:
```
Error using AstroImage.readFileNamesObj (line 716)
Error defining property 'ImageData' of class 'AstroImage'. Unable to construct default object of class SciImage.

Error in pipeline.last.forcedPhotAll (line 65)
        AI = AstroImage.readFileNamesObj(FN,'Path',sprintf('.%s',filesep));
```

**Comment by EranOfek** [comment]
Please try again.
