### ISSUE TITLE
MatchedSources.read_rdir 

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#124]
` MS = MatchedSources.read_rdir('*_sci_merged_MergedMat_*.hdf5')` does not work if some subimages are missing. 

The error message:

 `Unable to perform assignment because the size of the left side is 83-by-1 and the size of the right side is 1-by-85.

Error in MatchedSources.read_rdir (line 255)
                            ResultO(1:Nepoch,Ipart) = Result([Part==Ipart].');`

In the MatchedSources.m (line 250):
`Nepoch = Nlist./Npart;`
If subimages are missing `Neopch ` is not an integer (`Nlist `is not dividable by 24).

Path to the directory where the command was run: 
   '/last06e/data1/archive/LAST.01.06.01/2023/05/23/proc'

**Comment by EranOfek** [comment]
try to execute with : 'OrderPart',[] argument and report if it is working...

**Comment by EranOfek** [comment]
I changed the default to [].
Please test and close issue if problem solved.

**Comment by EranOfek** [comment]
@noralinn 
please test

**Comment by YarinMS** [comment]
changing default to [] might have side effects. Specifically, the results of mergeByCoo(MS1,MS2) to properly merge two MatchedSources objects changed drastically, and so does the running time (longer than before this change). 

by using 
MatchedSources.read_rdir('*_sci_merged_MergedMat_*.hdf5', 'OrderPart' , 'CropID')
we can get an ordered matched sources object with dimensions of [epoches X subimage] , which from some reason help mergeByCoo(MS1,MS2) run faster and give us the result we are expecting for.

nothing to change but keep in mind that if you are using the function mergeByCoo(), you might want to change the argument of MatchedSources.read_rdir from [] to 'cropID'
