### ISSUE TITLE
MS.write1 does not save entire merged sources object

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#127]
Ran forced photometry and created a merged sources object using: 

`ms =  mergeByCoo(MSf(mask), MSf(100))`

When trying to save it the following error appears:

```
ms.write1('fp_sn2023ixf_202305_C1.hdf5')
Error using hdf5lib2
The class of input data must be double instead of double when the HDF5 class is H5T_IEEE_F64LE.

Error in H5D.write (line 100)
H5ML.hdf5lib2('H5Dwrite', varargin{:});

Error in h5write (line 166)
H5D.write(dataset_id,'H5ML_DEFAULT',memspace_id,filespace_id,dxpl,Data);

Error in MatchedSources/write1 (line 323)
                        h5write(FileName, sprintf('/%s',Obj.Fields{Idata}), Obj.Data.(Obj.Fields{Idata}));

```

A file is saved nevertheless, but it contains only 10 instead of 17 fields.

`test.Fields

ans =

  10×1 cell array

    {'Chi2dof'   }
    {'Dec'       }
    {'FLUX_PSF'  }
    {'MAGERR_PSF'}
    {'MAG_PSF'   }
    {'RA'        }
    {'X'         }
    {'Xstart'    }
    {'Y'         }
    {'Ystart'    }

>> ms.Fields

ans =

  17×1 cell array

    {'RA'          }
    {'Dec'         }
    {'X'           }
    {'Y'           }
    {'Xstart'      }
    {'Ystart'      }
    {'Chi2dof'     }
    {'FLUX_PSF'    }
    {'MAG_PSF'     }
    {'MAGERR_PSF'  }
    {'BACK_ANNULUS'}
    {'STD_ANNULUS' }
    {'FLUX_APER_1' }
    {'FLUX_APER_2' }
    {'FLUX_APER_3' }
    {'FLAG_POS'    }
    {'FLAGS'       }
`

test is reading in the saved file while ms is the original file that was saved.

When saving as a .mat, the file isn't valid and can't be read.

The MS object contain 825 stars and 2504 epochs. Maybe too big?

**Comment by noralinn** [comment]
Saved matlab session as:

`/last04e/data1/archive/LAST.01.04.01/fp_session.mat`

**Comment by EranOfek** [comment]
There were three problems:
1. MAGERR_PSF was complex numbers.
a. added a default treatment  for dealing with complex number
b. opened a separate issue re MAGERR_PSF.
3. bug in the 'mat' and 'matobj' options - fixed.
4. Incorrect call to the function - should be used like this:
ms.write1('tmp.mat','FileType','matobj')
ms.write1('tmp1.mat','FileType','mat')
