### ISSUE TITLE
Cannot run pipeline with -nodisplay option due to gui-abort-button

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#134]
The pipeline works without issues in the matlab graphical interface. But when running it in the terminal (last-matlab -nodisplay) it fails with:

```
>> D.main
Property assignment is not allowed when the object is empty.  Use subscripted
assignment to create an array element.

Error in tools.gui.stopButton (line 29)
    Hc(2).Children.String = Args.Msg;

Error in pipeline.DemonLAST/main (line 1223)
            [StopGUI, Hstop]  = tools.gui.stopButton('Msg',GUI_Text);

```

**Comment by EranOfek** [comment]
on which computer?

**Comment by EranOfek** [comment]
I need more information - put breajpoint in line 1223, what is the value of GUI_Text?

**Comment by EranOfek** [comment]
no display option can not use dispaly, so you are no suppose to use it:
instead use "-nodesktop"

In addition, I added a StopButton argument (default is true).
