### ISSUE TITLE
Pointing model can't be calculated for M5C2 data

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#147]
The following command crashes and closes matlab while running for the data of M5C2. It works for other cameras and mounts.

`[AllR,PM]=pipeline.last.pointingModel(‘LAST*PointingModel*sci*.fits’,’Nfiles’,115,’ConfigFile’,’/home/ocs/MyConfig’)`

The data is: 
`/last05e/data2/archive/LAST.01.05.02/new/LAST.01.05.02_20230614.215244.492_clear_PointingModel_001_001_001_sci_raw_Image_1.fits`
and onwards.

**Comment by noralinn** [comment]
Another thing I'm confused about:

The pointing model now takes data at dec 90. But those points don't show up in the model. Maybe `pipeline.last.pointingModel` ignores them?

The last lines of the pointing model are:

```
         [  45.000000,   63.000000,   -0.098853,   -0.098853],
         [  75.000000,   63.000000,   -0.077716,   -0.077716],
         [ -75.000000,   63.000000,   -0.192052,   -0.192052],
         [ -45.000000,   63.000000,   -0.199380,   -0.199380],
         [ -15.000000,   63.000000,   -0.180821,   -0.180821],
         [  25.714286,   81.000000,   -0.074287,   -0.074287],
         [  77.142857,   81.000000,   -0.025807,   -0.025807],
         [ -77.142857,   81.000000,   -0.160762,   -0.160762],
         [ -25.714286,   81.000000,   -0.146502,   -0.146502],
     ]
```

**Comment by EranOfek** [comment]
Don't take pointing model data at dec=90, just set it manually (or by modifying the code) to 0 at a few hour angles at dec=90 (see my mail).

**Comment by noralinn** [comment]
I also got data for a new pointing model starting from:

`LAST.01.05.01_20230616.213039.768_clear_PointingModel_001_001_001_sci_raw_Image_1.fits`

**Comment by EranOfek** [comment]
'MATLAB:imagesci:hdf5io:resourceNotFound'
       message: 'Unable to open 'GAIADR3_htm_625300.hdf5'. File or folder not found.'

it seems that the GAIA/DR3 catalog is not fully installed.
I am rsyncing the catalog.

**Comment by EranOfek** [comment]
Why are you using Nfile=115 ?

**Comment by noralinn** [comment]
This was because I took images at dec=90 and it was 105 in total. I changed the script now, so in the future it will be 108 again.

Nfiles=115 worked for other mounts/telescopes so I don't think it's the issue.

**Comment by EranOfek** [comment]
I will change it back to Inf.
Better to control the files via the file names.

**Comment by EranOfek** [comment]
1. Changed Nfile default to Inf.
2. Note that the way you selected the files you mixed two nights of pointing models. Not necceserly bad, but if something changed, this may be a problem and not recommended at this stage.
3. So use: 
[AllR,PM]=pipeline.last.pointingModel('LAST*20230616.*PointingModel*sci*.fits')
4. Can not recreate the problem. Works for me, and the file is in /home/ocs/con1
