### ISSUE TITLE
Correlation of calibration coefficients

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#153]
Since there is difference in astrometric solution of sources which are overlapped in two sub frames, it might be insightful to consider the correlation between the Zero Point (ZP) and the Color term (COL1). We also consider the correlation of each coefficient with the air mass of the subframe, the distance from the center of FOV and the distance from the center of the CCD.

- side-notes : while computing the distance from the center of FOV, the following parameters from a processed image header are considered:
    - Header.Data.RA4, Header.Data.RA2 in order to find the center of the sub frame
    - Header.Data.RA, Header.Data.Dec as the center of FOV
   Since Eran pointed that the latter aren't based on astrometric solution, we also consider the distance of the subframe from the center of the CCD
    - To find the Distance of a subframe from the center in pixels we considered Header.Data.ORIGSEC as the boundaries of the subframe ($[x_0 \   x_N \ y_0  \ y_N]$), while computing it's center.
    - We find the airmass of the center of a subframe frame by using the coordinates aquired while computing the distance from the FOV

Results are presented for two distinct frames taken in observation date - 27/04/23 , (19:11:46 and 21:53:50)

- For each frame we plot : 
   * ZP vs COL1
   * Airmass vs Coefficients
   * Distance [deg] vs Coefficients
   *  Distance [pixel] vs Coefficients

Most visible is the anti-correlation between the ZP to the distance from the center, 

presenting results for obs  - 27042023_1911146 (target is rising) : 

ZP vs COL1 ,

![ZPVSCOL1_1911](https://github.com/EranOfek/AstroPack/assets/118757319/d029f56f-1182-4b77-8496-7f15fa9ada25)

 Airmass vs Coefficients,
![AMvsCoeff1911](https://github.com/EranOfek/AstroPack/assets/118757319/7787a9f5-86f6-494c-bb76-1fa50895b8a8)

Distance from center of FOV vs coefficients,
![3](https://github.com/EranOfek/AstroPack/assets/118757319/0f65a51e-90cf-4742-9fb8-29363d6048db)

Distance from center of CCD vs coefficients,
![4](https://github.com/EranOfek/AstroPack/assets/118757319/055432cb-0263-4754-86b6-dbfba2539ff6)

Now, we would like to consider a frame taken at airmass ~ 1. Where the anti-correlation of the coefficients is stronger,
results for obs  - 27042023_215350 (AM ~ 1) : 

ZP vs COL1 ,
![5](https://github.com/EranOfek/AstroPack/assets/118757319/6179ea36-7255-4285-9765-88b7dcd4d492)

 Airmass vs Coefficients, * 21:53:50 in title
![AMvsCoeff2150jpg](https://github.com/EranOfek/AstroPack/assets/118757319/6793b62c-6934-4b57-b7ba-f1583d1dbff5)

Distance from center of FOV vs coefficients,
![67](https://github.com/EranOfek/AstroPack/assets/118757319/144a966c-ac98-402e-b27a-5106e4dbe2d5)

Distance from center of CCD vs coefficients,
![8](https://github.com/EranOfek/AstroPack/assets/118757319/aa0e863a-36b1-4eaa-ab21-7a3d851fff0e)

**Comment by EranOfek** [comment]
Good.
We should be aware of this.
