### ISSUE TITLE
Pipeline shoud use flats (and darks) from the time of the observations

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#158]
When running of old data using the most recent calibration files might not be appropriate. Instead the pipeline should use the files closest in time.

**Comment by EranOfek** [comment]
Option to load calibration files near some date was added to:
pipeline.DemonLAST/loadCalib

For examples see:
https://github.com/EranOfek/AstroPack/wiki/pipeline.DemonLAST

**Comment by EranOfek** [comment]
please test.
