### ISSUE TITLE
pipeline fails while validating filename for M8C3, but not for M8C4

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#159]
The pipeline fails for data on LAST.01.08.03, but works without problems for LAST.01.08.04.

`Args.TempRawSci` is `*_sci_raw_*.fits` for both cameras.

```
D=pipeline.DemonLAST

D = 

  DemonLAST with properties:

             CI: [1×1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 1
      CamNumber: []
       BasePath: '/last08w/data1/archive/LAST.01.08.03'
        NewPath: '/last08w/data1/archive/LAST.01.08.03/new'
      CalibPath: '/last08w/data1/archive/LAST.01.08.03/calib'
     FailedPath: '/last08w/data1/archive/LAST.01.08.03/failed'
        LogPath: '/last08w/data1/archive/LAST.01.08.03/log'
         ObsCoo: [35 30 415]
           Name: []
       DataType: [0×0 AstroDataType]
         Config: [1×1 Configuration]
         Logger: [1×1 MsgLogger]
       UserData: []

>> D.loadCalib

ans = 

  DemonLAST with properties:

             CI: [1×1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 1
      CamNumber: []
       BasePath: '/last08w/data1/archive/LAST.01.08.03'
        NewPath: '/last08w/data1/archive/LAST.01.08.03/new'
      CalibPath: '/last08w/data1/archive/LAST.01.08.03/calib'
     FailedPath: '/last08w/data1/archive/LAST.01.08.03/failed'
        LogPath: '/last08w/data1/archive/LAST.01.08.03/log'
         ObsCoo: [35 30 415]
           Name: []
       DataType: [0×0 AstroDataType]
         Config: [1×1 Configuration]
         Logger: [1×1 MsgLogger]
       UserData: []

>> D.main('StartJD',2460111.2374,'EndJD',2460111.33834)
Error using FileNames/validateType (line 352)
Illegal value found in Type property (element 1)

Error in FileNames/set.Type (line 146)
            Obj.validateType;

Error in FileNames.generateFromFileName (line 311)
                Obj.Type{Ilist}     = SplitName{8};

Error in pipeline.DemonLAST/main (line 1290)
                FN_Sci   = FileNames.generateFromFileName(Args.TempRawSci, 'FullPath',false);
```

**Comment by EranOfek** [comment]
Please investigate - eg
Put a break point in line 311…  and check the content of Obj.Type and
SplitName 8
Thanks

**Comment by EranOfek** [comment]
Note that you can use [D M Y] instead of JD.

**Comment by EranOfek** [comment]
The system try to read an image which name is not legal:
LAST.01.08.03_20230405.185436.702_clear_bias_singleinvideomode_001_001_001_sci_raw_Image_1.fits

there are several such images and they were all taken on 20230405/06.
So I guess this is a local problem.

you can move these files to a temp dir, but tell Enrico where they are so he can try to figure out what happens,
and delete these files when done.

**Comment by EastEriq** [comment]
what is illegal in this name? `_clear_bias_singleinvideomode_` in the place of *_filter_target_*? I don't think it is my code which sets it. If it appears only on that date, and further biases were taken later, I would consider the problem solved since then.
I remark that there are as well `_clear_singlemode_`, `_clear_singleinvideomode_`, `_clear_bias_singlemode_offset6_` and the like.

**Comment by EastEriq** [comment]
Also, I'm not familiar with the directory logic, but on last08w I see that `/last08w/data1/archive/LAST.01.08.03` has various subdirs, whereas `/last08w/data1/archive/LAST.01.08.04` is empty. Conversely `/last08w/data2/archive/LAST.01.08.03` is empty and 04 has data. Are the empty dirs in the other data directory intentional?

**Comment by EranOfek** [comment]
some of the directories will be removed.
there should be a new/ calib/ failure/ and YYYY/ dirs.
eran

**Comment by noralinn** [comment]
Same on M8C3. I'm deleting the files.

To prevent this issue we could make the "_" character in the field name invalid.

**Comment by EastEriq** [comment]
I quite believe that they were temporary names given by who tried the flats script that day. My OCS code only does the writing after receiving the arguments. Let me know if there problem persists, and if you think that a fix is due on my part

Il 22 giu 2023 14:17, noralinn ***@***.***> ha scritto:

Same on M8C3. I'm deleting the files.

To prevent this issue we could make the "_" character in the field name invalid.
