### ISSUE TITLE
M3C4 had many hot pixels in the first ~4h of 20230626

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#166]
Science images until 20230626.200001.715 (at least) have many hot pixels across the entire chip. And the background stddev is close to 200. See e.g. :

`LAST.01.03.04_20230626.200001.715_clear_248+54_008_001_001_sci_raw_Image_1.fits` and early images during the same night.

An hour later the images look normal and the stddev is back to ~20. See e.g.:

`LAST.01.03.04_20230626.210018.099_clear_262+61_009_001_001_sci_raw_Image_1.fits`

Camera temperature was -5deg for both images and cooling power ~60%. A test image taken now (a day later) also looked ok.

Yahel was at the observatory, maybe she fixed anything?

Images taken at 20h and 21h UTC with the same camera.

![Screenshot from 2023-06-27 21-48-03](https://github.com/EranOfek/AstroPack/assets/14293969/76912137-d0ad-4e8b-b933-456cf2b79857)

**Comment by EranOfek** [comment]
copy the image to my collection of problematic images in:
euler:/raid/eran/projects/telescopes/LAST/Images_PipeTest/testPipe/LAST.01.02.02/knownIsuues/
I guess that this is some sort of electronic problem that requires power recycling.

**Comment by EranOfek** [comment]
So apparently the problem was fixed by itself.
In the future, we need a process to identify this problems.

**Comment by noralinn** [comment]
Apparently, it disappeared instantaneously in the middle of a 20 image visit.


![Screenshot from 2023-06-28 15-22-27](https://github.com/EranOfek/AstroPack/assets/14293969/ae48925f-4581-4063-8687-6aa6977631f0)


```
/last03w/data2/archive/LAST.01.03.04/new$ ls LAST.01.03.04_20230626.20*243-10*
LAST.01.03.04_20230626.205006.433_clear_243-10_001_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205026.435_clear_243-10_002_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205046.442_clear_243-10_003_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205106.451_clear_243-10_004_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205126.462_clear_243-10_005_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205146.455_clear_243-10_006_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205206.461_clear_243-10_007_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205226.473_clear_243-10_008_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205246.473_clear_243-10_009_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205306.483_clear_243-10_010_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205326.479_clear_243-10_011_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205346.501_clear_243-10_012_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205406.494_clear_243-10_013_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205426.504_clear_243-10_014_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205446.518_clear_243-10_015_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205506.517_clear_243-10_016_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205526.519_clear_243-10_017_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205546.533_clear_243-10_018_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205606.535_clear_243-10_019_001_001_sci_raw_Image_1.fits
LAST.01.03.04_20230626.205626.559_clear_243-10_020_001_001_sci_raw_Image_1.fits
```

**Comment by EastEriq** [comment]
Images are not anymore in `/last03w/data2/archive/LAST.01.03.04/new`, so...

Processing to identify the problem: Nora suggests global_stdev>=10*usual_stdev as a criterion. I would check if the pipeline doesn't by chance already mark something like that, and produces a mask with flagged hotpixels. Then it may be a matter of counting them.

Possible correlations: the FITS header contains data about a few candidates, like Unit.Temperature, Camera.Temperature, Camera.CoolingPower; eventually even the time of the night (=since the beginning of the operation). Plot them against the good/bad flag, and see if bad images accumulate in a specific region of the parameter space. It may well be that hot pixels don't necessarily show up if a given parameter is over a threshold, but anyway the negative information is as valuable (=there are never hot pixels if...)

**Comment by EastEriq** [comment]
Uh, now that I think the SDK has also a half working support for the camera humidity sensor (we are not reading it now but maybe we could)

**Comment by EastEriq** [comment]
https://github.com/EastEriq/LAST_QHYccd/blob/9bf30298e90683ccae4c7ba26bee639b48accfeb/%2Binst/%40QHYccd/QHYccd.m#L169
