### ISSUE TITLE
`[AI_array,Sources]=imProc.sources.psfFitPhot(AI_array)` returns the `Sources` of the last image only

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#175]
>> [AI,Sources]=imProc.sources.psfFitPhot(AI)

AI = 

  1×3 AstroImage array with properties:

    Image
    Back
    Var
    Mask
    Exp
    Header
    Key
    PSF
    Table
    ImageData
    BackData
    VarData
    MaskData
    ExpData
    HeaderData
    CatData
    PSFData
    WCS
    PropagateErr
    Name
    DataType
    Config
    Logger
    UserData

```
Sources = 

  struct with fields:

            Chi2: [534×1 double]
             Dof: [534×1 double]
            Flux: [534×1 double]
             SNm: [534×1 double]
             Mag: [534×1 double]
              DX: [534×1 double]
              DY: [534×1 double]
           Xinit: 9
           Yinit: 9
         Xcenter: 9
         Ycenter: 9
    ConvergeFlag: [0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 … ]
           Niter: 8
          RoundX: [534×1 double]
          RoundY: [534×1 double]
               X: [534×1 double]
               Y: [534×1 double]
          MagErr: [534×1 double]
```

**Comment by EranOfek** [comment]
1. Note that the first output argument is the UPDATED AstroImage containing additional columns with the PSF photometry for the sources.
2. The second output argument is some additional information needed mainly for debuging (Usually you don't need it).
3. Altough it is simple fix, I prefer to leave it as is. I updated the help section accordingly.
