### ISSUE TITLE
`imProc.calib.photometricZP` error

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#176]
```
>> imProc.calib.photometricZP(AI)
Unable to perform assignment because value of type 'AstroCatalog' is not convertible to
'double'.

Error in imProc.calib.photometricZP (line 236)
                [PhotCat(Iobj)] = imProc.cat.getAstrometricCatalog(RA, Dec, 'CatName',Args.CatName,...

Caused by:
    Error using double
    Conversion to double from AstroCatalog is not possible.
```

**Comment by EastEriq** [comment]
I can fix it in one of my use cases, single AI, by putting `PhotCat = AstroCatalog;` instead of https://github.com/EranOfek/AstroPack/blob/aee43ae0c495e8860d0b7c6a9527f68a6d86af1b/matlab/image/%2BimProc/%2Bcalib/photometricZP.m#L206,
but frankly I don't know the side consequences for all other possible calling sequences of this function.

**Comment by EastEriq** [comment]
The latter seems to happen at the second iteration of line 216 in fminsearch, when
```
K>> x

x =

   NaN   NaN

K>> varargin

varargin =

  0×0 empty cell array

K>> funfcn(x,varargin{:})

ans =

  0×1 empty double column vector
```

**Comment by EastEriq** [comment]
in line52 of bundingCircle
```
Radius = max(celestial.coo.sphere_dist_fast(Center(1), Center(2), Lon(:), Lat(:)))
```
Lon and Lat are empty at the second iteration

**Comment by EranOfek** [comment]
As you say, a possible fix for the first problem is:
%PhotCat = Astrocatalog([Nobj 1]);
However, I kept it commented because I want to test it carefully.

**Comment by EastEriq** [comment]
> The latter seems to happen at the second iteration of line 216 in fminsearch, when
> 
> ```
> K>> x
> 
> x =
> 
>    NaN   NaN
> 
> K>> varargin
> 
> varargin =
> 
>   0×0 empty cell array
> 
> K>> funfcn(x,varargin{:})
> 
> ans =
> 
>   0×1 empty double column vector
> ```

which I suspect is once more due to what observed in issues #173 and #174, i.e. no sources matched for AstroImages beyond the first.

**Comment by EranOfek** [comment]
Fixed by declaring:
PhotCat = AstroCatalog([Nobj 1]) in line 206.
Need to verify didn't affect the pipeline.

**Comment by EastEriq** [comment]
Regression? today I have
```
>> AI(1).CatData

ans = 

  AstroCatalog with properties:

           JD: 2.4562e+06
      Catalog: [367×53 double]
     ColNames: {1×53 cell}
     ColUnits: {1×53 cell}
      ColDesc: {}
    SortByCol: 53
     IsSorted: 0
         Name: []
     DataType: Cat
       Config: [1×1 Configuration]
       Logger: [1×1 MsgLogger]
     UserData: []
>> imProc.calib.photometricZP(AI(1))

ans = 

  AstroImage with properties:

           Image: [2059×2048 double]
            Back: [2059×2048 double]
             Var: [2059×2048 double]
            Mask: [2059×2048 uint32]
             Exp: []
          Header: {293×3 cell}
             Key: [1×1 struct]
             PSF: [17×17 double]
           Table: [367×53 table]
       ImageData: [1×1 SciImage]
        BackData: [1×1 BackImage]
         VarData: [1×1 VarImage]
        MaskData: [1×1 MaskImage]
         ExpData: [1×1 ExpImage]
      HeaderData: [1×1 AstroHeader]
         CatData: [1×1 AstroCatalog]
         PSFData: [1×1 AstroPSF]
             WCS: [1×1 AstroWCS]
    PropagateErr: 0
            Name: []
        DataType: [0×0 AstroDataType]
          Config: [1×1 Configuration]
          Logger: [1×1 MsgLogger]
        UserData: []

```
But the catalog of AI(2) has only 51 columns, hence 
```
>> AI(2).CatData

ans = 

  AstroCatalog with properties:

           JD: 2.4562e+06
      Catalog: [440×51 double]
     ColNames: {1×51 cell}
     ColUnits: {1×51 cell}
      ColDesc: {}
    SortByCol: []
     IsSorted: 0
         Name: []
     DataType: Cat
       Config: [1×1 Configuration]
       Logger: [1×1 MsgLogger]
     UserData: []
>> imProc.calib.photometricZP(AI(2))
Error using AstroCatalog/boundingCircle
Can not find RA/Dec coordinates in catalog

Error in imProc.calib.photometricZP (line 229)
                    [RA, Dec, CircleRadius] = boundingCircle(Cat, 'OutUnits','rad', 'CooType','sphere');
 

```

**Comment by EastEriq** [comment]
On the other side,
```
    AI=imProc.astrometry.addCoordinates2catalog(AI,'OutUnits','degrees');
    [AI, ZP, PhotCat] =imProc.calib.photometricZP(AI);%,'Plot',true);
```
gets stuck for very long time in trying to load catalogs. But this happens only for images of the M81 set, an not for another set (formerly, both were ok)

**Comment by EastEriq** [comment]
Seems that the astrometry for AI(2) is wrong again. GaiaDR2 sources (green) don't match the image. Maybe wrong fix of #176?
![image](https://github.com/EranOfek/AstroPack/assets/16066531/c84139cc-668c-4175-b658-d2d124bdd95e)

**Comment by EastEriq** [comment]
commit f0a4ec1b1c7e064f5a24bd7611fea55ae37621f2?

**Comment by EastEriq** [comment]
Closing and moving the discussion to #182, where it seems to belong
