### ISSUE TITLE
`AstroImage.WCS` and `AstroImage.Header` sync

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#183]
should get/sets be synchronized when fields match? E.g.
```
AI.WCS.CRPIX(2)=123.456;
```
should be automatically be copied as 
```
AI.HeaderData.setVal('CRPIX2',123.456)
```
and viceversa?

**Comment by EranOfek** [comment]
There are two AstroImage methods to do this:
populateWCS (header to WCS)
propagateWCS (WCS to header)

If we do it automatically we may encounter infinite loops - any suggestions?

**Comment by EranOfek** [comment]
For the specific case you aredealing with:
CI(2).WCS.CRPIX(2)=CI(2).WCS.CRPIX(2)-(4096-2059)
and then do propagateWCS

**Comment by EastEriq** [comment]
> If we do it automatically we may encounter infinite loops - any suggestions?

call them after a set only if the value changed - but it is quite tedious to write the conditional inside every possible accessor

**Comment by EranOfek** [comment]
The sync should be done by any specific (low level) function that is running on the data.
