### ISSUE TITLE
`imUtil.art.injectSources`  errors for sources on the edge

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#184]
e.g.
```
>> imUtil.art.injectSources([2059,2048],[2041.5,1012.9,1],rand(17,17));
Error using sub2ind
Out of range subscript.

Error in imUtil.art.injectSources (line 88)
                ind = sub2ind([SizeImageX,SizeImageY],Yind(flag),Xind(flag));
```
That shouldn't happen IMHO

**Comment by EastEriq** [comment]
(the same error happens at line 126, which has the same code, for the real use case, which is many sources and a single PSF)

**Comment by EranOfek** [comment]
It is working now.
Also replaced sun2ind with:
imUtil.image.sub2ind_fast

**Comment by EastEriq** [comment]
> Also replaced sun2ind with:
> imUtil.image.sub2ind_fast

you did it? I don't see it. Maybe push?
