### ISSUE TITLE
bug in readtable1

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#185]
readtable1
1. if not deployed function will fail, need to change this.
2. do not write every operation to log file...

**Comment by elhadan** [comment]
Does this issue refer to io.files.readtable1?
I need some more info on which calls make this function fail.

**Comment by elhadan** [comment]
Fixed.

**Comment by EranOfek** [comment]
please describe the fix

**Comment by elhadan** [comment]
The function tried to load the file through a variable called FileName, which was initialized only in the isdeployed clause. This caused any non-deployed cases to try to load a file from a missing variable.

I fixed the function to correctly use the input argument in the non-deployed case (and made sure isdeployed cases will work with the same var as well).
