### ISSUE TITLE
what is the recommended way to mask airplane and satellites streaks?

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#188]
I found no hint on cursive skimming of the wiki.

I have egregious examples of PTF images where they have not been masked at origin, and are mistakenly interpreted as chains of sources; i.e. /raid/enrico/PTF/2ndTake/images/level1/proc/2012/09/29/f11/c2/p5/v2/PTF_201209294633_i_p_scie_t110708_u016532761_f11_p100037_c02.fits

I remember a poster of yours, a long time ago, hanging on the dining corner wall
![image](https://github.com/EranOfek/AstroPack/assets/16066531/3a644e6f-8595-41fb-bde6-c36b080baf91)

**Comment by EranOfek** [comment]
This is likely a satellite.
In principle we can run radon transform on the images (either Guy code, or
the matlab built in function).

**Comment by EastEriq** [comment]
Ah, and out of principle? Nothing ready?
Radon? I'd say Hough.

**Comment by EranOfek** [comment]
Hough transform will be good too, but not optimal for low S/N trails. On
the other hand low S/N trails are not important
It will be good to have a function in imProc that run a Hough transform on
AstroImage object.

Eran

**Comment by EastEriq** [comment]
yes it will be good. Where is the code?

**Comment by EranOfek** [comment]
There is a built in hough transform in matlab - google will know

**Comment by EastEriq** [comment]
I know, but I hoped you had already something more astrological done. Like deciding acceptance thresholds, thickness as function of the already known PSF, and so on

**Comment by EastEriq** [comment]
Besides, I don't uses google. It spies my moves and tries to implant me with thoughts.

**Comment by EranOfek** [comment]
There is - i will dig it up when i am back

**Comment by EranOfek** [comment]
https://github.com/guynir42/radon
let's inspect it together.

**Comment by EastEriq** [comment]
Ok let's discuss on Sunday

**Comment by EranOfek** [comment]
new package:
imUtil.frt
with basic tolls taken from Guy's repository.

**Comment by EastEriq** [comment]
I see two possible ways: 
1. mark all the streak pixels in the mask as 'Streak', given a way to identify them. I don't have a reliable method fot this available, as of now. Tentatively it could be based on morphological operations on a binarized image like `Image>Back+2*sqrt(Var)`
2. detect the sources as they come, classify those which are close and collinear as a track, and eventually drop them from the image catalog. For that I have now a working function, `impProc.sources.findTrack`, which does a decent job, albeit a bit dependent on empirical parameters

**Comment by EranOfek** [comment]
Made some minor changes:
1. Add "BitName_Streak" argument.
2. 2. updated the help for consistency.
