### ISSUE TITLE
coreFRT.cpp works only for double input

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#191]
In: matlab/image/+imUtil/+frt/coreFRT.cpp works only for double inputs.
need a version that works on both single and double inputs.

**Comment by elhadan** [comment]
Done:
1. Added new coreFRT_single.cpp that accepts single as input (output is also single).
2. frt.m: removed casting to double (commented out for now), and added an if statement to check if single or double before calling the correct cpp file.
3. CompileCoreFRT now compiles both versions.

Comments:
1. If you are pleased with this - we can remove the commented line from point 2 above.
2. The double version was not renamed to "coreFRT_double" as I wasn't sure if it might affect other places in the code... Should I change it?
3. I'm working on windows, so I haven't pushed the compiled linux version (mexa).

**Comment by EranOfek** [comment]
excellent.
1. yes - change name to coreFRT_double
2. open a +mex directory and move mex files to this dir + update the calls
in frt.m
3. let me know when you are done, so I will compile again on linux...
Thanks,
Eran

**Comment by EranOfek** [comment]
linux compiled and pushed
