### ISSUE TITLE
FileNames/jd2str bug

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#196]
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] pipeline.DemonLAST try error: Expected one output from a curly brace or dot indexing expression, but there were 2 results. / funname: FileNames.jd2str @ line: 508
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] pipeline.DemonLAST try error: Expected one output from a curly brace or dot indexing expression, but there were 2 results. / funname: FileNames.jd2str @ line: 508
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] Exception: id=MATLAB:index:expected_one_output_from_expression msg=Expected one output from a curly brace or dot indexing expression, but there were 2 results.
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] Exception: id=MATLAB:index:expected_one_output_from_expression msg=Expected one output from a curly brace or dot indexing expression, but there were 2 results.
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] stack: Ind=1; FunName=FileNames.jd2str; line=508
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] stack: Ind=1; FunName=FileNames.jd2str; line=508
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] stack: Ind=2; FunName=FileNames.getProp; line=539
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] stack: Ind=2; FunName=FileNames.getProp; line=539
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] stack: Ind=3; FunName=FileNames.genFile; line=744
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] stack: Ind=3; FunName=FileNames.genFile; line=744
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] stack: Ind=4; FunName=FileNames.genFull; line=932
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] stack: Ind=4; FunName=FileNames.genFull; line=932
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] stack: Ind=5; FunName=writeProduct; line=183
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] stack: Ind=5; FunName=writeProduct; line=183
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 localhost last-pipeline[736589]: [ERR] stack: Ind=6; FunName=DemonLAST.main; line=1575
== last10e/last-messages.log.4.gz:Jul 14 06:00:16 last10e last-pipeline[736589]: [ERR] stack: Ind=6; FunName=DemonLAST.main; line=1575
== last10e/last-messages.log.4.gz:Jul 14 06:00:17 localhost last-pipeline[736589]: [ERR] pipeline.DemonLAST: 20 images moved to failed directory
== last10e/last-messages.log.4.gz:Jul 14 06:00:17 last10e last-pipeline[736589]: [ERR] pipeline.DemonLAST: 20 images moved to failed directory
== last10e/last-messages.log.4.gz:Jul 14 06:56:24 localhost last-pipeline[736589]: [ERR] pipeline.DemonLAST try error: Cannot open the specified file. / funname: xxhash @ line: 27
== last10e/last-messages.log.4.gz:Jul 14 06:56:24 last10e last-pipeline[736589]: [ERR] pipeline.DemonLAST try error: Cannot open the specified file. / funname: xxhash @ line: 27

**Comment by noralinn** [comment]
For which telescope and which data is it?

It seems that at the moment some process copies most images from new to failed. I would wait for this to be fixed before trying to rerun the pipeline.

I've seen the jd2str bug several times.

**Comment by EranOfek** [comment]
last10e: see error message.
1. Stop the pipeline service (see instructions in Arie message).
2. copy the the content of failed to new
