### ISSUE TITLE
pipeline.DemonLAST / fwhm

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#199]
In order to use the forced photometry tool, we would like to run the pipeline with an option to save the proc images as well, by executing :
<img width="1110" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/74aebdc0-03b7-4256-ba1f-914c4514b50e">

It looks like the pipeline fails for all the images, although they look ok (to me). For this report I've used images from : 
group 1 - First image: `/last04w/data2/archive/LAST.01.04.04/new/LAST.01.04.04_20230720.230849.762_clear_264+65_020_001_001_sci_raw_Image_1.fits `
up to 
 group 3 - First image: `/last04w/data2/archive/LAST.01.04.04/new/LAST.01.04.04_20230720.215515.584_clear_264+65_020_001_001_sci_raw_Image_1.fits`

For the time being I'll leave these images in the failed directory, them and only them. In case anyone would like to examine them.
A failed image to demonstrate,
<img width="1325" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/f80befb6-fe8e-4f2b-90b8-00d3f23b8906">

While running the pipeline it fails in processing all the groups.
 We get the following try error:
`[ERR] pipeline.DemonLAST try error: Subscripted assignment between dissimilar structures. / funname: AstroPSF.curve_of_growth @ line: 432`
<img width="1542" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/ae18e6b0-8b2d-41bc-a29f-745c9590610d">

Eran asked to check what is the content of the PSFData in the Coadd AstroImage BEFORE the call to fhwm, to do so, we run the pipeline on debug mode and taking the next break points:

<img width="1539" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/8cb6a757-ed6a-413b-8455-57e34d54828c">
Which uses the function,

`pipeline.generic.multiRaw2procCoadd`

Next, we are sent to,

`pipeline.generic.singleRaw2proc`

<img width="1539" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/fe2669bb-e34d-42d0-a56f-b71e68d8d0d9">
Then, we encounter the first call to fwhm : 
<img width="1539" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/dd7464ef-b103-479f-a0f2-7224188dad58">

Assuming the content we are looking for lies in : 
`SI.PPSFData ` 
We get a non-empty AstroPSF object :
<img width="946" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/6dfb0a42-47c3-44f4-b53c-10cbbf72597b">

 Looking further,
 `SI.PSFData.Data` or `SI.PSFData.DataPSF` demands to choose a subframe (out of 24), looking at an arbitrary sub image (15) around the center of the detector  :

`SI.PSFData.Data == SI.PSFData.DataPSF` and  it looks like the PSF spreads the light in a gaussian manner, (as expected?) :
<img width="1538" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/e7069f4f-526f-4b2d-9b7e-bbf492987613">
And the lower part : 
<img width="1538" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/5e280bd3-4681-4bf9-91e2-cf5f568d23c0">
Making sure it is normalized.

So, assuming I understood what Eran asked, the problem originates deeper in `AstroPSF` and specifically in `imUtil.psf.curve_of_growth`

**Comment by YarinMS** [comment]
Sure, I’m currently away, I’ll do at as I get back to my computer.

Yarin

________________________________

**Comment by EranOfek** [comment]
The bug was due to another bug fix I introduced a few days ago.          
Line 425 in AstroPSF now reads:
 Result = struct('Radius',cell(Nobj,1), 'Sum',cell(Nobj,1), 'Npix',cell(Nobj,1), 'Mean',cell(Nobj,1), 'Med',cell(Nobj,1), 'CumSum',cell(Nobj,1));
