### ISSUE TITLE
Not a good name

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#2]
https://github.com/search?q=Astropack 4 other hits

https://www.astropackgulf.com/ Astropack Gulf LLC is one of the best distributors of Inkjet Printer, Food Inspection System, EBS Handjet Printers, Metal Detector, etc. in the Middle East region

https://astropack.en.ec21.com/ China supplier of notebook, calendar, label, book, catalog, nonwoven bag

https://www.dnb.com/business-directory/company-profiles.astropack_trading_inc.2f23efd23f1d160527536e531bed8c8c.html Astropack Trading Inc. is located in Rancho Cucamonga, CA, United States and is part of the Wholesale Sector Industry

https://www.indianastrologysoftware.com/professional/astrology-software.php AstroPack 1.0 Astrology Software Calculates Birth Star as well as calculation of various astrological properties of the nakshatra and horoscope

etc. etc.

**Comment by EranOfek** [comment]
MAATv2 is an alternative name.

**Comment by EastEriq** [comment]
[Nut](https://en.wikipedia.org/wiki/Nut_(goddess))?
