### ISSUE TITLE
pipeline.DemonLAST try error ;  funname : writeProduct

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#201]
A new error has been encountered while trying to run the pipeline with the following command :

`D.main('StartJD',[19 07 2023],'EndJD', [21 07 2023],'SaveEpochProduct',{'Image','Cat'})`

or 

`D.main('StartJD',[19 07 2023],'EndJD', [21 07 2023],'SaveEpochProduct',{'Cat'})`

In either way the pipeline fails and moves all images to the failed directory. It seem like the problem is after the processing phase and in the writing phase of the products :
![image](https://github.com/EranOfek/AstroPack/assets/118757319/d2889012-6dfb-402f-9e0a-a8a4ec075812)

Where the first red line states :
`[ERR] pipeline.DemonLAST try error: Number of elements in WriteHeader must be 1 or equal to the number of products / funname: writeProduct @ line: 121`

**Comment by EranOfek** [comment]
The correct syntax is:
'SaveEpochProduct',{'Image',[],'Cat',[]}
