### ISSUE TITLE
Error in pipeline.last.forcedPhotAll

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#202]
While trying to apply forced photometry on processed images, the following error is encountered :
<img width="1435" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/a933cbf6-a708-4bdf-bcad-9b572779a669">
We see that in forcedPhot `'Moving' = moving` but there is no documentation that explains how to control this argument using focedPhotAll.

The first thing comes to mind is maybe the coordinates given as an argument to the function `[ra1 , dec1]` are close to the subframe boundaries. But, this error is consistent with different coordinates from different fields. Providing two examples from the coordinates we tried to implement forcedPhotAll for : 

`pwd =  '/last02e/data1/archive/LAST.01.02.01/2023/07/20/proc/' ` :

`Object = 'LAST*_253+02_*022_sci_proc_Image_*.fits'`

`ra1 = 255.111679 ; dec1 = 3.6005`

<img width="1089" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/b164a61e-abf0-420e-8db3-38231e781e17">

Where it doesn't seem like the target itself could be outside of the image boundaries, ( maybe its the reference sources ? )

Second example :

`Object = 'LAST*_261+64_*018_sci_proc_Image_*.fits'`

`ra1 = 264.12176 ; dec1 = 66.73127`

<img width="1090" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/58eed453-8c4b-4116-88c6-78afa5e3c179">

It doesn't look like this error arise due to the location of the target coordinates.

**Comment by EranOfek** [comment]
1. The Moving argument is explained in the help of
imProc.sources.forcedPhot and in the wiki pages.
2. I am aware of this bug, but the fix is not straightforward. Meanwhile, I
increased the default of MinEdgeDist to 20. Not sure it will solve the
problem, but let me know.

**Comment by YarinMS** [comment]
1. Thanks for the clarification
2. git pulled on last02e to try again yield the same error.
I will try it on another set of data on last04w, just to be sure.

**Comment by YarinMS** [comment]
apparently,  when saving proc images for forced photometry, we should save the Mask file as well...

**Comment by YarinMS** [comment]
Together with a MASK file, the function works great.
Should we reverse the change in MinEdgeDist ?.

**Comment by EranOfek** [comment]
Not critical - 20 pix is good.
