### ISSUE TITLE
Pipeline Errors

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#206]
While running the pipeline over : 

last02e
last04w
last05w
last10w

We succeed in reducing data chosen from 02,05. BUT, we encountered two different errors in 04 and 10 which looks some what related :
last04w:
For:
`D.main('StopWhenDone',true,'StartJD',[20 07 2023],'EndJD',[21 07 2023],'SaveEpochProduct',{'Image','Mask','Cat',[]})`

<img width="1207" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/b59350f8-4b91-4331-9ef5-fd52911f1d10">

last10w : 

For : 
`D.main('StopWhenDone',true,'StartJD',[23 05 2023],'EndJD',[24 05 2023],'SaveEpochProduct',{'Image','Mask','Cat',[]})`, we get:

<img width="1551" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/33ebdb10-97df-493b-ba5d-70309d0a3b06">

This looks like something which is specific to the data ? since in last04w it fails after creating 11 'proc directories' , anyways, the data looks ok by eye in both computers.

**Comment by EranOfek** [comment]
Hi,

from some reason the CUMNUM keyword is not populated in the header.
Yarin - Please inspect the raw images in one of these computers, and check
if there is a CUMNUM keyword in the header.
Compare it with other computers.
If this is indeed missing, then one possibility is that LAST-OCS code is
not updated (run last-tool enforce).

**Comment by EranOfek** [comment]
This is a severe bug that fails the pipeline.
It was due to wrong variable names in the DB insertion block.
Problem fixed.
