### ISSUE TITLE
my second error with `imProc.match.mergeCatalogs`

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#207]
(see issue #204)
```
>> AC = AstroCatalog('/raid/enrico/PTF/2ndTake/proc2/2014/02/12/proc/*Ha663*_011*Cat*.fits')

AC = 

  1×2 AstroCatalog array with properties:

    JD
    Catalog
    ColNames
    ColUnits
    ColDesc
    SortByCol
    IsSorted
    Name
    DataType
    Config
    Logger
    UserData

>> MC=imProc.match.mergeCatalogs(AC')
 
Exiting: Maximum number of function evaluations has been exceeded
         - increase MaxFunEvals option.
         Current function value: NaN 

Index in position 2 exceeds array bounds.

Error in imProc.match.match_catsHTMmerged (line 82)
                MaxSearchRadius = max(CatH.Catalog(:,Args.MergedCatRadiusCol));

Error in imProc.match.mergeCatalogs (line 312)
        MergedCat = imProc.match.match_catsHTMmerged(MergedCat, 'SameField',false, 'CreateNewObj',false);
 
```
Is it perhaps a problem that I try to create a merged catalog from only two catalogs? Investigating...

**Comment by EastEriq** [comment]
at line 79 of `imProc.match.match_catsHTMmerged`, 
```
[CircX, CircY, CircR] = Cat.boundingCircle('OutUnits','rad', 'CooType','sphere');
```
returns three NaNs. This happen even if I call `imProc.match.mergeCatalogs` with 4 or 22 catalogs, but not for 44.

**Comment by EranOfek** [comment]
Can you check if what is the content of CatH before line 82 is executed?
Is it containing an empty catalog?

**Comment by EastEriq** [comment]
No , a full one (no Idea if valid, though, I haven't inspected).
Anyway, no more debugging tonight

Il 3 ago 2023 19:31, EranOfek ***@***.***> ha scritto:

Can you check if what is the content of CatH before line 82 is executed?
Is it containing an empty catalog?

**Comment by EranOfek** [comment]
and another think.
Inspect the WCS after astrometryRefine (by overplotting GAIA stars using ds9) - is it ok?

**Comment by EastEriq** [comment]
Answer to the second, yes, at least for this sample:
![image](https://github.com/EranOfek/AstroPack/assets/16066531/b8ee91be-a4c0-48de-97fa-9edb30309964)

**Comment by EranOfek** [comment]
Is all the lines in the catalogs contains NaNs or only some of them?

**Comment by EastEriq** [comment]
Only some of them.
Altogether it is difficult for me to debug here. I don't grok the logic of what should be merged with what. For one, I'm puzzled by the fact that if I try to lump a mosaic of different fields in a single big catalog, (in contrast with many epochs of the same field) , I seem to end up with an enormous structure, in which most of the information is that "this source is not in any of these so many fields". We have to discuss.

**Comment by EastEriq** [comment]
Actually, in one of the cases I'm debugging now, `Cat` (line 79 of `match_catsHTMmerged`, but coming from above) has some non-NaN elements, but all RA and Dec are NaN, which explains why 'cone_search` returns an empty set. As for how this comes, I don't know.

**Comment by EranOfek** [comment]
In this specific example all the RA/Dec in the AstroCatalog are NaN.
1. I added a check and it will spit out a useful error message...
2. You have to understand why all the RA/Dec are NaNs and if needed open a new ticket.
Thanks,
Eran

**Comment by EastEriq** [comment]
Your check does not trap the error; what is reported is the same as in the beginning:

```
>> AC = AstroCatalog('/raid/enrico/PTF/2ndTake/proc2/2014/02/12/proc/*1514*_011_002*Cat*.fits')

AC = 

  1×2 AstroCatalog array with properties:

    JD
    Catalog
    ColNames
    ColUnits
    ColDesc
    SortByCol
    IsSorted
    Name
    DataType
    Config
    Logger
    UserData

>> MC=imProc.match.mergeCatalogs(AC')
 
Exiting: Maximum number of function evaluations has been exceeded
         - increase MaxFunEvals option.
         Current function value: NaN 

Index in position 2 exceeds array bounds.

Error in imProc.match.match_catsHTMmerged (line 82)
                MaxSearchRadius = max(CatH.Catalog(:,Args.MergedCatRadiusCol));

Error in imProc.match.mergeCatalogs (line 312)
        MergedCat = imProc.match.match_catsHTMmerged(MergedCat, 'SameField',false, 'CreateNewObj',false);
 
```
Note that the two catalogs refer to the same field, with most sources in common. This is a plot of the sources positions
```
>> plot(AC(1).Catalog(:,52),AC(1).Catalog(:,53),'b.',AC(2).Catalog(:,52),AC(2).Catalog(:,53),'go')
```
![image](https://github.com/EranOfek/AstroPack/assets/16066531/44cea519-9eaa-4aaf-bdf9-0dea7ae70f5d)
I get the same error for disjoint fields. There seem to be subsets of my AstroImages for which I can create a MergedCatalog this way, and some subsets for which not. For example this is ok:
```
>> AC = AstroCatalog('/raid/enrico/PTF/2ndTake/proc2/2014/02/12/proc/*151*_0*_002*Cat*.fits')

AC = 

  1×44 AstroCatalog array with properties:

    JD
    Catalog
    ColNames
    ColUnits
    ColDesc
    SortByCol
    IsSorted
    Name
    DataType
    Config
    Logger
    UserData

>> MC=imProc.match.mergeCatalogs(AC')

MC = 

  AstroCatalog with properties:

           JD: 22.5
      Catalog: [29318×141 double]
     ColNames: {1×141 cell}
     ColUnits: {1×141 cell}
      ColDesc: {}
    SortByCol: 2
     IsSorted: 0
         Name: []
     DataType: Cat
       Config: [1×1 Configuration]
       Logger: [1×1 MsgLogger]
     UserData: []
```

**Comment by EastEriq** [comment]
Right, I forgot to pull, now I get your same output. Still, given the data, it is apparent that there is a bug somewhere, and the entry point is still `imProc.match.mergeCatalogs`, which IMO is still a reason to keep this ticket open rather than opening a new one.

**Comment by EranOfek** [comment]
This bug is not related to mergeCatalogs - the RA/Dec from the previous step are all NaNs...
so open a new issue with the all the functions used to generate the catalogs...

**Comment by EastEriq** [comment]
How can you say that?? What about the plot above?
```
>> AC = AstroCatalog('/raid/enrico/PTF/2ndTake/proc2/2014/02/12/proc/*1514*_011_002*Cat*.fits');
>> size(AC(1).Catalog)

ans =

        1308          53

>> numel(AC(1).Catalog(:,52:53))

ans =

        2616

>> numel(find(isnan(AC(1).Catalog(:,52:53))))

ans =

     0

>> numel((AC(2).Catalog(:,52:53)))           

ans =

        2690
>> numel(find(isnan(AC(2).Catalog(:,52:53))))

ans =

     0
```
Reopening

**Comment by EranOfek** [comment]
The default 'RA' and 'Dec' in the MergedCat columns are derived
               by fitting a proper motion line to all the RA/Dec
               measurments of each source. If there are less then two
               epochs, then these will be NaNs.
               Note that in this case 'Mean_RA' and 'Mean_Dec' can be
               used instead.

So the only option right now is to use this function, for <= then two epochs, is with:
MergedMatchMergedCat=flase

**Comment by EranOfek** [comment]
added comment top help

**Comment by EastEriq** [comment]
>  If there are less then two epochs, then these will be NaNs.

two is not less than two? Why can't a proper motion be fitted with two epochs only?

**Comment by EranOfek** [comment]
This function uses: lcUtil.fitMotion, which have an argument called 'MinNobs', which default is 3.
So by default you need at least 3 epochs in order to fit proper motion.
An alternative is to use 'FitPM'=false.

**Comment by EranOfek** [comment]
you need at least 3 epochs. The reason is that the RA and Dec columns are
based on fitting proper motion which requires
