### ISSUE TITLE
AllSI(1).Key.CAMNUM is not recomended

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#208]
Sasha - 
In pipelines.DemonLAST:
Using the syntax: AllSI(1).Key.CAMNUM is not recomended.
This is meant for manual users.
The recommended way get keyword values in code is to use getKeyVal... which may return NaN if key doesn't exist.

**Comment by EastEriq** [comment]
> which may return NaN if key doesn't exist

ah, oh, #209

**Comment by agioffe** [comment]
OK, I will change the code to getKeyVal, as required.

**Comment by agioffe** [comment]
This way?

K>> AllSI(1).getStructKey('CAMNUM').CAMNUM
ans =
     1
K>> AllSI(1).getStructKey('MOUNT').MOUNT
ans =
   NaN
K>> AllSI(1).getStructKey('NODE').NODE
ans =
   NaN
K>> AllSI(1).getStructKey('NODENUMB').NODENUMB
ans =
     1
K>>

**Comment by EastEriq** [comment]
then it is `AllSI(1).HeaderData.getVal('CAMNUM')`

**Comment by EranOfek** [comment]
no - use:

StKey = AllSI.getStructKey({'CAMNUM','MOUNT','NODE'});

**Comment by agioffe** [comment]
Changed.
