### ISSUE TITLE
`VO.search.search_sortedlat_multi` has an execution time which approximates the age of the universe

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#214]
Uh oh
https://github.com/EranOfek/AstroPack/blob/7d710349c68ee580c100f2cac7ba96b2bd2c2aae/matlab/astro/%2BVO/%2Bsearch/search_sortedlat_multi.m#L49
#156

**Comment by EranOfek** [comment]
Need an example - please specify the exact call and send me the input variables in a mat file (to gmail).

**Comment by EastEriq** [comment]
the issue disappears when forcing `celestial.coo.sphere_dist_fast` to use the matlab implementation

**Comment by EranOfek** [comment]
is it fixed now?

**Comment by EastEriq** [comment]
Only in my local copy. I didn't commit anything

**Comment by EranOfek** [comment]
I think I fixed it - let me know if there is a problem.
thanks,
eran

**Comment by EastEriq** [comment]
another one closed by commit 9ce248d6 solving issue #156
