### ISSUE TITLE
add an `imUtil.art` function to inject synthetic satellite streaks

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#216]
After the glorious ramblings of #188, it would be nice to have a generator of synthetic streaks, for example to unit test `imProc.mask.maskTracks` and `imProc.sources.findTracks`.

To paint pixels along a segment I suggest starting from the ancillary function `pixelline()` which I buried inside `imProc.mask.maskTracks`. I was a little surprised that nothing ready made already exists, but it wasn't a big deal. Also `imUtil.frt.createLine` does it, but generates only full lines across the image, rather than bounded segments.

**Comment by EranOfek** [comment]
Can you add to imUtil.art a new function called createPartialLine
Thanks,
Eran

**Comment by EastEriq** [comment]
I've added the basic function (which is neat). In the following I plan to complete the help header, and want to peruse this function inside `imProc.mask.maskTracks`, as well as to write examples for tracks detection.
