### ISSUE TITLE
ForcedPhtotmetry Error

### ISSUE THREAD

**Issue by hanan-kill** [EranOfek/AstroPack#217]
At ocs@last04e, run matlab from /last04e/data1/archive/LAST.01.04.01/2023/07/05/proc/1 directory, while running imProc.source.ForcedPhoto thrown Exceptions, in two difference ways:

1. if running (as example at https://github.com/EranOfek/AstroPack/wiki/ForcedPhotometry):

input:
    AI = AstroImage('LAST.01.04.01_20230705.205245.660_clear_231+08_001_001_001_sci_proc_Image_1.fits')
    JD = AI.julday
    [Cat]=celestial.SolarSys.jpl_horizons('ObjectInd','2019 LH5','StartJD',floor(min(JD)-1),'StopJD',ceil(min(JD)+1), 'StepSizeUnits','h');
    CatInterp = Cat.interp1('JD',{'RA','Dec','r','Delta'}, JD);
    R=imProc.sources.forcedPhot(AI, 'Coo',CatInterp.Catalog(:,2:3), 'Moving',true);

output:
    Error using AstroTable/colname2ind (line 739)
    Column SN_1 not found
    
    Error in AstroTable/getCol (line 867)
                ColInd = colname2ind(Obj, Columns, []);
    
    Error in imProc.psf.selectPsfStars (line 54)
        SN       = getCol(Cat, {Args.ColSNdelta, Args.ColSN});
    
    Error in imProc.psf.constructPSF (line 63)
            [PsfXY, ~, Flux, Back] = imProc.psf.selectPsfStars(Obj(Iobj).CatData,...
    
    Error in imProc.sources.forcedPhot (line 339)
                    Obj(Iobj) = imProc.psf.constructPSF(Obj(Iobj), 'HalfSize',Args.HalfSizePSF,
                    Args.constructPSFArgs{:});

Looks like the exception throw because at  imProc.psf.constructPSF the object Obj(Iobj).CatData equal to empty AstroCatalog, for some reason.

2. If running (as example at https://github.com/EranOfek/AstroPack/wiki/imProc.sources):

input:
    AI = AstroImage('LAST.01.04.01_20230705.205245.660_clear_231+08_001_001_001_sci_proc_Image_1.fits')
    JD = AI.julday
    [Cat]=celestial.SolarSys.jpl_horizons('ObjectInd','2019 LH5','StartJD',floor(min(JD)-1),'StopJD',ceil(min(JD)+1), 'StepSizeUnits','h');
    Cat.interp1('JD',{'RA','Dec','r','Delta'}, JD);
    R=imProc.sources.forcedPhot(AI, 'Coo',Cat, 'Moving',true);

output:
    Error using sum
    Invalid data type. First argument must be numeric or logical.
    
    Error in mean (line 127)
            y = sum(x, dim, flag) ./ mysize(x,dim);
    
    Error in imProc.sources.forcedPhot (line 222)
            CatH   = catsHTM.cone_search(Args.AddCatName, mean(Args.Coo(:,1))./RAD, mean(Args.Coo(:,2))./RAD,
            Args.AddRefStarsDist, 'OutType','AstroCatalog');

**Comment by EranOfek** [comment]
1. Note that after this single image test you likely want to use pipline.last.forcedPhotAll
2. you have to upload the catalog and not only the image!

AI = AstroImage.readFileNamesObj('LAST.01.04.01_20230705.205245.660_clear_231+08_001_001_001_sci_proc_Image_1.fits');

This command will read not only the image, but also the catalog data and mask image which are needed.
