### ISSUE TITLE
General Pipeline try error

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#225]
A general try error encountered while running the pipeline on various machines (05w,06e,08e). 
The error emerges as D.main uses the function movefile., looks like some files being named with NAN instead of the date (i.e. 27082023_181441.934). The error appeared after successfully processing earlier groups.

last06e :
<img width="1386" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/a8a3bdd2-8f48-4f10-b71d-310f230d2247">

last08e:
<img width="1463" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/521b1198-dcfc-4a02-9a81-2090f01b789e">
Where the full relevant [ERR] lines are :

`[ERR] pipeline.DemonLAST try error: Array indices must be positive integers or logical values. / funname: DemonLAST.main @ line: 1663`

`08:48:53.982 [INF] FileName=/last08e/data1/archive/LAST.01.08.01//2023/08/28/proc/2/LAST.01.08.01_NaN_clear_355+21__001__sci_coadd_Image_1.fits, DataProperty=Image, image is empty - not saved`

`08:48:53.987 [INF] FileName=/last08e/data1/archive/LAST.01.08.01//2023/08/28/proc/2/LAST.01.08.01_NaN_clear_355+21__001__sci_coadd_Mask_1.fits, DataProperty=Mask, image is empty - not saved`

`08:48:53.992 [INF] FileName=/last08e/data1/archive/LAST.01.08.01//2023/08/28/proc/2/LAST.01.08.01_NaN_clear_355+21__001__sci_coadd_Cat_1.fits, DataProperty=Cat, image is empty - not saved
`

`08:48:53.996 [INF] FileName=/last08e/data1/archive/LAST.01.08.01//2023/08/28/proc/2/LAST.01.08.01_NaN_clear_355+21__001__sci_coadd_PSF_1.fits, DataProperty=PSF, image is empty - not saved`

`08:48:54.962 [INF] FileName=/last08e/data1/archive/LAST.01.08.01//2023/08/28/proc/2/LAST.01.08.01_NaN_clear_355+21_000_001_019_sci_merged_Cat_1.fits, DataProperty=CatData, image is empty - not saved`

`08:48:58.316 [INF] FileName=/last08e/data1/archive/LAST.01.08.01//2023/08/28/proc/2/LAST.01.08.01_NaN_clear_355+21_000_001_019_sci_merged_MergedMat_1.hdf5, DataProperty=MergedMat, image is empty - not saved`

While in last05w:
<img width="1009" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/4be56956-9f59-4c58-8c99-2c9f8519c8e4">

Please note:
- LAST 06e is up to date with 'origin/dev1'
- LAST 05w 'git status' is :

<img width="1213" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/9d3d0c35-b842-4a46-9255-4074ef29c944">

- LAST 08e 'git status' is : 
<img width="1213" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/18762694-37fc-44f7-8047-b7617ee0f859">

- Please pay attention that both in 08e&06w the pipeline fails in the same line (1663). Where in last05w it fails in line 1649 besides that, the error appear to be consistent in all machines. I don't have a good explanation for that, especially because the 'changes to commit' in each of the computers are different and should not effect the pipeline work, ( As far as I understand unitTest).

- LAST 08e presented the same error last week as well (see LAST_LOG_210823) but all other machines (02,05,06,10) did not - although using the pipeline.

- We might encounter this error in other machines since the pipeline is running  on 02w, 04e, 10e as well. It didn't fail so far, I will update here on the result of all other machines ( success in processing all groups or getting the same error, or a different one).

**Comment by EranOfek** [comment]
Yarin - please don't mix issues of different kind under the same thread.
Re: git status
do: git stash

Re moveFiles failure:
I moved the error message before the moveFile command so I will get more info.
Please run again on the same data, and send the new log.
Next, run the code again with a break point in line 1756 - when you get there, run this line manually. If its failed then:

save -v7.3 ForEran.mat RawImageList FN_Sci_Groups Igroup FailedPath
and send ForEran.mat to my gmail mail.

**Comment by YarinMS** [comment]
Running again on the same data, after using 'git pull' yield the same log.
![image](https://github.com/EranOfek/AstroPack/assets/118757319/2390ba91-15f7-466b-be51-dd035a8ac576)

ForEran matrix is sent to your gmail (only from last.01.08.01 but I have it for 05w&06e if needed).

**Comment by EranOfek** [comment]
Still no idea - can you please run it with the debug point and call me to your office when it get to the debug point
