### ISSUE TITLE
Limiting magnitude "jumps" over night.

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#226]
While checking  the limiting magnitude of a clear and moon less night of observation, a weird behavior was encountered.

The limiting magnitude for source detection is estimated by fitting the log_10(S/N) vs. the star magnitude and color. And reading the best fit magnitude value at  S/N = 5 and $B_p -R_p=1 \ mag.$ (see Ben Ami  & Ofek 2023)

We know about the relation between the limiting magnitude and the distance from the center of the detector (the base line in each plot). But we also encounter weird jumps.

For clarity, the following images present each subframe location on the detector, in each cell there is the sub frame limiting magnitude Vs time.

- Sorry if the values are too small to read, we really care about the general behavior of each subframe. I find it more effective in revealing the location dependency of the problem.

LAST.01.02.01 :

<img width="697" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/e4af7d2d-12e1-41da-ac0c-c6c5de1a8b46">

LAST.01.06.01 :

<img width="748" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/607d8a82-835e-432d-958e-21b4809ac760">

please pay attention :

- Measurements earlier than 17:30 UTC result in lower limiting magnitude due to the sun altitude ( beginning of observation)
- The results are from different telescopes but from the same night of observation
- You probably noticed that the jumps are antisymmetric around the center of the detector (positive slope in the lower region of the detector in LAST.01.02.01 and negative in the higher region, and the other way around for LAST.01.06.01).
- The observation was taken using Nora's function (ObsByPriority), 4 hrs of 20 s exposures.
- The jumps occur where there is a time difference of ~ 1 min (and not 20 s . Therefore, might happen between visits.)

LAST.01.02.01 sub frame number 1 for reference :
<img width="827" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/42a646ca-7f90-4a1b-b45a-f3603465e8e6">

- The jumps appear in the same night but not at the same time, and there is always a little more than a minute time difference.

LAST.01.06.01 sub frame number 1 for reference :
<img width="766" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/677da846-fbd6-4a1d-91db-d0a562e976cc">

- Take  moment to appreciate the amazing performance of  sub frame 15 in LAST.01.06.01. around all frames.  setting a bar for an ideal (or at least a good ) night.

Eran suspected that the problem might resides in the orientation of the detector, to test this we looked we can find “double stars” in the bad subframes.

- The fields are crowded, But no double star was detected. We looked especially at the frames before and after the jump. and also in the middle of the timeline for comparison.
2 images (before and after) from LAST.01.06.01 for reference :
<img width="596" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/2c05741e-75a4-4aa4-9faf-eb775e4f8899">

And zoomed out:
<img width="638" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/334de2e6-6b88-4665-a36d-7cc7cad696d2">

To make sure this is some general problem, we also looked at LAST.01.10.01 results from the same night, which are similar. Adding sub frame 1 for completeness:
<img width="1111" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/a40ca64f-7b98-49e5-8c17-b68b202dead2">

**Comment by noralinn** [comment]
When moving to a new line in the target list the script checks if the focus should be adjusted (temperature changed by more than 1.6deg), but it also repoints the mount.

To check if it is due to the focus: Check in the headers if the focus values change at the time of these jumps.

To check if it if due to repointing: Look at the X and Y pixel values. It's possible that the source is sometimes closer to the edge of the subimage and this might affect the image quality.

**Comment by YarinMS** [comment]
Thank you, will check and update.

**Comment by EranOfek** [comment]
To summarize - this is due to temperature focus loop and changes in PSF - to deal with this issue one need to detrend the data using positional and color information.
