### ISSUE TITLE
change Basepath default value to [] in pipeline.last.forcedPhotAll ?

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#235]
It seems that the default BasePath and Subdir of forcedPhotAll are set to '/last04e/data1/archive/LAST.01.04.01/2023/03'. 

It would be more convenient if the default was the current directory instead, like for MatchedSources.read_rdir

```
>> pwd

ans =

    '/last04w/data1/archive/LAST.01.04.03/2023/09/06'

>> cd proc/
>> MS=pipeline.last.forcedPhotAll('Coo',[332.6276711,40.893751],'FileTemp','./*/LAST.01.04.03*_333+41_*_009_sci_coadd_Image_1.fits')
Error using cd
Cannot CD to /last04e/data1/archive/LAST.01.04.01/2023/03 (Name is nonexistent or not a directory).

Error in pipeline.last.forcedPhotAll (line 39)
    cd(BasePath);
 
```

**Comment by EranOfek** [comment]
This is a temporary function - I suggest not to touch it at this time until the DB is used.
