### ISSUE TITLE
Suggestion to use time as the folder name for processed data

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#236]
Instead of ...../proc/1 etc. We should name the directory after the time hhmmss, when the observation of the first image started.

Advantages:
1) Moreover, when rerunning the pipeline it won't create an additional directory with a random number. Instead, we can rename hh.mm.ss to hh.mm.ss_v1. This will work as long as the first image is the same.
2) Humans to can find data. 
3) Computers can also find data more easily: e.g. sort by time

**Comment by EranOfek** [comment]
I updated FileNames/nextSubDir accordingly.
It now contains a 'UseTime' option (current default is false).
It will use a SubDir of the format 'HHMMSSv#', where # start with 0 for the first version.

Please test it.
To test it, change the UseTime default to true and run the pipeline.
If it is ok, then send an e-mail to everyone about this change, push the update, and close this issue.
