### ISSUE TITLE
slow code in moment2

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#238]
in imUtil.image.moment2 line 311-312:
``` 
W_Max = ones(size(MatR2), 'like',Image);
W_Max(MatR2>MomRadius2) = 0;
```

Takes a long time.
Try to write a function that

W_Max = FUN(MatR2, MomRadius2, Type)

Where Type is the class of Image (single or double).

Function name:
tools.array.onesCondition

**Comment by elhadan** [comment]
Added func: 
tools.array.onesCondition(MatR2,MomRadius2,Type,UseMex,UseMP)
Works for single/double, 1D/2D/3D arrays (Tell me if the 3D is not needed).
The mex version does work faster than the matlab - added testing to the +array unitTest.m.

**Comment by EranOfek** [comment]
Faster by how much?
test for 1700 by 1700 matrix
And 25 by 25 by 1000 cube

**Comment by elhadan** [comment]
On my machine, ~80% of matlab time for single. ~30% of matlab time for double.
Note that this is true for both the tests you asked for. 
(pushed the test to the unitTest)

**Comment by EranOfek** [comment]
I modified the function and the help.
On linux, for 'single' its about 5 times faster, but for 'double' is a bit slower - why?

**Comment by EranOfek** [comment]
fixed by replacing the zeros function with repmat (considerably faster).
