### ISSUE TITLE
ds9 can't cope with simultaneous requests

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#24]
Simultaneous requests to a single ds9 instance can happen very often now in setups where more than a single matlab tries to display its images at about the same time. For instance, when multiple slaves shoot images in parallel.
Typical errors caused intermittently by `ds9(Image, Frame)` are:
```
Error using ds9.system (line 182)
Command: xpaset -p ds9 frame frameno 4 failed - Answer: XPA$ERROR no 'xpaset'
access points match template: ds9


Error in ds9.frame (line 359)
                    ds9.system('xpaset -p ds9 frame frameno %d',FrameNumber);

Error in ds9.load (line 469)
            Frame = ds9.frame(FrameNumber);

Error in ds9.disp (line 660)
                    ds9.load(List{Iim},Frame(Iim));

Error in ds9 (line 142)
            ds9.disp(Image,varargin{:});
```
as well as
```
Error using ds9.system (line 182)
Command: xpaset -p ds9 colorbar   no failed - Answer: XPA$ERROR no 'xpaset'
access points match template: ds9


Error in ds9.colorbar (line 821)
            ds9.system('xpaset -p ds9 colorbar %s',Mode);

Error in ds9.disp (line 671)
                    ds9.colorbar(Args.Colorbar);

Error in ds9 (line 142)
            ds9.disp(Image,varargin{:});
```
and
```
Error using ds9.system (line 182)
Command: xpaset -p ds9 file /tmp/tp35077435_033f_4fde_9f0c_f51da28103b3.fits
failed - Answer: XPA$ERROR no 'xpaset' access points match template: ds9


Error in ds9.load (line 482)
            ds9.system('xpaset -p ds9 file %s',FitsFile);

Error in ds9.disp (line 660)
                    ds9.load(List{Iim},Frame(Iim));

Error in ds9 (line 142)
            ds9.disp(Image,varargin{:});
```
These are possibly (?) errors of `xpaset`, denouncing that ds9 is not available to digest commands at the moment.
As a solution, I don't know if it is possible to create an individual instance of ds9 for each frame, and to use a syntax of `xpaset` which directs to the right ds9. Alternatively, maybe it is possible to add retries to the failing `xpaset` commands, so that the command has a chance to be honored at a later time, and synchronicity is in fact broken.

**Comment by EranOfek** [comment]
This is xpa limitation and we are currently ignoring this problem

**Comment by EastEriq** [comment]
to be more precise, now LAST has a ds9 listener process which looks for new images in the relevant directories (I don't know myself the mechanics of it, but I'm told it works), and we are not anymore calling xpaset directly with matlab callbacks after images are acquired.
