### ISSUE TITLE
FLAT_IM keyword missing in the header of coadded images

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#241]
The FLAT_IM keyword is there in the header of single image catalogs, but not in the header of coadded images. BIAS_IM is present in both.

```
BIAS_IM = 'LAST.01.02.02_20230419.211314.616_clear_____dark_proc_Image_1.fits'  
FLAT_IM = 'LAST.01.02.02_20230915.161439.612_clear_____twflat_proc_Image_1.fits'
```

**Comment by noralinn** [comment]
This happens for M2, but not M3 or M8. So maybe it's fixed already and Astropack wasn't updated.

**Comment by EranOfek** [comment]
can you try doing git pull in M2e and M2w and check?

**Comment by EranOfek** [comment]
I don't see the problem - possibly this was based on data reduced with old version of the pipeline.
