### ISSUE TITLE
Bug in forcedPhot when not adding GAIA sources

### ISSUE THREAD

**Issue by Nimrod-S** [EranOfek/AstroPack#242]
In the function forcedPhot, if the argument `AddRefStarsDist` gets an invalid value (like NaN) the function is supposed to not look up any additional stars in GAIA and add them to the photometry, but this behavior does not work and causes an error.

The variable `AddColsFromRef` gets the value `false` in this case (which is the expected behavior) and `CatAdd` is an empty array of size 0x2 instead of a list of coordinates from GAIA. But, in line 311, sky2xy is called with `CatAdd` even when the array is empty, which causes an error.

The simplest solution is to wrap the lines 311-313 in `if AddColsFromRef`.

**Comment by EranOfek** [comment]
I added your suggestion to the code - fixed.
