### ISSUE TITLE
`tools.math.stat.wmean` doesn't take into account correctly the `dim` argument

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#247]
```
>> tools.math.stat.wmean(rand(3,5),rand(3,5),1)

ans =

      0.74264

>> tools.math.stat.wmean(rand(3,5),rand(3,5),2)

ans =

      0.84164
      0.25848
      0.30365
      0.20938
      0.65489
      0.51256
      0.66154
      0.33594
      0.76304
      0.49983
      0.78649
      0.39208
      0.24601
      0.15944
      0.57124
```
I'd expect a 1x5 array in the first case and a 3x1 array in the second. Or what is the expected behavior? Do other functions of the package behave consistently?

**Comment by EastEriq** [comment]
the mistake is at lines 43-47:
```
if (IgnoreNaN)
    Flag = ~isnan(Vec) & ~isnan(Err);
    Vec  = Vec(Flag);
    Err  = Err(Flag);
end
```
By default `IgnoreNaN=true`, which flattens the arrays. It should instead be something like (check me)
```
if (IgnoreNaN)
    if Dim==1
        Flag = any(~isnan(Vec),2) & any(~isnan(Err),2);
        Vec  = Vec(Flag,:);
        Err  = Err(Flag,:);
    else
        Flag = any(~isnan(Vec),1) & any(~isnan(Err),1);
        Vec  = Vec(:,Flag);
        Err  = Err(:,Flag);
    end
end
```

**Comment by EastEriq** [comment]
Note however that even with this fix the third output argument has wrong dimension for `Dim=2`

**Comment by EastEriq** [comment]
My fix treats also the third return argument `S`. Please check it and close if ok. Good luck with checking that the resto of the package is consistent with it....

**Comment by EranOfek** [comment]
I modified the function a bit.
