### ISSUE TITLE
Need a function for trapz integration with errors

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#250]
Need a function for trapz integration with errors propagation

**Comment by EranOfek** [comment]
Two new functions are available:
tools.math.integral.trapzErr for trapz integration with error propagation.
Example:
```
x=(1:1:3).'; y=[1 2 3; 1 3 4; 1 4 5]; Err=ones(3,3).*0.1;
[Int,IntErr]=tools.math.integral.trapzErr(x,y,Err)
```

and tools.math.errorProp.times for multiplication with error propagation.
Example:
```
X = rand(4,5); D_X=0.01.*ones(4,5); Y=rand(1,5); D_Y=0.01;
[Val, Err] = tools.math.errorProp.times(X,D_X,Y,D_Y)
```

**Comment by EastEriq** [comment]
trapzErr looks incomplete to me. There is no weighting of the addends, function 1/Err.^2. Compare with wmean, issue #247

**Comment by EastEriq** [comment]
https://github.com/EranOfek/AstroPack/blob/dev1/matlab/util/%2Btools/%2Bmath/%2Bstat/wmean.m

**Comment by EranOfek** [comment]
the purpose of this function is to calculate an integral (sum) and not a
weighted mean.
I suspect this function is what you need - no?

**Comment by EranOfek** [comment]
I thought about it some more.
I think that what you need for the spectrum integration is tools.math.integral.trapzErr and not wmean.
What you care about is the expected integral, and the error in the expectation value of the integral, which is given by a simple error propagation.

Here is an example:
```
[m,e]=tools.math.stat.wmean([100 1; 100 10])

m =

   100


e =

         0.995037190209989

```
As expected, the error on the mean is slightly smaller than 1, but this doesn't make sense for the error on the integral
which should be about 5.5...
