### ISSUE TITLE
Bug in ImageComponent.cutouts

### ISSUE THREAD

**Issue by Nimrod-S** [EranOfek/AstroPack#251]
In line 1710, the function calls `imUtil.cut.mexCutout`. However this function doesn't exist anymore, this call should be changed `imUtil.cut.mex.mex_cutout`. Tried fixing it locally, seems like it works.

**Comment by Nimrod-S** [comment]
Seems like you accidentally changed the function to `cut.mex_cutout` instead of `cut.mex.mex_cutout`! Looking at the commit, seems like all the help sections were changed correctly, it's just the actual function call that is still broken.

**Comment by EranOfek** [comment]
Fixed
