### ISSUE TITLE
`imProc.match.returnMatched_catsHTM` returns more than 10% wrong matches

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#252]
A sample AstroImage `AI` is checked against GAIASpec. The image is too big to attach, it is for now on euler in `/raid/enrico`. The code exhibiting the problem is below.
![image](https://github.com/EranOfek/AstroPack/assets/16066531/5769157f-2568-4364-8aa6-b931f7685933)

```
load("AI.mat")
% match this catalog vs. GAIA (spectral)
[CatOfSpec, ResInd, CatH] = imProc.match.returnMatched_catsHTM(AI,...
                                        'GAIADR3spec','ApplyPM',false);

% sources of the image which are matched with these of GAIA  (227, with these data)
matchind=ResInd.Obj1_IndInObj2(~isnan(ResInd.Obj1_IndInObj2));

% compute the distance in arcsec between matched objects
S1=AI.CatData.Catalog(matchind,end-1:end);
S2=CatOfSpec.Catalog(matchind,1:2)*180/pi; % in degrees
D=celestial.coo.sphere_dist(S1(:,1),S1(:,2),S2(:,1),S2(:,2),'deg')*180*3600/pi;

% note that there are 30 matches more than the nominal 3 arcsec apart:
iwrong=find(D>3);
numel(iwrong)

% the good matches are well near: in average 0.09"
mean(D(D<3))

% but the bad matches may be even more than 1' apart
D(iwrong)

% visual plot in ds9. Sources of the image are yellow squares, sources in
%  GAIA are green circles, matches are highlighted in blue, wrong matches
%  circled in red.
ds9(AI,'zoom','to fit')
ds9.plotc(S1,'bo')
ds9.plotc(S1(iwrong,:),'ro','size',25)
ds9.plotc([CatH.Catalog(:,1),CatH.Catalog(:,2)]*180/pi,'g','Size',20)
ds9.plotc([AI.CatData.Catalog(:,52),AI.CatData.Catalog(:,53)],'ys','Size',20)

% plot lines joining the wrong matches
[X1,Y1]=ds9.coo2xy(S1(iwrong,1),S1(iwrong,2));
[X2,Y2]=ds9.coo2xy(S2(iwrong,1),S2(iwrong,2));
for i=1:numel(iwrong)
    ds9.line_xy([X1(i),X2(i)],[Y1(i),Y2(i)],'r')
end
```

**Comment by EastEriq** [comment]
A fits file containing only the catalog, and not the image, is attached here anyway
[PTF_20170210.044256.247_Ha663_1793__000_001_sci_proc_Cat_1.fits.gz](https://github.com/EranOfek/AstroPack/files/12751478/PTF_20170210.044256.247_Ha663_1793__000_001_sci_proc_Cat_1.fits.gz)

**Comment by EastEriq** [comment]
Got it. It is, guess what, `celestial.coo.sphere_dist_fast` which happens to be called with a mixture of double and single arguments (line 80 of `VO.search.search_sortedlat_multiNearest.m`, called by `imProc.match.matchReturnIndices`, called by `imProc.match.returnMatched_catsHTM`). 
Proof: tracking down to it, point 213 is the point right out the right edge, which is wrongly tagged as a match. This is because `Long` and `Lat` are doubles, but `Cat` is single. The resulting distance is
```
K>> celestial.coo.sphere_dist_fast(Long(213),Lat(213),Cat(177,1), Cat(177,2))

ans =

  single

     0
```
whereas the true distance is
```
K>> celestial.coo.sphere_dist_fast(Long(213),Lat(213),double(Cat(177,1)), double(Cat(177,2)))

ans =

     3.952660817972941e-04

```
which is larger than 1arcsec= 1.45e-5 rad

**Comment by EastEriq** [comment]
setting
```
                Coo1    = double(getLonLat(Cat1, 'rad'));
                Coo2    = double(getLonLat(Cat2, 'rad'));
```
at line 131-132 of `imProc.match.matchReturnIndices.m` (and likewise should be perhaps also at 141-142) solves this issue. Please check if this is the best solution performance wise and for all use cases.

**Comment by EranOfek** [comment]
Also added a comment to the help of celestial.coo.sphere_dist_fast

**Comment by EastEriq** [comment]
> setting
> 
> ```
>                 Coo1    = double(getLonLat(Cat1, 'rad'));
>                 Coo2    = double(getLonLat(Cat2, 'rad'));
> ```
> 
> at line 131-132 of `imProc.match.matchReturnIndices.m` (and likewise should be perhaps also at 141-142) solves this issue. Please check if this is the best solution performance wise and for all use cases.

If you think that this is an acceptable resolution, please commit it. I haven't.

**Comment by EastEriq** [comment]
No objections, so I committed the change mentioned above
