### ISSUE TITLE
truncation errors with `celestial.coo.sphere_dist_fast`

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#253]
Motivated by issue #252.
Examples:
- Imaginary distance
```
celestial.coo.sphere_dist_fast(single(0.2),single(0.4),single(0.2),single(0.4))

ans =

  single

           0 + 0.00048828i
```
- zero output for nonzero distance, >> eps single
```
>> celestial.coo.sphere_dist_fast(0.2,0.4+1e-4,single(0.2),0.4)

ans =

  single

     0
```
- nonzero distance for nearly coincident points:
```
 celestial.coo.sphere_dist_fast(0.2,0.4+1e-19,0.2,0.4)

ans =

   2.1073e-08
```
```
>> celestial.coo.sphere_dist_fast(0.2,0.4,0.2,0.4)

ans =

   2.1073e-08
```

**Comment by EranOfek** [comment]
A known bug - added a real() operation on the output.

**Comment by EastEriq** [comment]
Still not convinced that all cases I reported are "known bugs" and not due to the propagation of truncation errors. I'll reopoen and investigate a little, though maybe they are unavoidable and harmless

**Comment by EastEriq** [comment]
I'm new toit, but for instance this line
https://github.com/EranOfek/AstroPack/blob/9f3daf4662d85c4a68518e87c0e96288344798d0/matlab/astro/%2Bcelestial/%2Bcoo/sphere_dist_fast.m#L70
couldn't be simplified in
```
acos(sin(Dec_1).*sin(Dec_2) + cos(Dec_1).*cos(Dec_2).*cos(RA_1-RA_2))
```
is `sqrt(1-sin^2)` for ensuring positiveness, or why is it "more accurate"?

**Comment by EranOfek** [comment]
I think I did it for speed, but not sure.
eran

**Comment by EastEriq** [comment]
Less operations would be probably faster. But do you think it is worth the fuss of dealing with it? With the risk of breaking existing code building on it, this is a rather core function.
Btw my example #2 is explained by the fact that `cos(single(1e-4))~single(1-1e-4^2)=1`

**Comment by EastEriq** [comment]
And my correction gives the correct result in the other three examples I gave (without mixing singles and doubles), even omitting `real()`. But it is not tested for _any_ angle in the sphere, if there are quadrant issues!

**Comment by EranOfek** [comment]
I have no idew why I wrote it like that - modified the code - is this what you meant?
and it is faster...

**Comment by EastEriq** [comment]
Yes I meant that, but I haven't tested it for any possible case. Is there a unit test?
BTW, you could still factor out one `dRA = RA_1-RA_2` for `nargout=1`, that would make the case `nargout>1` marginally faster.

**Comment by EastEriq** [comment]
It would be good practice if you reference the issue # in the commit messages, and/or the commit SHA in the issue comments

**Comment by EastEriq** [comment]
e.g., https://github.com/EranOfek/AstroPack/commit/318ae28e12bad03360a013d909cda55e7d7cf2aa

**Comment by EastEriq** [comment]
If we are picky, the current version involves 5 sin() - cos() evaluations within `acos()`. The one you commented as haversine formula needs only four, as it would the equivalent one
```
cos(Dec_1-Dec_2) - cos(Dec_1).*cos(Dec_2).*(1-cos(RA_1-RA_2))
```
but I'd be wary of tampering without fully testing.

**Comment by EranOfek** [comment]
tried this in the past, but as far as I remember it was slower...

**Comment by EranOfek** [comment]
can we close this one?
