### ISSUE TITLE
DemonLAST pipeline - populate DB in seperate try catch block

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#254]
The problem:
When running the pipeline and the DB fails, the images can not be moved from new/ to failed/, because they already were moved to raw/

IN order to fix this, we need to move the insert to DB block into another try catch block.

**Comment by agioffe** [comment]
This is done and tested at a local machine on a limited pipeline example (1 obsevation). Now Yarin will run the real pipeline and see whether is causes any unexpected issues (hopefully, won't).
