### ISSUE TITLE
bug with the new `CalcTranslient` flag in properSubtraction

### ISSUE THREAD

**Issue by Nimrod-S** [EranOfek/AstroPack#255]
We added the flag `CalcTranslient` and wrapped some lines in an `if`.

However the line `k = 1` (235) is also inside the condition despite the variable k being used later in non-translient related code (line 245). This means the function always crashes if called with the flag set to false.
The solution is to simply move the line to before the condition. It's probably a good idea to move line 236 out as well, `ExpectedMedian` isn't actually used anywhere but if it is used it's probably relevant outside the translient calculation like `k`.

**Comment by EranOfek** [comment]
Fixed - If false, then S2 and Z2 will not be calculated

**Comment by EranOfek** [comment]
Fixed
