### ISSUE TITLE
Unexpected PSF size calculated by populatePSF

### ISSUE THREAD

**Issue by Nimrod-S** [EranOfek/AstroPack#260]
The default value of the argument `RadiosPSF` is 8, which should give us a 17x17 PSF.

However, when calling the function `imProc.psf.populatePSF`, the image gets a PSF of size 25x25. Unlike calling `imProc.psf.constructPSF` which correctly gives a 17x17 PSF.

I called both functions with an image that should be identical (no PSF in both cases).

Calling constructPSF:

![cpsf](https://github.com/EranOfek/AstroPack/assets/139052408/14d052e1-b18d-4113-85a3-16c432034f52)

Calling populatePSF:

![ppsf](https://github.com/EranOfek/AstroPack/assets/139052408/f27dd68e-2f7c-4bef-9028-064d43f89b99)

**Comment by EranOfek** [comment]
fixed
