### ISSUE TITLE
`convert.length` does not know 'nm'

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#265]
```
>> convert.length('m','cm')

ans =

   100

>> convert.length('um','cm')
Error using convert.length
Unknown length units
 
>> convert.length('nm','cm')
Error using convert.length
Unknown length units
```
I'm surprised anyway that you have to code all this by yourself. There should be standard packages, much better mantained, and capable to resolve any SI prefix. LabVIEW has the capability, I'd have a look on the net as for if there is anything you could leverage on.

**Comment by EranOfek** [comment]
you can use:
https://www.mathworks.com/help/symbolic/unitconvert.html

eran

**Comment by EranOfek** [comment]
added um and nm to convert.length

**Comment by EastEriq** [comment]
That is symbolic, I think better to leave it alone.
There is stuff on Matlabcentral, but either they are too simplistic and better to leave them alone, like

https://www.mathworks.com/matlabcentral/fileexchange/15046-unit-conversion
https://www.mathworks.com/matlabcentral/fileexchange/121587-unit-conversion

or they introduce new classes of number-with-units like

https://www.mathworks.com/matlabcentral/fileexchange/29621-units-conversion-toolbox
https://www.mathworks.com/matlabcentral/fileexchange/38977-physical-units-toolbox

Not sure they provide a plug in replacement for us. And moreover, you need several specific astrophysical units.

**Comment by EastEriq** [comment]
Something wrong here
```
>> convert.length('nm','cm')

ans =

        1e-06

>> convert.length('nm','m')

ans =

        1e-08
```
