### ISSUE TITLE
PSF too sharp on this PTF image

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#266]
(Eran asked for the ticket)
Images are on euler.
Level 1 image is `/raid/enrico/PTF/2ndTake/images/level1/proc/2016/03/27/f12/c2/p5/v2/PTF_201603271521_i_p_scie_t033859_u027339000_f12_p100037_c02.fits`
The script used is `/raid/enrico/PTF/2ndTake/matlab/astrometryProgramFlow.m`
This is the resulting `AI(2).PSFData.surface` and eran says that it looks bad.
![image](https://github.com/EranOfek/AstroPack/assets/16066531/917c7ae5-26fc-4420-8b29-5af674675099)

**Comment by EranOfek** [comment]
I get FWHM
```
AI.PSFData.fwhm
```
of 1.9 pixels which is consistent with the expectation and this specific image.

**Comment by EastEriq** [comment]
wait - you are the one who said that it looks bad

**Comment by EranOfek** [comment]
AT first glace it looks too narrow, but it is actually ok.
