### ISSUE TITLE
searchFieldLAST returns wrong answers for coordinates in degrees

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#267]
The two lower commands return the correct answer, but the upper one gives the wrong field even though the coordinates are the same as in the second command.

```
>> pipeline.DemonLAST.searchFieldLAST([],284.06,8.68)
ans =
        1516
>> pipeline.DemonLAST.searchFieldLAST([],'18:56:15','+08:41:10')
ans =
        1050
>> pipeline.DemonLAST.searchFieldLAST([],'284+09',[])
ans =
        1050
```

**Comment by noralinn** [comment]
For the first line the function assumes that the coordinates are in radian. I modified it, so it now assumes that it's degrees.

Let me know whether this change is ok or causes problems elsewhere.

**Comment by EranOfek** [comment]
1. Verify this is explained in the help
2. run grep -R searchFieldLAST
If this function is used by some other tools - just make sure that your
change doesn't affect the other use cases.
