### ISSUE TITLE
matlab.io.fits.createFile cannot work with relative paths

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#268]
When tuning the unitTest for DemonLAST I found that saving pipeline products fails when the BaseDir variable employed for
`D.setPath(BaseDir);`
contains a relative path (e.g. '~/matlab/data/pipeline/LAST'), but works well if the path is absolute (e.g. '/home/sasha/pipeline/LAST');
I found that the reason is in the **fitsiolib** function internal to **matlab.io.fits.createFile**:

`matlab.io.fits.createFile('~/a.fits')`
Error using fitsiolib
CFITSIO library error (105): couldn't create the named file
Error in matlab.io.fits.createFile (line 34)
fptr = fitsiolib('create_file',filename);

`matlab.io.fits.createFile('/home/sasha/a.fits')`
ans =  uint64
   140380324862112

A dumb fix I found is as follows: instead of just 
`D.setPath(BaseDir);`
I use
`cd(BaseDir); BaseDir = fullfile(pwd);  D.setPath(BaseDir);`

But probably, there is a better solution? @EastEriq @blumzi @EranOfek what do you think?

**Comment by EastEriq** [comment]
Anedoctally I heard from Eran that matlab.io.fits is buggy and incomplete, so there may be no opttion but to transform whichever path into an absolute path.

Searching on the net for "matlab convert relative path to absolute" you find several proposed solutions. I didn't scan too much through them to find what is the best (portable, idempotent, failsafe).

**Comment by EastEriq** [comment]
On linux, this seems to do the job. Note that I'm using matlab's `ls`, not directly the shell `ls` (even though it is probably just a wrapper to it)
```
BaseDir=strtrim(ls('-d',Basedir))
```
Note that the option `-d` is passed, so that it works both for files and for directory names, without listing the content. Optionally, you could try-catch the case of non existing pathname.

**Comment by EranOfek** [comment]
Better to fix the baic FITS write function

**Comment by agioffe** [comment]
Do you mean changing the standard matlab function? Is it legal?

**Comment by EastEriq** [comment]
I think that Eran means to bypass it, replacing with something written anew as part of the `FITS` class. Which itself is quite a mess and ni many places, for the little I have seen, leverages on `matlab.io.fits`, so that I'd have some worries...

**Comment by EranOfek** [comment]
The fix should include two changes
1. A new function tools.os.relPath2absPath
2. Call this fun in FITS.write

Eran

**Comment by agioffe** [comment]
OK, I will try to. One issue is that FITS.write deals with file names, and not directories, so the full trick to do with FN (an input file name in any form, relative or full) would look like:
[Fdir,Fname,Fext]=fileparts(FN);
FullDir=strtrim(ls('-d',Fdir));
FN1 = strcat(FullDir,'/',Fname,Fext);
Is it well enough?

**Comment by agioffe** [comment]
Eventually I have written tools.os.relPath2absPath so that it can deal both with files and directories as input and 
add 1 line to FITS.write:
% sanify the file name so that it contain the absolute path
FileName = tools.os.relPath2absPath(FileName);

**Comment by agioffe** [comment]
Had to add the same sanity string also to FITS.writeTable1 and io.fits.writeSimpleFITS

**Comment by EastEriq** [comment]
wait...
- `relPath2absPath` in the folder case should restore the original pwd, i.e. `curdir=pwd; cd(NameRel); NameAbs = pwd; cd(curdir)`
- add at least a note in the header that this is tested only for linux. For windows, maybe you can take inspiration from toolbox/matlab/general/ls.m, which boils down to use `dir` instead of `ls`. maybe there is a suitable switch (`/b` perhaps?) which does the job

**Comment by agioffe** [comment]
Thank you, Enrico! You are right, I put the return path into the pipeline's unitTest, but forgot to put it into the low-level function.. Now improved. As for the Windows environment, I don't have one to see how it would work, so just put a warning.
