### ISSUE TITLE
A merge of io.files.load1 and io.files.load_check is requested

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#269]
It would be useful to make a merge of **io.files.load1** (now the default object loader in AstroPack) and **io.files.load_check** (that allows to save resources and not load the same object twice). As **io.files.load1** is already hardcoded in may places, it is reasonable to keep this name for the merger.

**Comment by chentishler** [comment]
Please contact Dan directly about any issue with AstroPack.

Thanks,
Chen

**Comment by EranOfek** [comment]
No - we need two seperate functions,
But we do need a deployed version of load_check

**Comment by agioffe** [comment]
What I meant was that we need to add functionality of io.files.load_check to io.files.load1. Do you agree?

**Comment by EranOfek** [comment]
Probably alm you beed is to csll load1 from load check

**Comment by agioffe** [comment]
Yes, it is an obvious variant, though, probably not the finest. Shall I change the io.files.load_check in this way?

**Comment by EranOfek** [comment]
Change and test
Thanks
Eran

**Comment by agioffe** [comment]
Changed, tried several example with debugging. Looks normal, doesn't load the 2nd time when already present. Should we now change all the io.files.load1 for io.files.load_check throughout the code?

**Comment by EranOfek** [comment]
No - load check should be used only by crutical task that requires this
capability

**Comment by agioffe** [comment]
OK, then we may close it.
