### ISSUE TITLE
FileNames.generateFromFileName doesn't produce error when called wrongly

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#270]
The upper command returns wrong results, but doesn't fail or print an error. It would be safer if it does.

The lower command is the correct way to call it.

Is there help/documentation of the FileNames class?

```
>> FN=FileNames.generateFromFileName('LAST.01.01.01_20220826.182338.681_clear_297+41_020_001_021_sci_proc_Image_001.fits')
FN = 
  FileNames with properties:

                   ProjName: {''}
                       Time: []
                     Filter: {'clear'}
                    FieldID: {}
                    Counter: []
                      CCDID: []
                     CropID: []
                       Type: {'sci'}
                      Level: {'raw'}
                    Product: {'Image'}
                    Version: 1
                   FileType: {'fits'}
                   FullPath: '/home/ocs/matlab/AstroPack'
                   BasePath: '/euler1/archive/LAST'
    BasePathIncludeProjName: 1
                BasePathRef: '/euler1/archive/LAST'
                     SubDir: ''
                   TimeZone: 2
                   UserData: []
>> FN=FileNames.generateFromFileName({'LAST.01.01.01_20220826.182338.681_clear_297+41_020_001_021_sci_proc_Image_001.fits'})
FN = 
  FileNames with properties:

                   ProjName: {'LAST.01.01.01'}
                       Time: {'20220826.182338.681'}
                     Filter: {'clear'}
                    FieldID: {'297+41'}
                    Counter: 20
                      CCDID: 1
                     CropID: 21
                       Type: {'sci'}
                      Level: {'proc'}
                    Product: {'Image'}
                    Version: 1
                   FileType: {'fits'}
                   FullPath: '/home/ocs/matlab/AstroPack'
                   BasePath: '/euler1/archive/LAST'
    BasePathIncludeProjName: 1
                BasePathRef: '/euler1/archive/LAST'
                     SubDir: ''
                   TimeZone: 2
                   UserData: []

```

**Comment by EastEriq** [comment]
`help FileNames.generateFromFileName` says it, but not in the most clear way:

             Either a char array or a cell array.
             If the input is a char array, then the function
             will use the io.files.filelist to search for all
             existing files that have this name (wild cards are
             allowed). *In this case the file must exist*.
             If a cell array, then the file name in each element of
             the cell will be used as is. IN this case, the
             file doesn't need to exist.

**Comment by EranOfek** [comment]
1. This is the expected behavior - the reason for this is that in some cases we would like to use this on non-existing files.
2.  Since that for some cases this behavior is unwanted, I added to new arguments to this function:
3.             'CheckExist' - A logical indicating if to check
                               that all the files exist. Only operational when the
                               input is a cell. If some files does not
                               exist then the function will act according
                               to the options in the 'DoNotExist'
                                argument.
                               Default is false.
                        'DoNotExist' - What to do in case a file doesn't
                               exist: 'error'|'warnning'
                               Default is 'error'.
