### ISSUE TITLE
searchFlags, countFlags fix

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#273]
searchFlags, countFlags are two useful functions used to examine the bit mask of sources contained in a Matched sources object. 

While using it myself, I encountered two minor errors that prevent from these functions to run, BASICALLY, just a few typos I had to fix, nothing serious. 
Really nice functions! created by Yehuda.

Example of a typo : [the argument opertaor is being used as operator later on (lines 2036 and 2047)]
<img width="872" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/0d715afe-884e-4c33-a4a3-84763b695804">

I've talked to Yehuda - we agreed that this is probably a typo. The fix is already implemented locally on last03e and will be pushed to Github during the day.

**Comment by EranOfek** [comment]
This is my fault - I changed the function to use function_handle and I
inserted the typo (missing "a")

**Comment by EranOfek** [comment]
Close issue after fixing
