### ISSUE TITLE
'HighRN' , 'FlatHighStd' flags in a MatchedSources object

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#277]
With the motivation to filter bad measurements we would like to consider the "FLAGS" field of a MatchedSources (MS) object.  
This field tells us which bit from the bit mask is on. Relevant flags (By Eran) are : NearEdge, Saturated, NaN and Negative. If one of these flags is on, we should ignore the measurement.

I have encountered different flags, ones that might not be fatal to the measurements but still need some sort of calibration (Again, by Eran), The flags that appear in the 251023 observation while using the forced photometry tool to extract the light curve of a target of interest (J1557+541) are:
`HighRN` and `FlatHighStd`. 

out of 300  data points, 200 of them are holding the flag `HighRN` and 16 data points with the flag `FlatHighStd`. 

The following light curve demonstrate the data points with the  `FlatHighStd` flags in red circles and the `HighRN` flags in black x's . Note that there are 5 points which are probably outliers but with small error bars. I've left them for completeness, their origin is not known to me.
![image](https://github.com/EranOfek/AstroPack/assets/118757319/a0afe281-94c9-418a-a011-c2b8e0346e61)

The images marked by the red circles are from `/last03e/data1/archive/LAST.01.03.01/2023/10/25/proc/15`:

`LAST.01.03.01_20231025.161817.409_clear_238+53_014_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.161857.417_clear_238+53_016_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.161917.431_clear_238+53_017_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.161937.437_clear_238+53_018_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.161957.452_clear_238+53_019_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162017.454_clear_238+53_020_001_009_sci_proc_Image_1.fits
`

and
`/last03e/data1/archive/LAST.01.03.01/2023/10/25/proc/14` :
`LAST.01.03.01_20231025.162037.461_clear_238+53_001_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162057.456_clear_238+53_002_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162117.468_clear_238+53_003_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162137.478_clear_238+53_004_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162157.481_clear_238+53_005_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162217.491_clear_238+53_006_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162237.496_clear_238+53_007_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162257.486_clear_238+53_008_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162317.501_clear_238+53_009_001_009_sci_proc_Image_1.fits
LAST.01.03.01_20231025.162337.499_clear_238+53_010_001_009_sci_proc_Image_1.fits
`

**Comment by EranOfek** [comment]
Is there an action item here?
