### ISSUE TITLE
Non-clear result of Ast/stars photometry - RA/Dec/Mag are looking strange

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#278]
Data is here:
/last04e/data1/archive/LAST.01.04.01/2023/10/25/proc/215506v0

The file: Phot_2021SZ4_M4_20231025.mat includes the argument R which is the output of imProc.sources.forcedPhot
The file: Cat_2021SZ4_M4_20231025.mat includes the ephemerids from JPL/Horizons.

![Screen Shot 2023-11-06 at 11 25 30](https://github.com/EranOfek/AstroPack/assets/45033848/a9b06135-f163-4a8b-a45e-f7f0bf68f768)

See attached snapshot or see *.fig or *.eps files at the given directory.

The RA/Dec of the stars have a very strange pattern (marked in red and green).
The RA/Dec of the asteroid looks ok, but I'm not sure they represent the exact location of the asteroid on the image.
Therefore, the magnitide of the asteroid is looking like noise.

This is how I drew the lightcurve:
figure; hold on; for I=1:1:length(R),plot((R(I).JD-R(1).JD).*24,R(I).Data.MAG_PSF(1,1),'ok');end

This is how I drew the RA/Dec plot:
figure; hold on; for I=1:1:length(R),plot(R(I).Data.RA(1,1),R(I).Data.Dec(1,1),'ok');end         % asteroid
for I=1:1:length(R),plot(R(I).Data.RA(1,2),R(I).Data.Dec(1,2),'sr');end                                    % star
for J=3:1:13, for I=1:1:length(R),plot(R(I).Data.RA(1,J),R(I).Data.Dec(1,J),'sr');end; end      % more stars
for J=14:1:33, for I=1:1:length(R),plot(R(I).Data.RA(1,J),R(I).Data.Dec(1,J),'sg');end; end   % more stars

**Comment by PolishookDavid** [comment]
![Screen Shot 2023-11-06 at 11 38 23](https://github.com/EranOfek/AstroPack/assets/45033848/47426f79-3ba2-495d-8206-ae2b14eb492f)
Graphs with axes labels

**Comment by EranOfek** [comment]
Can't recreate - I suspsect you run the wrong command
