### ISSUE TITLE
Undefined if flags in writeProduct.m

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#279]
line 147 in imProc.io.writeProduct asks for an OR case between three flags.

> if Args.GetHeaderJD || Args.GetHeaderCropID || Args.GetHeaderCounter

GetHeaderJD is true by default so the if condition is true on default as well, GetHeaderCropID and GetHeaderCounter are undefined so the if condition always gives an error if GetHeaderJD is false.

**Comment by EranOfek** [comment]
Bug fix - please test
