### ISSUE TITLE
some GAIADR3spec sources have negative F(lambda) density points

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#280]
Is it a problem in the source data, or is it due to the import?
e.g. for a given AstroImage:
```
>> CatOfSpec = imProc.match.returnMatched_catsHTM(AI,'GAIADR3spec','ApplyPM',false);
>> CatOfSpec.Catalog(475,CatOfSpec.colname2ind({'RA','Dec'}))

ans =

       1.6733     -0.34057

>> CatOfSpec.Catalog(475,CatOfSpec.colname2ind({'F378','F380','F382'}))

ans =

   1.4367e-18  -1.5239e-18   5.3849e-19

```
another one
```
>> CatOfSpec.Catalog(811,CatOfSpec.colname2ind({'RA','Dec'}))

ans =

       1.6705     -0.33892

>> CatOfSpec.Catalog(811,CatOfSpec.colname2ind({'F386','F388','F390'}))

ans =

   2.7602e-18  -9.5528e-19   1.0066e-18
```

**Comment by EranOfek** [comment]
I don't understand - what is the problem?

**Comment by EastEriq** [comment]
That for instance the spectrum for the source at (RA,Dec)=(1.6733,-0.34057)rad has F(380nm)<0

**Comment by EastEriq** [comment]
I am also puzzled by the errors on F(lambda) in the catalog. They vary strangely across the spectrum, and there is an order of magnitude variance of S/N between source and source of similar magnitudes. Maybe they reflect some artifact of how or when they were measured instrumentally. But that is  for another issue.
