### ISSUE TITLE
Can't match specific catalogs due to undefined variables in imProc.match.insertCol_matchIndices

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#288]
Trying to call `imProc.match.match_catsHTM` leads to crash in `imProc.match.insertCol_matchIndices`;

```
>> [MatchedObj, UnMatchedObj, TruelyUnMatched, CatH] = imProc.match.match_catsHTM(New.CatData, 'SDSSDR10')
Unrecognized function or variable 'FlagNN'.

Error in imProc.match.insertCol_matchIndices (line 54)
            DistData     = convert.angular('rad', Args.ColDistUnits, ResInd(Iobj).Obj2_Dist(FlagNN));

Error in imProc.match.match_catsHTM (line 123)
        [Result(Iobj), SelObj] = imProc.match.insertCol_matchIndices(Result(Iobj), ResInd, 'AddColDist',Args.AddColDist,...
```

Looking closer at `imProc.match.insertCol_matchIndices`, there are further undefined variables such as Result at

>   line 55: Result(Iobj) = insertCol(**Result(Iobj)**, ResInd(Iobj).Obj2_Dist, Args.ColDistPos, Args.ColDistName, Args.ColDistUnits);

**Comment by EranOfek** [comment]
Fixed some bugs, but it seems that previous changes broke this function completely.
Working on this.

**Comment by EranOfek** [comment]
Bug fixed - line 65 in insertCol_matchIndices
