### ISSUE TITLE
Pipeline keeps running when the disk is full

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#289]
It keeps running and moves images to the failed directory. I think it would make sense that it stops running when the disk is full or waits.

Maybe it could even stop earlier when the disk is 95% full, such that we could still observe.

**Comment by EranOfek** [comment]
good point!

**Comment by EranOfek** [comment]
pipeline.DEmonLAST.main - add an option 'StopDiskFull' default is [].
If you will set it to 95 then the function will abort if storage is above 95%.
Please test.
