### ISSUE TITLE
Seeing specified in header?

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#292]
Does the header of processed images contain the seeing?

I though it was FWHM, but it has a values of 8000 to 11000.

I looked at:
/2023/09/16/proc/230207v0/LAST.01.04.01_20230916.230227.695_clear_SN2023ijh_002_001_010_sci_proc_Image_1.fits and other images from the same night.

**Comment by noralinn** [comment]
Yes, the values are very large. Therefore, I was confused whether it actually is the seeing or has a different meaning. So it is the seeing, right?

These are the FWHM values for M4T1 2023/09/16 cutout 10. The images are ok (processing worked, image subtraction, forced photometry etc. return reasonable results). Maybe just divide by 3600?


![Screenshot from 2023-12-01 13-33-15](https://github.com/EranOfek/AstroPack/assets/14293969/01199254-66a8-4427-8dba-abd2dead7e22)

**Comment by noralinn** [comment]
Unrelated side note: 
The figure also shows that focusByTemperature messes up the focus.

For the first group of points it is good. The it's adjusted according to the changed temperature and after that it is worse and limiting magnitude degrades. Either the initial focus was bad. Of the adjustment was too large. The shown data was taken at the end of the night, so errors in adjustment accumulate over the night, if the focus look wasn't rerun.

Towards the end of the night the focus improves due to the decreasing temperature, even though the target it setting. (First points were taken at 85deg and last ones at 40 deg).

![Screenshot from 2023-12-01 14-00-25](https://github.com/EranOfek/AstroPack/assets/14293969/5b316058-5ce5-4f8e-be12-2377658a681f)

First drop in limiting magnitude is due to the focus. Later degradation is mostly caused by increasing airmass and increasing sky background at low altitudes.

![Screenshot from 2023-12-01 14-04-00](https://github.com/EranOfek/AstroPack/assets/14293969/34de0e33-ba78-46e1-bf1c-a1e6e3d7b4e1)

**Comment by EranOfek** [comment]
offcourse.

**Comment by EranOfek** [comment]
will be good to checl aslo the FWHM in the coadd image.

**Comment by agioffe** [comment]
I have made the correction in **pipeline.generic.singleRaw2proc** but pushed it only in my personal branch **ak** ,and not yet in **dev1**. Let us train pull requests on Sunday?
In the COADD images it is already fine as in **pipeline.generic.procMergeCoadd** the astrometry is done before the PSF is built.
