### ISSUE TITLE
Larger scatter in pipeline LC's

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#295]
In a meeting presenting comparison between different photometries ( Flux_aper_i , Flux_psf and results from photutils package in pythom), we noticed that in a single visit case the pipeline products are noisier than the photutils product : 

The pipeline products are marked in black and purple (Forced photometry and catalog values respectively)
<img width="793" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/403173df-ea5e-482d-96a1-d451849251f0">
Please note that the blue curve (Manual Phot) uses a 6 pixel aperture and not 3-arcsec like appears in the legend.

The result for the same visit from photutils :
<img width="657" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/8429177d-63fe-453a-9160-50c27edd9474">
Where we ±800 counts is the mean and ~ 120 is the SD. resulting in a scatter of ~ 15 %. Which is 5 % lower than the pipeline products.

Eran suspect that the fact that using fftshift transforms the aperture to be continuous and not pixelated might cause this extra scatter.

The data we used to profuce the LC's is from LAST.01.02.02_20230822 SubFrame #12 :
`ocs@last02e:/last02e/data2/archive/LAST.01.02.02/2023/08/22/proc/232115v0$ ls *012_sci_proc_Image*
LAST.01.02.02_20230822.232115.469_clear_356+34_001_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232135.471_clear_356+34_002_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232155.479_clear_356+34_003_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232215.485_clear_356+34_004_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232235.469_clear_356+34_005_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232255.485_clear_356+34_006_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232315.485_clear_356+34_007_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232335.496_clear_356+34_008_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232355.507_clear_356+34_009_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232415.521_clear_356+34_010_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232435.525_clear_356+34_011_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232455.533_clear_356+34_012_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232515.528_clear_356+34_013_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232535.539_clear_356+34_014_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232555.551_clear_356+34_015_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232615.545_clear_356+34_016_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232635.547_clear_356+34_017_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232655.571_clear_356+34_018_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232715.557_clear_356+34_019_001_012_sci_proc_Image_1.fits
LAST.01.02.02_20230822.232735.579_clear_356+34_020_001_012_sci_proc_Image_1.fits
`

The target coordinates in this field are :
` RA: 356.820145942564
Dec: 34.0324957868111
Mag: 17.828075
 Name: 'WDJ234716.83+340157.33'
`

### ** Update
the following are result from the data set :
`https://astroinstrugroup.slack.com/archives/D03LGALFQ1E/p1701682285860749`

Adding a comparison  between the catalog , forced photometry and photutils results, all in **Flux Aperture 3**,  the annulus size is compared to the size in the LAST-pipeline paper $(R_{in} = 8 \  pix ; R_{out} = 12 \  pix)$
 The "scatter" is quantified by the Standard Deviation over the mean of the signal ($\frac{\sigma}{\bar{flux}}$).
 
 We can look at the "scatter distibution" of ~ 600 Targets. 
<img width="868" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/bf765ebc-12aa-4f1b-bd05-e454b011a9c7">

The targets are taken from the Catalog only if they have 20 measurements ( entire visit).  A frame for reference : 
<img width="458" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/9b2bcc53-8522-4c01-bf03-7ed7ba800205">

We then compute the SD and the mean of a 20 epochs Light Curve for each targets from the different methods - Aper 3 (from the catalog, by applying forced photometry on every target and using photutils with a circular aperture in the right size[ 6 pix])

 We can also think of this "Scatter" as the RMS and plot it against Gaia $B_p$ of our sources : 
<img width="874" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/b4bade49-a70b-4336-8860-03a9acc2e343">

We can also compare the PSF results of the Catalog, Forced Photometry and photutils,
<img width="938" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/372bdebb-d8d4-448d-819a-6ee2955a43bc">
Looking at the " RMS vs MAG " plot :
<img width="941" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/e04ede24-33f7-4c7d-9278-d9a21c72e266">

Its is obvious that the catalog and forced photometry preform better on the bright end, but it is unexpected to have such a difference in the fainter end.
Keep in mind that the psf_model we used in photutils is the simplest offered online and we should probably change it to get better results on the bright end (I assume).

**Comment by EranOfek** [comment]
In imUtil.image.moment2 - around line 430
XX   = M1.X - M1.Xstart + StampCenterX;
YY   = M1.Y - M1.Ystart + StampCenterY;

I suspect this is a bug and should be:
XX = M1.X;
YY = M1.Y;

modified, but need to test/understand this.

Add Poisson error calculation to imUtil.sources.aperPhotCube
Note that this could be faster...

Also recomend to test the pipline when setting the SubPixShift argument in moment2 to 'none'.
It looks like there is a small bias when using the 'fft' option.

Also added some tests to: imUtil.image.unitTest
Next, need to test on real images.

**Comment by EranOfek** [comment]
not yet.

**Comment by EranOfek** [comment]
Latest test shows that the piplein produce results which are very similar (in scatter) to photutils. Both for paper phot and psf phot.

**Comment by YarinMS** [comment]
No Issue with the PSF photometry. a fitted PSF model in photutils preforms the photometry practically the same as the pipeline.

![image](https://github.com/EranOfek/AstroPack/assets/118757319/bb7ce4b8-f513-4d7d-b66e-d9c66e50a4c9)

the difference between the fitted and default psf models is that in the fitted we dont assume a circular 2D gaussian like the default, we fit for an anisotropic 2D gaussian and use it as our psf model.
