### ISSUE TITLE
Error in getPos - returns NaN

### ISSUE THREAD

**Issue by Mariavolkov1** [EranOfek/AstroPack#304]
```
>> IN.getPos('Ear',2451545+100)

ans =

   NaN
   NaN
   NaN
```

**Comment by EranOfek** [comment]
This seems like a matlab version issue (working in 2022a)

**Comment by EranOfek** [comment]
Not related to matlab version.
Likely incorrect installation of INPOP

**Comment by EranOfek** [comment]
Regenerating the mat file by using celestial.INPOP.convertAsci2mat solved the issue.
Not clear why.
Closing.
