### ISSUE TITLE
imUtil.background.modeVar_LogHist yields Inf 

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#308]
**imUtil.background.modeVar_LogHist** yields **Inf** for a 1D vector of 1040 elements only, which does not look peculiar. 
I am attaching a plot and a zip archive of this vector. 
![exB](https://github.com/EranOfek/AstroPack/assets/117931420/6e7e9c29-1118-4144-810b-f068ce15adc9)
[exB.zip](https://github.com/EranOfek/AstroPack/files/13627332/exB.zip)

**Comment by EranOfek** [comment]
imUtil.background.modeVar_LogHist is designed for astronomical images with Poisson noise (i.e., not background subtracted!).

You can change the parameters - e.g.,
```
mUtil.background.modeVar_LogHist(e,'LogNhistFromPeak',6)
ans =
       1.3149
```

or use different function - e.g.,
```
mUtil.background.modeVar_QuantileHist(e)
```

or:
```
imUtil.background.modeVar_QuantileHist(e,false)
```
I added the following comment to the function help:
This function is designed for astronomical images in units of
electrons (i.e., their Poisson properties are still in place) and
that do not have negative values.
