### ISSUE TITLE
Problems with LAST_startup.m

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#31]
1. It does not add to path the LAST directories. In fact I don't understand why this line https://github.com/EranOfek/AstroPack/blob/853982a5df68572bd9fe631ca28a60c084467fbc/matlab/startup/startup_LAST.m#L22 is commented out
2. it is too verbose, as if there was a missing `;`
3. it leaves matlab in `/home/ocs/matlab/AstroPack/matlab/startup`
4. philosophically, it is dirty that Astropack has to know the whereabouts of LAST packages which are not among its dependencies. But the whole idea of what is Astropack (missing manifesto), what functionality it brings and what are its interdependencies is missing, I already remarked

```
ans =

    '/home/ocs/matlab/LAST/.'


ans =

    '/home/ocs/matlab/LAST/..'


ans =

    '/home/ocs/matlab/LAST/LAST_AtikCamera'


ans =

    '/home/ocs/matlab/LAST/LAST_CelestronFocusMotor'


ans =

    '/home/ocs/matlab/LAST/LAST_EnclosureControl'


ans =

    '/home/ocs/matlab/LAST/LAST_EnvironmentArduinoSensors'


ans =

    '/home/ocs/matlab/LAST/LAST_Handle'


ans =

    '/home/ocs/matlab/LAST/LAST_Messaging'


ans =

    '/home/ocs/matlab/LAST/LAST_MountArduinoSensors'


ans =

    '/home/ocs/matlab/LAST/LAST_OCS'


ans =

    '/home/ocs/matlab/LAST/LAST_QHYccd'


ans =

    '/home/ocs/matlab/LAST/LAST_USBserial'


ans =

    '/home/ocs/matlab/LAST/LAST_XerxesMount'


ans =

    '/home/ocs/matlab/LAST/LAST_ZWOASICamera'


ans =

    '/home/ocs/matlab/LAST/LAST_config'


ans =

    '/home/ocs/matlab/LAST/LAST_iOptronCEM120'


ans =

    '/home/ocs/matlab/LAST/LAST_tinycontrolIPpowerSocket'

AstroPack startup addpath count: 0
AstroPack startup done: /home/ocs/matlab/AstroPack/matlab/startup/startup
>> pwd

ans =

    '/home/ocs/matlab/AstroPack/matlab/startup'
```

**Comment by EranOfek** [comment]
~/matlab/AstroPack/matlab/startup.startup.m file is the AstroPack startup file and not the LAST startup file.
The LAST startup file is located in ~/matlab/startup and it adds all the LAST directories and calls the AStroPack startup

**Comment by EastEriq** [comment]
Apparently the issue has been tackled months ago, both by Astropack and by last-tool
