### ISSUE TITLE
FileNames/validateType failed

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#315]
```
D.main('StopWhenDone',true,'StartJD',[14 12 2023],'EndJD',[16 12 2023])
Error using error
Function is not defined for 'cell' inputs.

Error in FileNames/validateType (line 397)
                    error('Illegal value found in Type property (element %d): %s',II, Obj.Type);

Error in FileNames/set.Type (line 147)
            Obj.validateType;

Error in FileNames.generateFromFileName (line 356)
                Obj.Type{Ilist}     = SplitName{8};

Error in pipeline.DemonLAST/main (line 1686)
                FN_Foc   = FileNames.generateFromFileName(Args.TempRawFocus);
 ```

**Comment by EranOfek** [comment]
This happens because the input filename was not valid.
Specifically, the object name contained "_" which was interpreted by the FileNames class a seperator.
Solutions:
1. avoid using "_" in object names.
2. Added a check for the number of seperators in code:

```
if numel(SplitName)~=11
     error('Illigal file name - number of underline-seperators in file name %s is not 11',List{Ilist});
end
```

**Comment by EastEriq** [comment]
>      error('Illigal file name - number of underline-seperators in file name %s is not 11',List{Ilist});

Illegal!!

**Comment by EastEriq** [comment]
which file is this in? Which commit did solve this issue? Always reference it in the commit message!

**Comment by EranOfek** [comment]
commit dev1 fb80e7cc

**Comment by EastEriq** [comment]
It would appear automatically if in the commit message you would mention issue #315
