### ISSUE TITLE
pipeline: failed on last02e at prepMasterFlat

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#317]
>> D.prepMasterFlat
Error using cell/unique (line 85)
Cell array input must be a cell array of character vectors.

Error in CalibImages/createFlat (line 889)
            UniqueFilters = unique(FilterList);

Error in pipeline.DemonLAST/prepMasterFlat (line 1513)
                        CI.createFlat(AI, 'FlatArgs',Args.FlatArgs,
                        'Convert2single',true);

**Comment by EranOfek** [comment]
Executed on flat images taken in 2022 with incomplete header.
Images deleted - Ignoring bug.
