### ISSUE TITLE
pipeline: failed on last03w

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#320]
>> D.main('StopWhenDone',true,'StartJD',[14 12 2023],'EndJD',[16 12 2023])
Error using error
Function is not defined for 'cell' inputs.

Error in FileNames/validateType (line 397)
                    error('Illegal value found in Type
                    property (element %d): %s',II,
                    Obj.Type);

Error in FileNames/set.Type (line 147)
            Obj.validateType;

Error in FileNames.generateFromFileName (line 356)
                Obj.Type{Ilist}     = SplitName{8};

Error in pipeline.DemonLAST/main (line 1686)
                FN_Foc   =
                FileNames.generateFromFileName(Args.TempRawFocus); 
>>

**Comment by EranOfek** [comment]
Same problem as issue #315 (Object name containing underline).
I rename the files on this computer.
