### ISSUE TITLE
pipeline: failed on last06e, prepMasterDark

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#321]
>> D.prepMasterDark
Index exceeds the number of array elements (0).

Error in AstroImage/astroImage2ImageComponent (line 1072)
                    OutClass = str2func(class(Obj(1).(Args.DataProp{Iout})));

Error in imProc.image.images2cube (line 50)
    [Out{1:nargout}] = astroImage2ImageComponent(Obj, 'CreateNewObj',false,...

Error in imProc.stack.coadd (line 183)
    [ImageCube, BackCube, VarCube, MaskCube] = imProc.image.images2cube(ImObj,
    'CCDSEC',Args.CCDSEC, 'DimIndex',IndexDim, 'DataProp',DataProp,
    'DataPropIn',Args.DataPropIn, 'Cube',Args.Cube);

Error in imProc.dark.bias (line 150)
    [Result, CoaddN, ImageCube] = imProc.stack.coadd(ImObj(IsBias), 'CCDSEC',[],...

Error in CalibImages/createBias (line 714)
            [BiasImage, ~, ~] = imProc.dark.bias(ImObj, Args.BiasArgs{:});

Error in pipeline.DemonLAST/prepMasterDark (line 1298)
                        CI.createBias(DarkList, 'BiasArgs',Args.BiasArgs,
                        'Convert2single',true);
 
>>

**Comment by EranOfek** [comment]
Can not redproduce - works for me.
Next time please provide full information.
What is the content of D properties...
