### ISSUE TITLE
Test and changes of pipeline.last.pointingModel

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#322]
This is to keep track of issues and changes. I'm still working on it and will test whether it works now at the next occasion.

The new version is currently only used on M8, the other mounts still use the previous pointing model that did not take into account that the telescopes are not coaligned and that the offsets in the camera config files are not precise.

File at: ocs@last08e:~/Desktop/nora/pointingModel_plots.m will check it in to GitHub once I figure out how or once it's tested.

* in PM (written to the pointing model file) the first two columns were set to Dec, instead of HA and Dec - this explains why my tests during Yahel's last visit did not succeed
* now using celestial.coo.sphere_dist to calculate distances on sphere
```
        % HA diff - Mount - Astrometry
        [Dists, Angles] = celestial.coo.sphere_dist( ...
            AllResult(Idirs).Result.M_JRA, AllResult(Idirs).Result.M_JDEC,...
            AllResult(Idirs).Result.CenterRA, ...
            AllResult(Idirs).Result.CenterDec, 'deg');
           
        DiffHA_Mnt_Ast(:,Idirs) = Dists.*sin(Angles)*RAD;
        DiffDec_Mnt_Ast(:,Idirs) = Dists.*cos(Angles)*RAD;

```
* current script writes DiffHA and DiffDec directly to file instead of interpolating over them - change later is necessary
* removed lots of unnecessary code to simplify script
* plotting lots of things for debugging/inspection

Resulting pointing model for M8:
![PM_offsets_HA](https://github.com/EranOfek/AstroPack/assets/14293969/ec43eda3-a2fc-49d9-8191-3e71aed5d0da)

![PM_offsets_Dec](https://github.com/EranOfek/AstroPack/assets/14293969/6a4a804e-e554-4ad9-bce2-d0c8731292a6)

Blue from header of unprocessed images
Red astrometry
Results for the center of all 4 CCDs and the mount/mean coordinate in the center
![PM](https://github.com/EranOfek/AstroPack/assets/14293969/f21e4662-2c6c-41c2-b748-246a235e1e40)

Plans for next observing night:
* recalculate pointing model for M8
* use testing script: ocs@last08e:~/Desktop/nora/getPointingModelTestData.m to verify it's working
* * test script creates grid or RADec, selects observable positions, takes image, solves astrometry, and compares it to pointing

**Comment by EranOfek** [comment]
new versions pointingModel_Solve
and 
pointingModel_Write
