### ISSUE TITLE
Pipeline uses the latest MasterFlat exist But we want it to use the MasterFlat which is closer to the observation date.

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#326]
When loading calib before using the pipeline. the default is to use the latest master flat.
we can prepMasterFlat near JD and also ask it to use it by loadcalib('nearJD' ,xxxxx).
If this was automatic we would prevent human errors. Instead of a human asking for a specific MasterFlat we can just force the prepMasterFlat and loadcalib functions to use the MasterFlat which is taken in the night of observation - if exist, or the next best thing, to use Flats taken in the a date which is the closest to the date of the observation we are trying to process.

**Comment by EranOfek** [comment]
pipelie.DemonLAST/main modified to reload calibration images taken near observations time.
