### ISSUE TITLE
PSF estimation error due to non-existend method call in imProc.psf.selectPsfStars

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#328]
Trying to construct a PSF for any image using imProc.psf.constructPSF fails. imProc.psf.selectPsfStars calls the method imUtil.background.mode (line 61), which does not exist. 

```
> AI = imProc.psf.constructPSF(AI)
Unable to resolve the name 'imUtil.background.mode'.

Error in imProc.psf.selectPsfStars (line 61)
    MedSigma = imUtil.background.mode(Sigma(FlagSN));

Error in imProc.psf.constructPSF (line 63)
        [PsfXY, ~, Flux, Back] = imProc.psf.selectPsfStars(Obj(Iobj).CatData,...
```

**Comment by EranOfek** [comment]
bug corrected by switching from mode to modeVar_LogHist.
However, from now on you should use:
imProc.psf.populatePSF
