### ISSUE TITLE
re:  moonlight.m

### ISSUE THREAD

**Issue by RTOMalley** [EranOfek/AstroPack#329]
(1) It looks like moonlight.m has a 90 degree phase shift in the output (tested for December 2023).  At line 54 (after 'Handle Elongation' comment) the original code calculates "f = 180 - Elon(J).*RAD;"  ... leading to a maximum illumination for Dec 5 (elongation = 270) not Dec 27 (elongation = 180).  Changing 180 to 90 gives the relative outputs one would expect for the different phases of the moon.

(2)  Can you point me to the original article this function is based on?  I suspect the horizontal plane is at the top of the atmosphere, but that's just a guess.  Original papers help me in understanding the basis for the code.  Thx

**Comment by EranOfek** [comment]
In: celestial.SolarSys.moonlight the elongation must be between 0 to 180 deg (this is how elongation is defined).
I updated the help of the function, and also its ability to handle a mix of scalar/vector inputs.

Usage example:
```
JD=2451545+(0:1:30)';
[RAS,DecS]=celestial.SolarSys.suncoo(JD);      
[RAM,DecM,HP]=celestial.SolarSys.mooncool(JD,NaN);
Elon=celestial.coo.sphere_dist_fast(RAM,DecM, RAS, DecS);
Illum=celestial.SolarSys.moonlight(pi./2, HP, Elon);     
```

**Comment by RTOMalley** [comment]
Most appreciated, and apologies for my error.
