### ISSUE TITLE
prepMasterFlat  master flats Only if pwd is the ~/new directory

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#331]
This issue encountered while processing data on last01e.
First, reducing the data from LAST.01.01.01 went well, the pipeline automatically used MasterFlat from the observation date (14/12/23)

Second, reducing the data from LAST.01.01.02 did not go as planned, since the MasterFlats used is from 26/06/23.

First I made sure that im on the right directory :
![image](https://github.com/EranOfek/AstroPack/assets/118757319/6d4a9cd5-3246-40f2-b5a2-3e2694410269)
Then, naively trying to loadCalib('FlatNearJD') to find out there is no MasterFlat from this date., and indeed 26/06/23 is the oldest master flat we have in `/last01e/data2/archive/LAST.01.01.02/calib`

Next, we try to prepMasterFlat() - expecting from the function to create MasterFlats from the flats taken in the observation date ( and for others as well):
![image](https://github.com/EranOfek/AstroPack/assets/118757319/8373ef83-fc64-47ab-9fa5-a4d4a12c1ec1)

Following this step we tried to provide prepMasterFlats('FilesList',FN) with the path to the twflat images from the observation date :
![image](https://github.com/EranOfek/AstroPack/assets/118757319/f9cee318-3936-455c-b643-26267b27db70)

But we got the same result :
![image](https://github.com/EranOfek/AstroPack/assets/118757319/6595029d-a46d-45ff-9f36-1c10c1a24e70)

To prepMasterFlat I actually had to manually `cd /last01e/data2/archive/LAST.01.01.02/new` and then execute the function `D.prepMasterFlat`, which created the latest Master Flats from single twflat fits files in the `new` directory and stored them in the `calib` directory.

**Comment by EranOfek** [comment]
Fixed
Moving to new prior to execution.
