### ISSUE TITLE
pipeline.DemonLAST.main error

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#334]
While trying to rum the pipeline on data collected in 25/12/23 in last01e the following syntax error was encountered:
![image](https://github.com/EranOfek/AstroPack/assets/118757319/17d1db1a-3dcc-4242-bf23-6d798351fa35)

looking at celestial.OrbitalEl() in Line :1640 we find:
![image](https://github.com/EranOfek/AstroPack/assets/118757319/baa2c123-3c20-424b-abcd-506852aa2375)

(Looks like a syntax error)

**Comment by EastEriq** [comment]
the second is not a syntax error

**Comment by YarinMS** [comment]
After fixing the syntax error, different error encountered : 
<img width="660" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/ac20cfdc-66fe-4f70-bf25-435b17d32aaf">

We need to ask from Arie to install `MergedEpoch_2460200.mat` on all computers.
pipeline.demonLAST.main() can work on computers without the given file with the argument "SelectKnownAsteroids" as false
