### ISSUE TITLE
MergedEpoch_2460200.mat is missing in last01e.

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#335]
While trying to use pipeline.DemonLAST.main() in last01e the following error encountered : 

<img width="660" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/c59adae6-d931-4777-98f0-9dd823c6b539">

We need to ask from Arie to install `MergedEpoch_2460200.mat` on all computers (if it does not exist already).
pipeline.demonLAST.main() can work on computers without the given file with the argument "SelectKnownAsteroids" as false

**Comment by EranOfek** [comment]
Sasha added MinorPlanetsCT/ to the installer.
Next, need to install it via last-tool.

**Comment by agioffe** [comment]
I have installed it at all the LAST machines which are up (i.e., all except last01w, last04w and last08w which are down by now).
