### ISSUE TITLE
convert.angular (called by AstroWCS.interm2native) error while running pipeline

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#336]
08:31:32.637 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  494.5
08:31:32.658 [INF] pipline.DemonLAST executing pipeline for group 33 - First image: /last10e/data1/archive/LAST.01.10.01/new/LAST.01.10.01_20231225.212146.404_clear_054+13_041_001_001_sci_raw_Image_1.fits
08:31:32.665 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  494.5
08:31:47.706 [INF] multiRaw2procCoadd: image 1 of 20 processed: LAST.01.10.01_20231225.212146.404_clear_054+13_041_001_001_sci_raw_&'
08:31:58.704 [INF] multiRaw2procCoadd: image 2 of 20 processed: LAST.01.10.01_20231225.212206.418_clear_054+13_042_001_001_sci_raw_&'
08:32:08.050 [INF] multiRaw2procCoadd: image 3 of 20 processed: LAST.01.10.01_20231225.212226.429_clear_054+13_043_001_001_sci_raw_&'
08:32:17.157 [INF] multiRaw2procCoadd: image 4 of 20 processed: LAST.01.10.01_20231225.212246.438_clear_054+13_044_001_001_sci_raw_&'
08:32:26.421 [INF] multiRaw2procCoadd: image 5 of 20 processed: LAST.01.10.01_20231225.212306.442_clear_054+13_045_001_001_sci_raw_&'
08:32:35.547 [INF] multiRaw2procCoadd: image 6 of 20 processed: LAST.01.10.01_20231225.212326.444_clear_054+13_046_001_001_sci_raw_&'
08:32:44.819 [INF] multiRaw2procCoadd: image 7 of 20 processed: LAST.01.10.01_20231225.212346.444_clear_054+13_047_001_001_sci_raw_&'
08:32:54.285 [INF] multiRaw2procCoadd: image 8 of 20 processed: LAST.01.10.01_20231225.212406.456_clear_054+13_048_001_001_sci_raw_&'
08:33:03.707 [INF] multiRaw2procCoadd: image 9 of 20 processed: LAST.01.10.01_20231225.212426.459_clear_054+13_049_001_001_sci_raw_&'
08:33:12.939 [INF] multiRaw2procCoadd: image 10 of 20 processed: LAST.01.10.01_20231225.212446.475_clear_054+13_050_001_001_sci_raw_&'
08:33:22.550 [INF] multiRaw2procCoadd: image 11 of 20 processed: LAST.01.10.01_20231225.212506.477_clear_054+13_051_001_001_sci_raw_&'
08:33:31.868 [INF] multiRaw2procCoadd: image 12 of 20 processed: LAST.01.10.01_20231225.212526.475_clear_054+13_052_001_001_sci_raw_&'
08:33:41.446 [INF] multiRaw2procCoadd: image 13 of 20 processed: LAST.01.10.01_20231225.212546.486_clear_054+13_053_001_001_sci_raw_&'
08:33:51.136 [INF] multiRaw2procCoadd: image 14 of 20 processed: LAST.01.10.01_20231225.212606.500_clear_054+13_054_001_001_sci_raw_&'
08:34:00.914 [INF] multiRaw2procCoadd: image 15 of 20 processed: LAST.01.10.01_20231225.212626.500_clear_054+13_055_001_001_sci_raw_&'
08:34:10.197 [INF] multiRaw2procCoadd: image 16 of 20 processed: LAST.01.10.01_20231225.212646.500_clear_054+13_056_001_001_sci_raw_&'
08:34:20.082 [INF] multiRaw2procCoadd: image 17 of 20 processed: LAST.01.10.01_20231225.212706.516_clear_054+13_057_001_001_sci_raw_&'
08:34:29.249 [INF] multiRaw2procCoadd: image 18 of 20 processed: LAST.01.10.01_20231225.212726.521_clear_054+13_058_001_001_sci_raw_&'
08:34:38.615 [INF] multiRaw2procCoadd: image 19 of 20 processed: LAST.01.10.01_20231225.212746.523_clear_054+13_059_001_001_sci_raw_&'
08:34:48.126 [INF] multiRaw2procCoadd: image 20 of 20 processed: LAST.01.10.01_20231225.212806.522_clear_054+13_060_001_001_sci_raw_&'
08:34:48.168 [INF] multiRaw2procCoadd: started coadding the sub images
08:34:58.249 [INF] procMergeCoadd: coadding field 1
08:34:58.258 [INF] procMergeCoadd: coadding field 2
08:35:00.759 [INF] procMergeCoadd: coadding field 3
08:35:03.286 [INF] procMergeCoadd: coadding field 4
08:35:05.799 [INF] procMergeCoadd: coadding field 5
08:35:08.289 [INF] procMergeCoadd: coadding field 6
08:35:10.827 [INF] procMergeCoadd: coadding field 7
08:35:13.340 [INF] procMergeCoadd: coadding field 8
08:35:15.837 [INF] procMergeCoadd: coadding field 9
08:35:18.402 [INF] procMergeCoadd: coadding field 10
08:35:20.961 [INF] procMergeCoadd: coadding field 11
08:35:23.488 [INF] procMergeCoadd: coadding field 12
08:35:26.006 [INF] procMergeCoadd: coadding field 13
08:35:28.502 [INF] procMergeCoadd: coadding field 14
08:35:31.030 [INF] procMergeCoadd: coadding field 15
08:35:33.549 [INF] procMergeCoadd: coadding field 16
08:35:36.046 [INF] procMergeCoadd: coadding field 17
08:35:38.570 [INF] procMergeCoadd: coadding field 18
08:35:41.114 [INF] procMergeCoadd: coadding field 19
08:35:43.607 [INF] procMergeCoadd: coadding field 20
08:35:46.186 [INF] procMergeCoadd: coadding field 21
08:35:48.729 [INF] procMergeCoadd: coadding field 22
08:35:51.244 [INF] procMergeCoadd: coadding field 23
08:35:53.769 [INF] procMergeCoadd: coadding field 24
[08:36:02.370] [ERR] pipeline.DemonLAST try error: Unknown input angular units / funname: convert.angular @ line: 261
[08:36:02.386] [ERR] Exception: id= msg=Unknown input angular units
[08:36:02.398] [ERR] stack: Ind=1; FunName=convert.angular; line=261
[08:36:02.407] [ERR] stack: Ind=2; FunName=AstroWCS.interm2native; line=780
[08:36:02.417] [ERR] stack: Ind=3; FunName=AstroWCS.xy2sky; line=668
[08:36:02.425] [ERR] stack: Ind=4; FunName=AstroWCS.cooImage; line=1199
[08:36:02.432] [ERR] stack: Ind=5; FunName=AstroImage.cooImage; line=1748
[08:36:02.443] [ERR] stack: Ind=6; FunName=getCooCenter; line=62
[08:36:02.451] [ERR] stack: Ind=7; FunName=match2solarSystem; line=211
[08:36:02.459] [ERR] stack: Ind=8; FunName=procMergeCoadd; line=326
[08:36:02.467] [ERR] stack: Ind=9; FunName=multiRaw2procCoadd; line=497
[08:36:02.478] [ERR] stack: Ind=10; FunName=DemonLAST.main; line=1924
[08:36:02.486] [ERR] pipeline.DemonLAST: 20 images moved to failed directory
08:36:05.540 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd analyzed 20 images starting at 20231225.212146.404

**Comment by agioffe** [comment]
I tried to reproduce the error, made a group of 20 images starting with the same one
/last10e/data1/archive/LAST.01.10.01/new/LAST.01.10.01_20231225.212146.404_clear_054+13_041_001_001_sci_raw_Image_1.fits
but the processing went to the end without errors.
Hence, I'd suggest to close the issue by now and reopen it if the same error comes up agian.
