### ISSUE TITLE
Found an image with an invalid time in the filename

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#339]
ocs@last01e:/last01e/data1/archive/LAST.01.01.01/new/LAST.01.01.01_20220928.005960.000_clear_054-32_027_001_001_sci_raw_Image_1.fits causes problems because the datetime 20220928.005960.000 is invalid. It should be 20220928.010000.000 instead.

The file is quite old, so not sure whether the bug still exists.

**Comment by EastEriq** [comment]
The code setting the time stamp of the filename is in LAST_OCS/+obs/@unitCS/private/constructFilename.m, using IP.Time.  As for constructFilename.m, its latest change was on 20/3/2022. I think that it is unlikely that if there was a bug, we haven't become aware either earlier than later than that date. Rather, I would think that the clock of the computer might have been wrong, or whatever.

In what sense "datetime 20220928.005960.000 is invalid. It should be 20220928.010000.000 instead"? The correct date is written in the FITS header, in contrast with the file name?

Also, what is "causes problems"? Perhaps the message here is that the pipeline should trap such invalid cases and flag them?

**Comment by EranOfek** [comment]
this is a known feature of celestial.coo.convertdms.
The probability it will happen is about 1./(60*1000*2)...
Note that this should not effect anything besides readability...

**Comment by EastEriq** [comment]
Ah yes, 00:59:60, I didn't pay attention.

**Comment by EranOfek** [comment]
I am closing - if there is an effect on science please reopen.
