### ISSUE TITLE
Rechecking how much the focus changes with temperature - value used in focusByTemperature

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#340]
Not a bug, but a report. Posted here, so it doesn't get lost.

A while ago I noticed that focusing by temperature doesn't always work.

Here's the evolution of the seeing (remember there was a bug the FWHM should be divided by 3600 https://github.com/EranOfek/AstroPack/issues/292) with time for M4T1 from 20230916. I've seen the same in a different night I looked at. So the seeing was ok at first, but then the focuser moved by ~30 ticks after the first 100 images and it got much worse. The limiting magnitude degraded by about 0.5mag. 

![287257908-5b316058-5ce5-4f8e-be12-2377658a681f](https://github.com/EranOfek/AstroPack/assets/14293969/bae111d7-a922-4a30-9f88-504de2693901)

Based on past measurements, focusByTemp moves the focuser by 19 ticks per degree, but it only moves if the difference is >30 ticks, so if the temperature has changed by >1.6 deg.

I was suspecting that we are overadjusting and that 19 ticks/deg might be too much. Therefore I reran the focus loop many times and the results for 6 telescopes are below:

![focus_vs_ticks_M8C4](https://github.com/EranOfek/AstroPack/assets/14293969/a0c052cb-0105-4db5-8b94-81b9d120e996)
![focus_vs_ticks_M8C3](https://github.com/EranOfek/AstroPack/assets/14293969/f40a2d37-ce7b-435e-a5e5-d80f16a52770)
![focus_vs_ticks_M8C2](https://github.com/EranOfek/AstroPack/assets/14293969/881c3ba9-706f-49bf-932d-67c12ce20a1b)
![focus_vs_ticks_M8C1](https://github.com/EranOfek/AstroPack/assets/14293969/8e1cb05d-dde6-4f60-b407-8ecceab5689d)
![focus_vs_ticks_M4C2](https://github.com/EranOfek/AstroPack/assets/14293969/f7d5e7df-d098-4d7c-870b-914150786a24)
![focus_vs_ticks_M4C1](https://github.com/EranOfek/AstroPack/assets/14293969/8c217401-236f-43cc-8a7f-a726c7ec3285)

It seems that 19 ticks/deg (black line) is more or less ok, but the scatter of the dots is relatively large. It always reported that the focus was found, but there are some outliers. Also, the temperature only changed by 6 degrees. In summer we have temperature changes of up to 15 deg.

Any suggestions how to make sure the focus is good throughout the night?
Maybe just rerun the focus loop once in the middle of the night?
Or as soon as the temperature has changed by ~3deg?
Get more data points in the plots above?

**Comment by noralinn** [comment]
Eran suggests to measure the focus for different regions of the image to make sure that it is good on average and not only optimized for the center.

This can be done using existing focus loop images.

**Comment by EranOfek** [comment]
Thanks - closing.
