### ISSUE TITLE
DS9analysis.m: blinkAstCrop - try to access wrong non-exisitng parameter

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#345]
File DS9analysis.m
Method blinkAstCrop
Line 362

The code tries to read JD_PM from the SecetedCatPM table, but such value is not in the table.
It appear at AstCrop.SelectedCatPM level, and NOT in its table.

David

**Comment by PolishookDavid** [comment]
% To reproduce:
ssh last10e
cdcam1
cd 2023/12/14/proc
% in matlab
load 172023v0/LAST.01.10.01_20231214.172013.438_clear_074+55_001_001_001_sci_merged_Asteroids_1.mat
D9.blinkAstCrop(Obj,'Id',1)

**Comment by PolishookDavid** [comment]
% present in ds9 images from last.01.10.01/2023/12/14/proc/*/
cd     '/home/polishoo/Images/LAST/LAST.01.10.03/2023/12/14/proc/004009v0'
load('LAST.01.10.03_20231215.003959.614_clear_074+55_481_001_001_sci_merged_Asteroids_1.mat')
D9.blinkAstCrop(Obj,'Id',8)
% Run the plotKnownAst code
D9.plotKnownAst('OrbEl', OrbEl, 'INPOP', IN, 'MagLimit',20)

**Comment by EranOfek** [comment]
In the new version of the pipeline the JD is included in the AstroTable.
The solution is to rerun the pipeline - will run it tonight and there will be some new data tomorrow.
