### ISSUE TITLE
DS9analysis: plotKnownAst - crash

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#346]
File: DS9analysis
Method: plotKnownAst
Line: 451

plotKnownAst crashes when trying to read a designation number of asteroids that was never found by the function: searchMinorPlanetsNearPosition.

Is it a unit problem of searchMinorPlanetsNearPosition?

**Comment by PolishookDavid** [comment]
D9.plotKnownAst('OrbEl', OrbEl, 'INPOP', IN, 'MagLimit',20)
449             [Result] = searchMinorPlanetsNearPosition(OrbEl, JD, CooCenter(1), CooCenter(2), CooCenter(3), 'INPOP',Args.INPOP, 'CooUnits','deg', 'SearchRadiusUnits','deg', 'MagLimit',Args.MagLimit);
Dot indexing is not supported for variables of this type.

Error in DS9analysis/plotKnownAst (line 451)
            DesigCell = Result.Catalog.Desig;

**Comment by EranOfek** [comment]
bug fixed [dev1 a710572c]
