### ISSUE TITLE
A visit with only 6 images was created 

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#347]
See
/last10w/data1/archive/LAST.01.10.03/2023/12/25/proc/230158v0

In addition the merged asteroids mat file:
230158v0/LAST.01.10.03_20231225.230148.535_clear_054+13_341_001_001_sci_merged_Asteroids_1.mat

has only 71 columns in the Obj.AstCrop(#).SelectedCatPM.Catalog instead of 99 columns.

**Comment by EranOfek** [comment]
The 230158v0/ dir contains only 286 files - this indicate that not all the files were processed.
This is consistent with the pipeline operations - I.e., the pipeline found 10-20 images in the visit, but only 6 of them are good.
Indeed the background level of the processed images is high (full Moon)...
No action needed at this time.
