### ISSUE TITLE
Info: studying the effect of using the cropped PSF

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#349]
With the new algorithm of empirical PSF building (**imProc.psf.populatePSF**) recently approved as the standard for the LAST pipeline, the size of the PSF stamp increased from 17 x 17 pix to 25 x 25 pix, and that leads to substantially enhanced runtime of the pipeline, which is a critical point. 

However, there is an option allowing us to crop the stamp after it has been built, at a given level (quantile) of total flux encirclement. This option can be turned on with two arguments of **pipeline.generic.multiRaw2procCoadd** for the PSFs built at the single epoch and COADD (multi-epoch) levels: 
Args.SingleImconstructPSFArgs   = {'CropByQuantile',true,'Quantile',0.999}; 
Args.CoaddImconstructPSFArgs  = {'CropByQuantile',true,'Quantile',0.999}; 

With such cropping, the typical PSF size is reduced to 11 x 11 pix, and the total pipeline runtime goes down by about 20% compared with the uncropped 25 x 25 pix PSF stamp.

The influence of the said PSF cropping on the output source magnitudes can be illustrated by the following figure:
![croped_vs_noncropped](https://github.com/EranOfek/AstroPack/assets/117931420/88c1a90e-5ed5-4621-a252-33d585fd1add)
One can see that the difference in MAG_PSF is always below 1%, and for over 95% of the objects it is below 0.1%.
The difference in MAG_APER_3  is always below 3 x 10(-5). 

The influence of PSF cropping on the RMS spread also seems to be acceptable. In the first plot the two panels correspond to the cropped and uncropped cases, while in the second plot zoomed onto the faint end of the distribution the cropped case is shown with the red color.
![croped_vs_noncropped_MatchedRMS_v2](https://github.com/EranOfek/AstroPack/assets/117931420/817f2a36-4f6e-4250-a79a-0d85da192d38)
![croped_vs_noncropped_MatchedRMS_v2_zoom](https://github.com/EranOfek/AstroPack/assets/117931420/4feb57b5-dc34-4b6a-a877-9eec74892928)

The overall conclusion: the (limited) testing has shown that PSF cropping substantially accelerates the pipeline without a substantial impact on the resulting source measurements.

**Comment by EranOfek** [comment]
Looks good
