### ISSUE TITLE
Error in constructPSF while using it with the CropByQuantile option

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#351]
Getting the following error while running the pipeline on last10e/cam2 using the new PSF size version (i.e., using PSF stamp size containing 99.9% of the light).
SingleImconstructPSFArgs cell            = {'CropByQuantile',true,'Quantile',0.999};

```
D.main
Using dark: LAST.01.10.02_20230419.221333.297_clear_____dark_proc_Image_1.fits
Using flat: LAST.01.10.02_20231215.151234.869_clear_____twflat_proc_Image_1.fits

09:47:59.468 [INF] pipline.DemonLAST executing pipeline for group 1 - First image: /last10e/data2/archive/LAST.01.10.02/new/LAST.01.10.02_20231226.005510.478_clear_054+13_681_001_001_sci_raw_Image_1.fits

Using dark: LAST.01.10.02_20230419.221333.297_clear_____dark_proc_Image_1.fits
Using flat: LAST.01.10.02_20231215.151234.869_clear_____twflat_proc_Image_1.fits

[09:48:24.769] [ERR] pipeline.DemonLAST try error: For cube input X and Y must be provided / funname: constructPSF @ line: 243
[09:48:24.821] [ERR] Exception: id= msg=For cube input X and Y must be provided
[09:48:24.831] [ERR] stack: Ind=1; FunName=constructPSF; line=243
[09:48:24.846] [ERR] stack: Ind=2; FunName=populatePSF; line=96
[09:48:24.875] [ERR] stack: Ind=3; FunName=singleRaw2proc; line=334
[09:48:24.887] [ERR] stack: Ind=4; FunName=multiRaw2procCoadd; line=389
[09:48:24.890] [ERR] stack: Ind=5; FunName=DemonLAST.main; line=1924
[09:48:24.894] [ERR] pipeline.DemonLAST: 20 images moved to failed directory
09:48:31.364 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd analyzed 20 images starting at 20231226.005510.478
09:48:31.369 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:   23.8
```

**Comment by agioffe** [comment]
In fact, it does not look as a **constructPSF** issue. 
The reason of the error is that no sources are found in the field:

K>> Obj(1).CatData
  AstroCatalog with properties:
      JD: 2.4603e+06
      Catalog: [0×43 double]
     ColNames: {1×44 cell}
     ColUnits: {1×44 cell}
      ColDesc: {}
    SortByCol: []
     IsSorted: 0
     UserData: []
K>> 

The image itself does not look normal both from within the matlab:
![Obj(1)](https://github.com/EranOfek/AstroPack/assets/117931420/4e108c64-e7b0-4ad2-b314-9d90df758221)
(Obj(1).Image)
and from ds9:
![LAST 01 10 02_20231226 005510 478_raw](https://github.com/EranOfek/AstroPack/assets/117931420/9a6b8b2f-b182-4efd-9203-c2964705a515)
(ds9 LAST.01.10.02_20231226.005510.478_clear_054+13_681_001_001_sci_raw_Image_1.fits)

However, I will add a specific error message to **constructPSF** to report such cases from inside it.

**Comment by agioffe** [comment]
Or, probably, a error message should be issued already in **singleRaw2proc** after we search for sources:

SI = imProc.sources.findMeasureSources(SI, Args.findMeasureSourcesArgs{:},...
                                                   'RemoveBadSources',true,...
                                                   'Threshold',Args.Threshold,...
                                                   'ColCell',Args.ColCell,...
                                                   'ZP',Args.ZP,...
                                                   'CreateNewObj',false);

I would add after this something like
for Isub = 1:numel(SI)
   if isempty(SI(Isub).CatData.Catalog)
      error('Some of the sub-images do not contain sources');
   end
end

**Comment by EranOfek** [comment]
yes - note that there are two useful methods of AstroImage/sizeCatalog that
you can use (instead of using the loop):

if any(AI.sizeCatalog<Args.MinNstar)
     [MinVal, MinInd] = min(AI.sizeCatalog);
     error('Sub Image: %d have only %d sources", MinInd, MinVal)
end

where Args.MinNstar is a new argument of the function.

**Comment by agioffe** [comment]
OK, I have added this block and the new argument. I will test it locally and then push up.
