### ISSUE TITLE
Astrometric mis-matched

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#352]
There is an astrometric mis-match between images of this visit:

cd /last06w/data1/archive/LAST.01.06.03/2023/12/15/proc/164358v0
Visit: 164358v0
Mat File:
load('LAST.01.06.03_20231215.164348.418_clear_074+56_081_001_001_sci_merged_Asteroids_1.mat')

Obj.AstCrop element 2
>> D9.blinkAstCrop(Obj,'Id',2)
SubImage      : 4
RA            : 04:44:59.639
Dec           : +54:05:01.44
Nobs          : 11
Noutlier      : 1
PM_RA         : 0.125218 [deg/day]
PM_Dec        : -0.087421 [deg/day]
JD_PM         :  2460294.199404
MAG mean      : 18.120434
MAG range     : 0.308689
S/N mean      : 8.593629
FLAGS         :  HighRN  Overlap
MergedCat     :  GAIA_DRE3  unWISE  tMASS  PS1_DR1
PolyDeltaChi2 : NaN

Also:
Obj.AstCrop element 5

>> D9.blinkAstCrop(Obj,'Id',5)
SubImage      : 14
RA            : 04:49:01.961
Dec           : +53:08:49.65
Nobs          : 20
Noutlier      : 0
PM_RA         : -0.043391 [deg/day]
PM_Dec        : -0.022097 [deg/day]
JD_PM         :  2460294.199404
MAG mean      : 12.783826
MAG range     : 0.069347
S/N mean      : 1087.247220
FLAGS         :  HighRN  Overlap
MergedCat     :  GAIA_DRE3  unWISE  tMASS  PS1_DR1
PolyDeltaChi2 : 5.545634

**Comment by PolishookDavid** [comment]
Bad astrometry also at:
Directory: LAST.01.06.03/2023/12/15/proc/170358v0/
File: LAST.01.06.03_20231215.170348.784_clear_074+56_141_001_001_sci_merged_Asteroids_1.mat
AstCrop element: 4.
>> D9.blinkAstCrop(Obj,'Id',MatVisitNames{Inx(8),2})
SubImage      : 22
RA            : 04:52:37.344
Dec           : +54:14:44.70
Nobs          : 14
Noutlier      : 1
PM_RA         : -0.386947 [deg/day]
PM_Dec        : -0.053931 [deg/day]
JD_PM         :  2460294.213297
MAG mean      : 16.987606
MAG range     : 0.201324
S/N mean      : 25.352392
FLAGS         :  HighRN  Overlap
MergedCat     :
PolyDeltaChi2 : NaN

ans = 

  struct with fields:

    AstCrop: [1×4 struct]

**Comment by EranOfek** [comment]
These stamps are near the image edges and therefore one of the stamps is not full,
and the WCS generated by AstroImage/cropLonLat are incorrect.
This is not a problem with the full image astrometry, but with the stamp astrometry.
Closing this one and opening another issue on - "bug in AstroImage/cropLonLat when stamp is on boundaries"
