### ISSUE TITLE
LAST pipline: FileNames NaN date error

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#356]
```
14:59:42.087 [INF] last_operational: Processed: 23 entries
14:59:42.099 [INF] last_operational: Table coadd_images successfully populated with img metadata
14:59:42.108 [INF] Insert images to LAST coadd images table - success: 1
14:59:42.115 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  641.5
[14:59:44.895] [ERR] pipeline.DemonLAST try error: ls: cannot access '/last10e/data2/archive/LAST.01.10.02//-4712/01/NaN/proc/214837v0': No such file or directory
 / funname: ls @ line: 47
[14:59:44.905] [ERR] Exception: id=MATLAB:ls:OSError msg=ls: cannot access '/last10e/data2/archive/LAST.01.10.02//-4712/01/NaN/proc/214837v0': No such file or directory

[14:59:44.913] [ERR] stack: Ind=1; FunName=ls; line=47
[14:59:44.927] [ERR] stack: Ind=2; FunName=relPath2absPath; line=19
[14:59:44.936] [ERR] stack: Ind=3; FunName=AstroDb.insert; line=652
[14:59:44.943] [ERR] stack: Ind=4; FunName=DemonLAST.main; line=2055
14:59:44.951 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd analyzed 20 images starting at 20231225.214827.075
14:59:44.958 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  653.5
```

**Comment by agioffe** [comment]
The technical reason for the failure is that one of the Coadd images is empty:
K>> EmpCoadd = Coadd.isemptyImage
EmpCoadd =
  24×1 logical array
   1
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
   0
K>>

This leads to a NaN value of JD in the header and further to the NaN in the corresponding file names.
So the question is what to do in such a case, either
1) in **procMergeCoadd** write some JD value in the header even if no image is attached to the Coadd AI object
(may be the same value as in other non-zero-image objects in the stack)
or
2) in **procMergeCoadd** reduce the size of the Coadd AI, excluding objects without images
(may cause problems in other parts of the pipeline?)
or
3) keep the AI with some image properties empty as it is, but 
a) in **writeProduct** do not attempt to write to files the empty images
and
b) in the DB part also exclude such objects explicitly?

I would suggest the last variant, what do you think?

**Comment by EranOfek** [comment]
Apparently it was already implemented, but likely with a bug...

in imProc.io.writeProduct in line 195:
``` 
if (FlagGoodTimes(Iobj) && ~isempty(Obj(Iobj).Image)) || Args.WriteEmpty
```
Checking...

**Comment by agioffe** [comment]
I have updated **db.AstroDb** so that it could deal Coadd AI stacks where some of the images are empty. If now the pipeline runs without errors, this issue can be closed.
