### ISSUE TITLE
celestial.coo.convert2equatorial returns too small corrections

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#357]
Double checking celestial.coo.convert2equatorial after it returned suspiciously small corrections in https://github.com/EranOfek/AstroPack/issues/355#issuecomment-1877285644

I looked at an image: 
/last08e/data1/archive/LAST.01.08.01/new/LAST.01.08.01_20231110.002725.818_clear_field1073_002_001_001_sci_raw_Image_1.fits

In the header it says:

```
JD  =  2460258.5190488 /
M_RA    =     64.7793602687129 /                                                
M_DEC   =     22.5313657522202 /                                                
M_HA    =     26.0345805289545 /                                                
M_JRA   =     64.4341307709482 /                                                
M_JDEC  =     22.4757718275772 /                                                
M_JHA   =     26.4656222155656 /  

```

When using the NED coordinate converter (https://ned.ipac.caltech.edu/cgi-bin/calc?in_csys=Equatorial&in_equinox=J2000.0&obs_epoch=2000&lon=64.43413d&lat=22.47577d&pa=0.0&out_csys=Equatorial&out_equinox=J2024.0) to change from J2000 to J2024, I get:

M_JRA   =     64.4341307709482 /                                                
M_JDEC  =     22.4757718275772 /   
->
64.79165924       22.53305450

So similar, but not identical to the header. Probably this is because refraction is not considered by NED or other factors.

But when using the function, the shifts are much smaller (~ 10 times smaller than they should be):

```
[RA, Dec] = celestial.coo.convert2equatorial(64.434130, 22.47577, 'JD', 2460258.5190488)

RA =

       64.441


Dec =

       22.479

```       

They are as small for all positions, so it's not just a coincidence.

Summary: The equinox shift in the header has a reasonable size, but celestial.coo.convert2equatorial returns too small shifts.

**Comment by noralinn** [comment]
When using goToTarget, Mount.RA and Mount.Dec are equal to M_RA and M_Dec in the header.
But M_JRA and M_JDec are not equal to the input coordinates.

So the corrections done by goToTarget and the ones that are written into the header are inconsistent.


```
>> Unit.Mount.goToTarget(300, 10)

ans =

  logical

   1

>> Unit.Mount

ans = 

  XerxesMountBinary with properties:

                     RA: 300.16
                     HA: 10.305
                    Dec: 10.043
                     Az: 207.79
                    Alt: 67.802
          TrackingSpeed: [0.0041778 0]
           MeridianFlip: 0
              PreferWoP: 1
                 Status: 'tracking'
           IsEastOfPier: 0
    IsCounterWeightDown: 1
                    EMO: 0
                    LST: 310.47

Unit.takeExposure([1],1,1)

```

Header:

```
JD      =     2460316.96930388 /                                                
LST     =     310.517811361181 /                                                
DATE-OBS= '2024-01-07T11:15:47.855' /                                           
M_RA    =     300.162370224914 /                                                
M_DEC   =     10.0429683923721 /                                                
M_HA    =      10.355441136267 /                                                
M_JRA   =     299.879344659153 /                                                
M_JDEC  =     9.98443352193318 /                                                
M_JHA   =     10.6543081681916 /   
```

**Comment by EranOfek** [comment]
celestial.coo.convert2equatorial will be moved to the obsolte directory after we will finalize the new goToTarget function.
