### ISSUE TITLE
celestial.INPOP file in http://data.astropack.org/SolarSystem/INPOP.tar is corrpted

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#358]
The http://data.astropack.org/SolarSystem/INPOP.tar file contains mat files - these mat files are corrupted.

Please upload the files again (from euler:/home/eran/matlab/data/SolarSystem/INPOP).

**Comment by agioffe** [comment]
OK, I will make a tarball tomorrow and will ask Chen to upload it to the repository.

**Comment by agioffe** [comment]
Eran, I cannot reach the directory you mentioned:
sasha@euler:~$ ls /home/eran/matlab/data/SolarSystem/INPOP
ls: cannot access '/home/eran/matlab/data/SolarSystem/INPOP': Permission denied
sasha@euler:~$ 
so I take the files from
/raid/eran/matlab/data/SolarSystem/INPOP/
Is it correct?
BTW, I tried to read some of the .mat files from the current distribution, and they appeared normal.
Could you tell which files were corrupted?

**Comment by agioffe** [comment]
Chen has uploaded the new version, please look and close if it is fine now.

**Comment by EranOfek** [comment]
Not fixes.
Specifically
when running:
```
I=installer;
I.install('INPOP')
IN=celestial.INPOP
IN.populateAll
IN.PosTables.Sun   % contains NaNs
```

**Comment by agioffe** [comment]
Obviously, the data at
/raid/eran/matlab/data/SolarSystem/INPOP/
differs from those at
/home/eran/matlab/data/SolarSystem/INPOP
Please, give me access to the latter directory.

**Comment by EranOfek** [comment]
please copy file from: /raid/eran/INPOP.tar

**Comment by agioffe** [comment]
Uploaded to the repository, reinstalled with the Installer. No more NaNs, hence closing the issue.
