### ISSUE TITLE
celestial.convert.j2000_toApparent(RA, Dec, JD) only works for single coordinates not for arrays

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#359]
I got this error when I called it for an array of RA and Dec values.

```
Error using dot (line 46)
A and B must be same size.

Error in celestial.SolarSys.aberrationSolarSystem (line 44)
    F1      = dot(P, V, 1);

Error in celestial.convert.j2000_toApparent (line 174)
        U2 = celestial.SolarSys.aberrationSolarSystem(U1, E_dotB,
        1);
```

Moreover, it's very slow. When calling in a loop for 50 coordinates it takes 41s.
`
Elapsed time is 41.581144 seconds.`

**Comment by EranOfek** [comment]
please send all the details - specifically, the command you executed and
its variables.

**Comment by EranOfek** [comment]
[dev1 eb70808b] fixed in:
celestial.SolarSys.aberrationSolarSystem
