### ISSUE TITLE
`Configuration.loadFile` errors if the computer is offline

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#360]
To reproduce:
- disconnect the computer from network (e.g. unplug the ethernet cable or disable networking)
```
>> C=Configuration;
>> C.loadFile('pippo.yml')  % it doesn't matter if the file exists or not, for this bug
Error using io.Syslog (line 97)
Unable to bind to LOCALHOST and LOCALPORT. Verify that the LOCALPORT is not in
use, and that LOCALHOST and LOCALPORT are valid for IPADDRESSVERSION "IPV4".

Error in MsgLogger (line 172)
                Obj.Syslog = io.Syslog();

Error in MsgLogger.getSingleton (line 419)
                PersObj = MsgLogger('FileName', Args.FileName, 'UseTimestamp',
                ...

Error in io.msgStyle (line 9)
    m = MsgLogger.getSingleton();

Error in Configuration/loadFile (line 243)
                io.msgStyle(LogLevel.Error, '@error', 'loadFile: Exception: %s',
                FileName);
 ```
Clearly what fails here is `MsgLogger`, but the code of `Configuration.loadFile` calls it for whatever it tries to do.

Why is this important: LAST code needs to be checked also on machines which are offline, and involves a lot of configuration files.

**Comment by agioffe** [comment]
We could put a try .. catch construction into the logger with a warning message produced if there is no connection. In principle, I can do it, but probably, it would be better if it is done by the authors of the logging system @blumzi and @chentishler ?

**Comment by EastEriq** [comment]
Sure.
To be clear: line 97 of io.Syslog, the one which causes the error, calls matlab's `udpport` constructor. That succeeds as long as there is a network connection (_any_ network connection, it doesn't have to be in the observatory net, and the address does not have to be actually reachable), and fails otherwise.

The stupid solution would have been to try-catch that single line, but I guess that then the `Syslog` object created would be invalid, and cause further errors. This is why I also think that the ones who know are better indicated to take care of it.

**Comment by EastEriq** [comment]
Btw, I reproduced this on Simone's pc (last07e), on my desktop pc and on my laptop. All Ubuntu 20 like all LAST machines

**Comment by blumzi** [comment]
Guys, let's take a breather, OK :-)
I'm looking into it and want to get to the root cause.  I'll have to test this in-situ.  The symptoms are obvious, I'll find the root cause and fix accordingly.

BTW, as a rule-of-thumb, the LAST product is rather far from being able to run on non-LAST machines and the first priority is to make it run on proper LAST machines :-)

**Comment by blumzi** [comment]
Fixed, added a catch
