### ISSUE TITLE
Interpolation of saturated pixels inside bright stars leads to donut shapes

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#365]
The center of bright stars that are beyond the saturation limit is not interpolated properly, which causes dips in the star within the image.

See example below:

Screenshot:

![Screenshot from 2024-01-10 15-35-33](https://github.com/EranOfek/AstroPack/assets/51087294/12fdcbd8-dd1f-4588-a393-ea2fe73ff636)

Bit mask values of a pixel within the dip:
```
    {'Saturated'        }
    {'Interpolated'     }
    {'NonLinear'        }
    {'SrcNoiseDominated'}
```

**Comment by EranOfek** [comment]
please specify image name including full path

**Comment by RuslanKonno** [comment]
Example image: /last10e/data1/archive/LAST.01.10.01/2023/11/08/proc/164333v0/LAST.01.10.01_20231108.164633.263_clear_field1213_000_001_001_sci_coadd_Image_1.fits

**Comment by EranOfek** [comment]
Change defrault from:
BitNameBadPix                  = {'Saturated','NaN','Negative'};
to
BitNameBadPix                  = {'NaN','Negative'};

updated live doc
[dev1 2a14f7d5]
