### ISSUE TITLE
Coadd image artifacts with unflagged dark/negative pixels

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#366]
Some coadd images have the following artifacts:

![Screenshot from 2024-01-10 16-25-02](https://github.com/EranOfek/AstroPack/assets/51087294/bee6d80d-ee46-4183-86c4-bf281dbc52a2)

Checking the bit mask values; the bright pixels are flagged with 

```
{'HighRN'       	}
{'DarkHighVal'  	}
{'FlatHighStd'  	}
{'SrcNoiseDominated'}
```

However, the dark pixels have no flags -> valued as good pixels by the pipeline. Sometimes the dark pixels can be negative and still not be flagged.

![Screenshot from 2024-01-10 16-53-28](https://github.com/EranOfek/AstroPack/assets/51087294/dbc129b2-246c-43c5-a29c-61b077e342bd)

Example image: /last10e/data1/archive/LAST.01.10.01/2023/11/08/proc/164333v0/LAST.01.10.01_20231108.164633.263_clear_field1213_000_001_001_sci_coadd_Image_1.fits

**Comment by EranOfek** [comment]
imProc.stack.coadd
In line 219 in: pipeline.generic.procMergeCoadd
sigma clipping is [2 2] and nanmean is used.
Attempt use nanmedian.

Also currently parameters are hard wired in line 219 - need to move these to the argument block.

**Comment by EranOfek** [comment]
Hard weired parameters moved to arguments block.
Replaced the StdFun in the sigmaclipping with tools.math.stat.std_mad (slower but should be more robust).

Note that the fact that the neighboring pixels are not flagged is not a big problem as the bit mask propagation is done within some radius...
[dev1 fe7722b1]
