### ISSUE TITLE
pipeline.DemonLAST ERROR: Dot indexing is not supported for variables of this type

### ISSUE THREAD

**Issue by simonegarrappa** [EranOfek/AstroPack#370]
When running the pipeline, during the saving of the data products the following error is displayed (without stopping the pipeline)

```
14:24:39.531 [INF] pipline.DemonLAST finish executing pipeline for group 1 - start saving data
[14:25:47.728] [ERR] pipeline.DemonLAST try error: Dot indexing is not supported for variables of this type. / funname: DemonLAST.main @ line: 1982
[14:25:47.749] [ERR] Exception: id=MATLAB:structRefFromNonStruct msg=Dot indexing is not supported for variables of this type.
[14:25:47.766] [ERR] stack: Ind=1; FunName=DemonLAST.main; line=1982
[14:25:47.780] [ERR] pipeline.DemonLAST: 20 images moved to failed directory
```
the 20 images are moved to the failed directory but the products seem to be correctly populated in the /proc folder.

To reproduce the issue:

Machine: last05w
CameraNum: 3
command: D.main('StopWhenDone',true,'StartJD',[8 1 2024],'EndJD',[10 1 2024],"SelectKnownAsteroid",false,'SaveAsteroids',false)

**Comment by EranOfek** [comment]
Not enough information to reproduce.
Please specify the computer name, camera, and full file name of the first
file of the visit.

**Comment by simonegarrappa** [comment]
To reproduce the issue:

Machine: last05w
CameraNum: 3
Command: D.main('StopWhenDone',true,'StartJD',[8 1 2024],'EndJD',[10 1 2024],"SelectKnownAsteroid",false,'SaveAsteroids',false)

It happened with all the batches between this StartJD and EndJD. I have moved back to the raw images from the /failed ti the /new directory so you can reproduce it on the same batches.

If you want to run it on a specific visit you this is the first image:

/last05w/data1/archive/LAST.01.05.03/new/LAST.01.05.03_20240108.202102.387_clear_PKS0446+11_001_001_001_sci_raw_Image_1.fits

**Comment by EranOfek** [comment]
When running the pipeline with SaveAsteroids=false, or OnlyMP was not created - a bug.
Fixed by checking if OnlyMP is not empty.

In general avoid running the pipeline with SaveAsteroids=false

[dev1 293e0b4d]
