### ISSUE TITLE
Inconsistency between PH_MAGT and PH_MAGTE

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#371]
In the Header of every proc_Image we found that  while PH_MAGT is MAG_PSF , its error, PG_MGTE is MAGERR_APER_3.

<img width="735" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/e8e6059a-11ff-45a2-b6e2-37ffb3e58f30">

**Comment by EranOfek** [comment]
To fix it: in imProc.calib.photometricZP
change the default of CatColNameMagErr to {'MAGERR_PSF','MAGERR_APER_3'}
Will modify this and test it on Sunday.

**Comment by EranOfek** [comment]
Fixed [dev1 1c402e3d]
