### ISSUE TITLE
MatchedSources.addExtMag bug

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#372]
The product of MS.addExtMag adds the sources magnitude, color and coordinates from the Gaia catalog.
It produces Nsrc Magnitude and color values but less values for RA and Dec, which doesn't make sense since each source in the Gaia catalog have both Magnitudes and Coordinates.

<img width="687" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/c7ef237a-88e1-4dbc-9106-4b0d91eceab5">

**Comment by EranOfek** [comment]
Bug fixed - Added initilaization lines:
ColorVector = nan(1, Nra);
DecVector   = nan(1, Nra);

**Comment by EranOfek** [comment]
[dev1 00561a36]

**Comment by YarinMS** [comment]
Although you initialize by Nra , when conducting a for loop (Ira = 1 : Nra), it looks like the condition : `if ~isnan(RA(Ira)) && ~isnan(Dec(Ira))`
still prevents from RAVector to be in the same length as all others :
<img width="440" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/a222984d-9a12-42cd-bc62-936cf1efb560">

**Comment by EranOfek** [comment]
My mistake - (a typo).
Fixed
[dev1 36f33895]
