### ISSUE TITLE
fitMultiProperMotion outlier rejection is based on a constant value

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#373]
In celestial.pm.fitMultiProperMotion
the outlier rejection process is based on a constant value.
Modify to include sigma clipping rejection.

**Comment by PolishookDavid** [comment]
In many (2/3?) cases the number of outliers from the proper motion fit (column Noutlier) is equal to the number of observations of a source within a visit (column Nobs).
e.g.:
last03e
/last03e/data1/archive/LAST.01.03.01/2024/01/08/proc
CropID: 10

Source:
Visit 204808v0
RA: 94.2149331
Dec: 22.85792
Nobs: 8
Noutlier: 8
TdistProb: 0.999999870758531
Flags: 0
MergedCatMask: 0

![Screen Shot 2024-03-03 at 15 36 45](https://github.com/EranOfek/AstroPack/assets/45033848/e9f72ef8-be66-48da-9c62-12e9c62e6c5d)


Another source:
Visit 205448v0
RA: 94.21250
Dec: 22.85783
Nobs: 12
Noutlier: 12
TdistProb: 1
Flags: 4
MergedCatMask: 0

Another source:
Visit 221929v0
RA: 94.1985569068303
Dec: 22.857356471736
Nobs: 8
Noutlier: 8
TdistProb: 0.9999999
Flags: 4
MergedCatMask: 0

![Screen Shot 2024-03-03 at 15 38 23](https://github.com/EranOfek/AstroPack/assets/45033848/7a316583-9fb3-45c4-9375-f02ec6365a63)

**Comment by EranOfek** [comment]
New version now available - requires a detailed testing.

**Comment by EranOfek** [comment]
A factor of 2 improvement in detection capability.
