### ISSUE TITLE
coadd image boundries are irrelevant

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#375]
coadd image boundries are irrelevant - they have intermediate background level.
Consider modifying this? how about bit mask?

**Comment by agioffe** [comment]
Bit mask would be the best solution if we still have some free bits. Currently 31/32 are already in use, according to the paper draft, right?

**Comment by EranOfek** [comment]
there is already a bit mask for this (number 29), and maybe it is already
on - need to check.

**Comment by agioffe** [comment]
Does it always result from the reduced number of coadded images? Probably, we need another bit to show that this background level should not be used for regular calculations, is it always the case with the reduced number of coadded images or just a boundary effect?

**Comment by EranOfek** [comment]
I think I solve this issue -
specifically, in AstroWCS/xy2refxy when the image size is not divided by sampling.
Fixed by forcing the sampling to include the last column/row.
[dev1 9a75a3fb]
