### ISSUE TITLE
Seeking your opinion re interpolating bad pixels

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#376]
Currently we are interpolating over NaN and Negative pixels (these are very rare in our case), and they are flagged with NaN/Negative bit mask (and also the Interpolated bit mask).
Ia considering stop the interpolation (it tasks ~15s, and have little effect on the results).
Any thoughts?

**Comment by agioffe** [comment]
If this does not crash any of the following code, we can indeed stop it.

**Comment by EranOfek** [comment]
The default is now no interpolation.
Updated live pipeline paper.
