### ISSUE TITLE
relPath2absPath is too slow

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#379]
It has been found that the **tools.os.relPath2absPath** path sanitizer called from **io.fits.writeSimpleFITS** significantly slows down the pipeline. On another side, in some cases using relative paths leads to a crash of **matlab.io.fits.createFile** who fails to create such a file.

As a simple solution, I added an Args.SanifyPath = false argument to **imProc.io.writeProduct** and propagated it down to **io.fits.writeSimpleFITS** where it prevents a call to **tools.os.relPath2absPath**. 

However, we'd need to create a faster version of **tools.os.relPath2absPath**, as it looks that there is no built-in matlab tool to get a file's or directory's full path from a relative path.

**Comment by EranOfek** [comment]
I created a new function: tools.os.relPath2absPath2
that is about two orders of magnitude faster - if it is ok,
just delete old function and rename the new function.

**Comment by agioffe** [comment]
I have tested your new function some and eventually replaced the old one with yours.
