### ISSUE TITLE
Speed improvment of: imUtil.psf.constructPSF (calling moment2 twice)

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#380]
imUtil.psf.constructPSF execute:
imUtil.image.moment2 (14s run time in LAST pipeline).

then it calls:
imUtil.psf.constructPSF_cutout

which execute: imUtil.image.moment2
again (5 s run time).

It seems that there is a duplicate call to moment2 that can be avoided.
Check this out.

**Comment by agioffe** [comment]
Looks like we can pass the values of M1 obtained in imUtil.psf.constructPSF in the call to imUtil.psf.constructPSF_cutouts as:
```
[MeanPSF, VarPSF, NimPSF, FlagSelected] = imUtil.psf.constructPSF_cutouts(Cube(:,:,IndGoodPsf), XY,...
                                                        'Annulus',Args.Annulus,...
                                                        'ReCenter',true,...
                                                        'Back',Back,...
                                                        'SmoothWings',Args.SmoothWings,...
                                                        'SubAnnulusBack',Args.SubAnnulusBack,...
                                                        'SumMethod',Args.SumMethod,...
                                                        **'M1', M1**...
                                                        Args.constructPSF_cutoutsArgs{:});
```
I will check how it works.

**Comment by EranOfek** [comment]
note sure they are the same size, so you may need to select by indices.
Note that when you have a flag of logicals - e.g., F=X>Y; them, when you
are doing a single selection
than
M2(F) is faster.
However, when you use F multiple times then its better to use (faster):
FI = find(X>Y)
M2(FI)
M1(FI)

**Comment by agioffe** [comment]
Your are right, we need to cut out of the calculated M1 array the values for selected PSF stars, so I introduced 
this small changes to the code:
```
M1.X = M1.X(FlagGoodPsf);
M1.Y = M1.Y(FlagGoodPsf); 
        
 [MeanPSF, VarPSF, NimPSF, FlagSelected] = imUtil.psf.constructPSF_cutouts(Cube(:,:,IndGoodPsf), XY,...
                                                        'Annulus',Args.Annulus,...
                                                        'ReCenter',true,...
                                                        'Back',Back,...
                                                        'SmoothWings',Args.SmoothWings,...
                                                        'SubAnnulusBack',Args.SubAnnulusBack,...
                                                        'SumMethod',Args.SumMethod,...
                                                        'M1',M1,...
                                                        Args.constructPSF_cutoutsArgs{:});
```
I checked that M1 is no longer need in the calling routine and that only .X and Y. fields are used inside imUtil.psf.constructPSF_cutouts. 
I also checked on several examples that the PSF that is created here does not change to the machine precision after this improvement is made.
So shall I push this to dev1?

**Comment by EranOfek** [comment]
excellent - yes!

**Comment by agioffe** [comment]
done
