### ISSUE TITLE
Request for opinion: imProc.match.match_catsHTMmerged - running on both coadd and matched catalogs

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#382]
The MergedCat Bit mask is added by:
 imProc.match.match_catsHTMmerged

Currently, in the LAST pipeline it is added to both the catalog of coadd image of the visit,
and to the matched catalog of the merged individual images within the visit?
Each requires about ~13s.
Do we need both? or is the Coadd only enough?

**Comment by agioffe** [comment]
If these data are identical and for each of the sub-image fields it is possible to get it from an output file like
LAST.01.08.03_20230616.222625.384_clear_346+79_000_001_024_sci_coadd_Mask_1.fits
then there is no need to add it the second time.

**Comment by EranOfek** [comment]
they are not identical.
The coadd image goes deeper so in principle contain more sources.
On the other hand, if there is a short term variable in the visit it may be
missing in the coadd...

**Comment by agioffe** [comment]
Then we'd need both.

**Comment by EranOfek** [comment]
I also forgot that it is used by MovingSource so we need it
