### ISSUE TITLE
tools.os.relPath2absPath mistreats names starting from "../"

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#385]
I found that the new version of **tools.os.relPath2absPath** does not work if the name is just "a.fits" or starts with "../".
I have changed it so that the first case ("a.fits" ) is treated separately (the if Ns > 1 clause in the end), but I don't have any good idea how to deal with the case of
FN = '../../a.fits';
Please, look into it when you have some time.

**Comment by EranOfek** [comment]
fixed
