### ISSUE TITLE
MovingSource.blink detect same asteroid 7 times, and DS9analysis.plotKnownAst does not recognize it

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#387]
cd /last03e/data2/archive/LAST.01.03.02/2024/01/08/proc

MP=MovingSource.read
MP.blink
- seven asteroids are found - all are the same one observed at 13 different visits.
- should the code return a single detection or 13 detections (1 per visit)?
The asteroid is very slow - 0.002 arcsec/sec

D9=DS9analysis
D9.load(MP(1).Stamps(1))
D9.plotKnownAst
- does not recognize the asteroid (324 Bamberga).

**Comment by EranOfek** [comment]
A detection per visit.
In the future we can add a function that merge visits...

**Comment by EranOfek** [comment]
The problem was that the preliminary search didn't find the asteroid within the buffer (likely because the orbital elements were not accurate enough without integration).
Increased the default buffer size from 500 to 1000 arcsec fixed the problem.
[dev1 f06b9861]
