### ISSUE TITLE
Catalog search results in error when near latitude slice of catalog is empty in VO.search.search_sortedlat_multiNearest

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#388]
Matching external catalogs to an AstroCatalog results in an error when catalog sliced by latitude and near sources is empty, crashing any running process. See error below.

```
Index exceeds the number of array elements. Index must not exceed 0.

Error in VO.search.search_sortedlat_multiNearest (line 67)
Ilowhigh = double(Inear(Ilat));

Error in imProc.match.matchReturnIndices (line 152)
        [IndTable, CatFlagNearest, CatFlagAll, IndInObj2] = VO.search.search_sortedlat_multiNearest(Coo1,...

Error in imProc.match.match_catsHTM (line 127)
            ResInd = imProc.match.matchReturnIndices(CatH, Obj, 'CooType','sphere',...

Error in imProc.sources.findTransients (line 256)
        [TranTable, ~, ~, ~] = imProc.match.match_catsHTM(TranTable, ...
```

Crash occurs because Inear() is empty. It would be preferable if the catalog match returned no matches rather than crashing.

For reproduction,
AstroCat file: 
[cat.zip](https://github.com/EranOfek/AstroPack/files/14025189/cat.zip)
Catalog: CRTS_per_var
Command: [TranTable, ~, ~, ~] = imProc.match.match_catsHTM(TranTable, 'CRTS_per_var');

**Comment by EranOfek** [comment]
Fixed in low level: VO.search.search_sortedlat_multi
[dev1 2eaa474d]
