### ISSUE TITLE
Redundant header keywords: CAMNUM, FIELDID, CCDID, BZERO

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#40]
CAMNUM and CAMPOS are redundant. Get rid of CAMPOS.
OBJECT and FIELDID also redundant in current files.

There's only one ccd per camera, so is CCDID always 1?

BZERO and BSCALE are optional, if you are not planning to rebin the images you can leave them out.

**Comment by EranOfek** [comment]
In LAST CCDID is always 1.
CAMNUM and CAMPOS are kept for clearity.

**Comment by EastEriq** [comment]
BZERO and BSCALE turn out to be all but optional! see Issue #66
