### ISSUE TITLE
two epochs passed to `celestial.OrbitalEl.integrateElements`

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#405]
My top call is
```
imProc.match.match2solarSystem(AI(k), 'JD',[], 'INPOP',INPOP,'OrbEl',OrbEl,'AddColNmatch',false,'AddColDesignation',false);
```
with an AstroImage `AI(k)` containing  389 sources centered at about (176,-6). The stack trace is
```
Error using celestial.OrbitalEl/integrateElements
All Epoch must be the same

Error in celestial.ephem.ephemMultiObj (line 124)
        [ObjTime, U_B, U_Bdot, S_B, S_Bdot] = integrateElements(Obj, Time, 'TimeScale',Args.TimeScale,...

Error in celestial.OrbitalEl/searchMinorPlanetsNearPosition (line 1888)
                        Result(Iobj) = celestial.ephem.ephemMultiObj(ObjNew(Iobj), JD, 'INPOP',Args.INPOP,...

Error in imProc.match.match2solarSystem (line 236)
                [AstCat] = searchMinorPlanetsNearPosition(Args.OrbEl, Cat.JD, CatCoo(1), CatCoo(2), CatCoo(3),...
```
and indeed when reaching line  1561 of `celestial.OrbitalEl.integrateElements` I see that `Obj.Epoch` contains two unique values differing by exactly 200. Now I should understand the mechanics of all what leads to it, and figure out reason or workaround.

**Comment by EastEriq** [comment]
I can add that I don't get an error if I call `imProc.match.match2solarSystem(... 'Integration',false)`, bypassing `ephemMultiObj`; but in that case I also get unmodified `AI(k).CatData`.

**Comment by EastEriq** [comment]
If it helps to debug, when entering `integrateElements`:
```
K>> Obj

Obj = 

  OrbitalEl with properties:

         Number: [91×1 double]
    Designation: {91×1 cell}
           Node: [91×1 double]
              W: [91×1 double]
           Incl: [91×1 double]
              A: [91×1 double]
       PeriDist: [91×1 double]
          Eccen: [91×1 double]
             Tp: [91×1 double]
          Epoch: [91×1 double]
         Mepoch: [91×1 double]
         MagPar: [91×2 double]
        MagType: 'HG'
        Equinox: 'J2000.0'
       AngUnits: 'deg'
       LenUnits: 'au'
      TimeUnits: 'day'
              K: 0.017202
            Ref: {91×1 cell}
       UserData: []

K>> find(Obj.Epoch==StartEpoch(2))

ans =

    91

K>> Obj.Number(91)

ans =

   NaN

K>> Obj.Designation(91)

ans =

  1×1 cell array

    {'2024 CQ7'}
```

**Comment by EastEriq** [comment]
And besides the 2024 in the Designation, this last object 91 is the only one which has  `Obj.Ref`  'E2024D35' instead of '`JPL `_somenumber_'. Does the fact that it is a very recently discovered object conflict with some other assumption somewhere?

**Comment by EastEriq** [comment]
I keep finding similar cases analyzing other images. In the few cases I inspected it is always only one of the last entries in Obj which has a different `Obj.Epoch`, but if I look at `.Designation` I also find 2021, 2023, and `.Ref` JPL.

**Comment by EranOfek** [comment]
How did you created OrbEl in the first place?
In order for all the orbital elements to have the same epoch (as required)
you have to use:
OrbEl = celestial.OrbitalEl.loadSolarSystem('merge');

**Comment by EastEriq** [comment]
I have
```
OrbEl = celestial.OrbitalEl.loadSolarSystem;
OrbEl = OrbEl.merge;
```
as per your instruction.  Property arrays have 1350114 elements, with the data installed a few days ago. Do you imply that `celestial.OrbitalEl.loadSolarSystem('merge')` does something different?

**Comment by EastEriq** [comment]
Indeed it does something different as it produces arrays of 1302476 elements.

**Comment by EastEriq** [comment]
ok, with `OrbEl = celestial.OrbitalEl.loadSolarSystem('merge');` the issue is gone, closing. But it is again a "how could I know". Not that I would have understood it from https://github.com/EranOfek/AstroPack/wiki/celestial.OrbitalEl
