### ISSUE TITLE
`imProc.match.match2solarSystem()` fills the column `DistMP` with a constant value for all unmatched sources

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#407]
This happens in -- uhm, 10% of the cases in the field I'm processing now. I call `match2solarSystem()` on AstroImages containg an AstroCatalog, but the bug is exhibited well by the following example.

The attached file contains an AstroCatalog `AC` with 618 sources. 

```
AC = 

  AstroCatalog with properties:

           JD: 2.4575e+06
      Catalog: [618×39 double]
        Table: [618×39 table]
     ColNames: {1×39 cell}
     ColUnits: {1×39 cell}
      ColDesc: {}
    SortByCol: 38
     IsSorted: 0
     UserData: []
```
Calling `match2solarSystem()`, three minor planets are matched, fine, and a 40th column is added to the new `AC`:
```
>> [SourcesWhichAreMP, CatData,AC]=imProc.match.match2solarSystem(AC,'JD',[], 'INPOP',INPOP,'OrbEl',OrbEl,'AddColNmatch',false,'AddColDesignation',~false)

SourcesWhichAreMP = 

  AstroCatalog with properties:

           JD: 2.4575e+06
      Catalog: [3×41 table]
        Table: [3×41 table]
     ColNames: {1×41 cell}
     ColUnits: {1×41 cell}
      ColDesc: {}
    SortByCol: 38
     IsSorted: 0
     UserData: []


CatData = 

  AstroCatalog with properties:

           JD: []
      Catalog: [63×11 table]
        Table: [63×11 table]
     ColNames: {1×11 cell}
     ColUnits: {1×11 cell}
      ColDesc: {}
    SortByCol: []
     IsSorted: 0
     UserData: []


AC = 

  AstroCatalog with properties:

           JD: 2.4575e+06
      Catalog: [618×40 double]
        Table: [618×40 table]
     ColNames: {1×40 cell}
     ColUnits: {1×40 cell}
      ColDesc: {}
    SortByCol: 38
     IsSorted: 0
     UserData: []
```
However, all but three `AC.Table.DistMP` should be NaNs, and they are not:
```
>> numel(find(~isnan(AC.Table.DistMP)))

ans =

   618

>> AC.Table.DistMP'

ans =

  Columns 1 through 6

       1.9347       1.9347       1.9347       1.9347       1.9347       1.9347

  Columns 7 through 12

       1.9347       1.9347       1.9347       1.9347       1.9347       1.9347

....
```

**Comment by EastEriq** [comment]
[astrocatalog.mat.gz](https://github.com/EranOfek/AstroPack/files/14377484/astrocatalog.mat.gz)

the AstroCatalog in question. Is it me, or github is erratically unavailable in the last couple of days?

**Comment by EastEriq** [comment]
Also, *to be clear*, in ~90% of the other images the result is sane, a few sources are matched, DistMP is some small number of arcsec for those entries, and all other ones are NaNs as expected.

**Comment by EastEriq** [comment]
Also, *to be clear*, in ~90% of the other images the result is sane, a few sources are matched, DistMP is some small number of arcsec for those entries, and all other ones are NaNs as expected.

**Comment by EranOfek** [comment]
This is an important bug that will affect tag v2.0.

The bug is located near line 305 in match2solarSystem.
To fix it, I added:
Obj_DistCol(IsnanTmp) = NaN;
Result seems good, but please check independetly.
[dev1 664649f7]

**Comment by EastEriq** [comment]
With your fix the code seems to work (no situation as initially reported, over 332 PTF subimages), but I can't understand how the code works. Perhaps it should be rewritten in a more readable way for future maintenance.

As a matter of fact, in these 332 2kX2k subimages in the sign of Virgo, I get in average one or two asteroids identified. However, the mean distance is always several arcsecs (up to 10" which is the default search radius, despite 5" said in the help, snafu). Only 2/322 are found at less than 1". Now, astrometry is supposed to be capable of doing much better. Is it because the ephemerides or the integrated positions are imprecise, or because in lack of neighbors a candidate match is proposed with a much weaker closeby object? Are apparent magnitudes taken in to account at all for the search? (I see only output options for the predicted magnitude). In the case of PTF, magnitude may be a hairy concept because we would have to compute it in the spectral band of the Ha filter used (maybe easy, the solar emission spectrum is known).

**Comment by EranOfek** [comment]
I updated the help of imProc.match.match2solarSystem
and also:
https://github.com/EranOfek/AstroPack/wiki/MinorPlanetsEphemerisAndMatch

The accuracy depends on how well the orbit is known. A few arcsecond is reasonable for most asteroids.
