### ISSUE TITLE
`MatchedSources.unifiedCatalogsIntoMatched` creates lots of rows with only NaNs

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#408]
Attached is a file containing a two element AstroCatalog, containing 364 sources in one element and 478 in the second. Note that the only NaNs in both catalogs are in column 40, `DispMP`, for all sources but  the couple which is identified as minor planet in (1) and the one which is in (2). That should not affect the merging, though.

Instead, when I run
```
MS=MatchedSources;
MS.unifiedCatalogsIntoMatched(AC, 'Radius',3, 'MatchedColums',...
    {'JD','RA','Dec','X','Y','MAG_PSF','MAGERR_PSF','SN','GAIA_ZP','FLAGS',...
     'MERGED_CAT_MASK','DistMP'});
```
I get a collection of 746 entries, in which  the last 191 (556:746, no less!) have *all* properties NaN:
```
>> find(all(isnan(MS.Data.JD)))

ans =

  Columns 1 through 11

   556   557   558   559   560   561   562   563   564   565   566

  Columns 12 through 22

   567   568   569   570   571   572   573   574   575   576   577

....
```
etc. for `.RA`, `.Dec` and so on. What is going on?

[astrocatalog.mat.gz](https://github.com/EranOfek/AstroPack/files/14397006/astrocatalog.mat.gz)

**Comment by EastEriq** [comment]
I'm pretty convinced that the bug is in this line https://github.com/EranOfek/AstroPack/blob/bcbdcff860a458d943894065eeda22f438b7ee37/matlab/image/%2BimProc/%2Bmatch/unifiedSourcesCatalog.m#L119
which should be moved above line 116 instead. Tat solves the issue for me, but a) we should be careful with validation, b) I'm still investigating because I think I see another bug here,

**Comment by EranOfek** [comment]
This is indeed a bug (harmless but important, as it inflate the output).
The bug is in: imProc.match.unifiedSourcesCatalog

Bug fixed.
[dev1 c176b819]
