### ISSUE TITLE
io.files.mex.mex_writecsv sometimes writes extra numbers to a CSV file

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#410]
I found that **io.files.mex.mex_writecsv** sometimes adds small numbers to CSV lines when dumping cell arrays, and these extra numbers in a line make the SQL COPY command crash during bulk insertion to a DB.
E.g., here is a part of the cell array (catalog line) to be dumped to a CSV file:
```
>> Matrices{3}(1:5,end-5:end)
ans =
   2.4603e+06            3            1            1            1          400
   2.4603e+06            3            1            1            1          400
   2.4603e+06            3            1            1            1          400
   2.4603e+06            3            1            1            1          400
   2.4603e+06            3            1            1            1          400
>>
```
A test dumping sequence is:
```
load('~/Matrices.mat')
FileName = '/home/sasha/testcat.csv';
io.files.mex.mex_writecsv_double(Matrices, ColNames, FileName);
```
The corresponding part of the output file looks like:
```
sasha@WRX80:~/matlab/AstroPack$ head -n 8486 ~/testcat.csv |tail -n 5
40,2,40.0096,2.14226,1.20235,1.05675,0.035702,4.72595,15.4408,16.4936,13.6518,8.35474,121.331,7.59273,121.331,5.05164,130.375,213.39,228.001,0.095768,0.072434,0.0698344,20.2484,19.7135,19.6416,0.104004,0.0786634,0.0758402,746586116,39.8513,1.69105,224.828,19.6568,0.0736405,1.73636,14.7473,60.0331,64.2185,67,-nan,2.46029e+06,3,1,1,1,400,0
181,2,180.547,2.2949,1.20994,0.760148,0.0825803,138.337,289.402,293.677,242.648,159.725,121.668,8.04329,121.668,6.20962,2349.53,3949.5,4192.73,0.0207991,0.0159896,0.0155146,17.109,16.5451,16.4802,0.0225878,0.0173647,0.0168488,746586244,180.58,2.21737,4391.24,16.43,0.0164034,12.1953,66.2058,60.1458,64.2203,71,8,2.46029e+06,3,1,1,1,400,1.71589e-320
263,3,262.854,3.18598,0.712371,1.63265,0.689426,2.60485,6.52478,7.43627,6.39037,3.54119,121.75,7.9546,121.75,2.6315,53.0388,112.586,113.48,0.145999,0.0971001,0.0966945,21.2246,20.4076,20.399,0.158555,0.105451,0.10501,746586116,262.972,3.06023,101.5,20.5202,0.111939,2.91372,9.70174,60.2117,64.2215,67,-nan,2.46029e+06,3,1,1,1,400,6.90556e-310
46,12,46.2825,11.7068,1.17315,0.95823,0.0626368,9.61475,22.029,23.3528,20.1292,13.1335,121.331,7.59273,121.331,4.78626,169.618,330.458,346.038,0.0818036,0.0568848,0.0555083,19.9627,19.2386,19.1886,0.0888387,0.0617769,0.060282,746586116,46.31,11.7318,333.089,19.23,0.0601788,0.382677,18.0462,60.038,64.222,71,13,2.46029e+06,3,1,1,1,400,6.9044e-310
32,14,31.4825,14.0051,1.23706,0.848044,0.0658268,12.3475,25.3361,25.4613,20.7111,12.8775,121.331,7.59273,121.48,3.90763,185.378,320.107,346.64,0.0764115,0.0572099,0.0548809,19.8663,19.2732,19.1867,0.0829829,0.0621299,0.0596007,209715236,31.835,13.9679,366.08,19.1275,0.0573455,0.566399,18.9378,60.0263,64.2227,71,16,2.46029e+06,3,1,1,1,400,0
sasha@WRX80:~/matlab/AstroPack$ 
```
Note that the lines contain extra numbers after "400", that should not be present.

**Comment by agioffe** [comment]
I found that **io.files.mex.mex_writecsv** is actually not to blame here (sorry, @chentishler)! 
Though it is this function that adds extra numbers, it is because for some yet unknown reason in some of the crops the size of **Coadd.CatData.Catalog** is smaller than it should be, with one of the columns in the middle completely missing:
K>> for i=1:24
size(Coadd(i).CatData.Catalog)
end
ans =   4082          43
ans =   4398          43
ans =   4145          **42**
ans =   3665          43
ans =   3459          **42**
ans =   3235          **42**
ans =   3628          43
ans =   3907          43
ans =   3610          43
ans =   3124          43
ans =   3415          43
ans =   3396          43
ans =   3461          43
ans =   3575          43
ans =   3064          43
ans =   2933          43
ans =   3314          43
ans =   3489          43
ans =   3129          43
ans =   3337          43
ans =   2666          43
ans =   2966          43
ans =   3486          43
ans =   3491          43
```
This is a visit starting from 
/last01e/data1/archive/LAST.01.01.01/new/LAST.01.01.01_20231214.200400.739_clear_WD0434+637_001_001_001_sci_raw_Image_1.fits

**Comment by agioffe** [comment]
I finally found what's going on. This is a result of **imProc.match.match2solarSystem**. When there is at least one asteroid in the FOV of a particular subimage, this function adds the column "distMP" to its catalog, but when there are no asteroids in the FOV, it does not add an empty column, and thus, in the same Coadd object we are getting catalogs of varying width. This further makes **io.files.mex.mex_writecsv**, who does not check whether the dimensions of the input vector of catalogs are the same for all the elements, produce incorrect CSVs and then the SQL COPY command crash on them.
Eran @EranOfek , shall I correct **imProc.match.match2solarSystem** or you prefer to do it yourself?

**Comment by agioffe** [comment]
P.S. I'd suggest in  **imProc.match.match2solarSystem** after
```
if isemptyCatalog(AstCat) || isemptyCatalog(Cat)
                % No Asteroids in search radius - skip
                SourcesWhichAreMP(Iobj)    = AstroCatalog;
                SourcesWhichAreMP(Iobj).JD = Cat.JD;
```
add 1 line:
```
                insertCol(Cat, nan(size(Cat.Catalog,1),1), Args.SourcesColDistPos, Args.SourcesColDistName, Args.SourcesColDistUnits);
```

**Comment by EranOfek** [comment]
This solution will not solve the problem.
The problem is in the nargout>2 block which is inside the  else clause of "isemptyCatalog(AstCat) || isemptyCatalog(Cat)"

The solution should be taking lines 304-328 out of the else clause of  "isemptyCatalog(AstCat) || isemptyCatalog(Cat)".
I will test it carefully on Sunday.

**Comment by agioffe** [comment]
Thanks! Then I will not touch it. We just need to have it settled before we issue a new tag and restart.

**Comment by EranOfek** [comment]
Fixed by adding:

                % Fixing issue 410:
                if nargout>2
                    Nline = Cat.sizeCatalog;
                    Obj_DistCol = nan(Nline,1);
                    insertCol(Cat, Obj_DistCol, Args.SourcesColDistPos, Args.SourcesColDistName, Args.SourcesColDistUnits);
                end

**Comment by EranOfek** [comment]
[dev1 60768e0e]

**Comment by agioffe** [comment]
OK, thanks!
