### ISSUE TITLE
wrong application of proper motion in `MatchedSources.addExtMagColor`

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#415]
I have e.g. the MatchedSources object MS1 in the attached file. If I call `MS1.addExtMagColor` i get wrong matches, as apparent from
```
plot(MS1.SrcData.ExtRA,MS1.SrcData.ExtDec,'ro',MS1.Data.RA,MS1.Data.Dec,'b.')
```
![image](https://github.com/EranOfek/AstroPack/assets/16066531/27750276-5678-4db8-9116-85bc6bfd5973)
It turns out that this because of proper motion, which apparently here is applied wrongly (in the first place, I wouldn't expect it to be big and to affect all sources in a field, but what do I know). Indeed the match is correct if I call `MS1.addExtMagColor('ApplyPM',false)` instead.

[matchedsources.mat.gz](https://github.com/EranOfek/AstroPack/files/14549442/matchedsources.mat.gz)

**Comment by EranOfek** [comment]
can you please send me the name of one file on which you execute it so I
can try to recreate the problem.

**Comment by EastEriq** [comment]
A file is already attached to the issue

**Comment by EastEriq** [comment]
Hm, probably this happens because in this object `MS1.JD`=1. If I set
```
MS1.JD=unique(MS1.Data.JD(~isnan(MS1.Data.JD)))
MS1.addExtMagColor
plot(MS1.SrcData.ExtRA,MS1.SrcData.ExtDec,'ro',MS1.Data.RA,MS1.Data.Dec,'b.')
```
then the result is consistent:
![image](https://github.com/EranOfek/AstroPack/assets/16066531/81a841c9-98a9-4870-aaf6-b078c359832f)
I remark that I'm concerned with JD already since #409.

**Comment by EastEriq** [comment]
To say it differently, I don't understand if it is deliberate that `MatchedSources.unifiedCatalogsIntoMatched(AstroCatalogs)` sets `MS.JD`=1:N instead of taking, by default, `AC.JD`.

**Comment by EranOfek** [comment]
Check if it is possible to populate the JD while the MatchedSources is created.
