### ISSUE TITLE
MatchedSources objects :  add Sub-Image center & corner coordinates 

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#416]
We would like to add the  Sub-Image corner coordinates to the MatchedSources object.
We Also want the sub frame centroid coordinates, to get an idea about the field location. 
(By looking at MS objects we can see the coordinates of targets within but we would like to have information about the centroid coordinate.)

**Comment by EranOfek** [comment]
This information is available in the catalogs and images. In the catalogs the information is stored in HDU=3.
One solution is to to read the header of one of the images/catalogs when reading the MatchedSources object.
