### ISSUE TITLE
`modeVar_LogHist` error when computing background of my `improc.mask.maskTracks`  example

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#419]
What I wrote as example might be pretty unrepresentative for an astronomical image. How would you recommend to proceed though? The example could be well be made more realistic, if that is the problem.
```
>>  AI=AstroImage();
>> AI.Image=20*imUtil.art.createSegments([650,700],...
                        [322,233;98,0],[54,11;145,211],'width',0.5) + ...
                        rand(650,700);
>> imProc.background.background(AI);
Error using matlab.internal.math.histcounts
At least two bin edges must be specified.

Error in imUtil.background.modeVar_LogHist (line 102)
    Nhist = matlab.internal.math.histcounts(LogArray, Edges);

Error in imUtil.background.background (line 138)
        [SubImage(Isub).Back, SubImage(Isub).Var] = Args.BackFun(SubI,Args.BackFunPar{:});

Error in imProc.background.background (line 131)
                            imUtil.background.background(Obj(Iobj).(Args.ImageProp).(Args.ImagePropIn),...
```
I acknowledge that after `modeVar_logHist` was introduced, issues #308, #310 and #412 were reported

**Comment by EranOfek** [comment]
you can try and change the background method - for example, use:
***@***.***

**Comment by EranOfek** [comment]
BackMethod,@median

**Comment by EastEriq** [comment]
There is no such key 'BackMethod' in `imProc.background.background`. With `'BackFun',@median` as a guess I get:
```
>> imProc.background.background(AI,'BackFun',@median);
Error using median
Too many input arguments.

Error in imUtil.background.background (line 138)
        [SubImage(Isub).Back, SubImage(Isub).Var] = Args.BackFun(SubI,Args.BackFunPar{:});

Error in imProc.background.background (line 131)
                            imUtil.background.background(Obj(Iobj).(Args.ImageProp).(Args.ImagePropIn),...
 
```

**Comment by EastEriq** [comment]
In any event, yes I can modify my maskTrack example changing image levels so that the call doesn't error out with the default parameters, like
```
>> AI.Image=2000*imUtil.art.createSegments([650,700],[322,233;98,0],[54,11;145,211],'width',0.5) +100*rand(650,700); 
>> imProc.background.background(AI);
>> imagesc(imProc.mask.maskTracks(AI))
```
but the computed `.Back` and `.Var` apparently deviate from those achieved with the former method, and as a result the thresholding which identified tracks now delivers bogus results:

![image](https://github.com/EranOfek/AstroPack/assets/16066531/c079d84d-c5c3-4cc3-a2a0-87e268b18fa8)

![image](https://github.com/EranOfek/AstroPack/assets/16066531/9e34131a-2b1e-48b0-883e-49c262bce2df)

![image](https://github.com/EranOfek/AstroPack/assets/16066531/295c7d1f-e8c2-424e-a8a7-fb13cd115482)

**Comment by EranOfek** [comment]
imUtil.background.modeVar_LogHist is designed to work with Poisson
(positive) distributed values.
Therefore, it will not work when you use non-Poisson distributions.

To use the @median option you also need to change the BackFunPar argument
to something like: {'all','omitnan'})

**Comment by EastEriq** [comment]
No, `@median` is not a good  `'BackFun'`, as the code stands now:
```
>> AI=AstroImage();
>> AI.Image=2000*imUtil.art.createSegments([650,700],[322,233;98,0],[54,11;145,211],'width',0.5) +100*rand(650,700); 
>> imProc.background.background(AI,'BackFun',@median,'BackFunPar',{'all','omitnan'});
Error using median
Too many output arguments.

Error in imUtil.background.background (line 138)
        [SubImage(Isub).Back, SubImage(Isub).Var] = Args.BackFun(SubI,Args.BackFunPar{:});

Error in imProc.background.background (line 131)
                            imUtil.background.background(Obj(Iobj).(Args.ImageProp).(Args.ImagePropIn),...
```
In fact `median` returns only one argument, and not the variance as second.
So what needs to be passed in order to have the same behavior as once? I need to compare some side effects of computing the background with the one or the other algorithm.

**Comment by EastEriq** [comment]
Not this....
```
>> imProc.background.background(AI,'BackFun',@median,'VarFun',@imUtil.background.rvar);
Error using median
Too many input arguments.

Error in imUtil.background.background (line 142)
         SubImage(Isub).Back = Args.BackFun(SubI,Args.BackFunPar{:});

Error in imProc.background.background (line 131)
                            imUtil.background.background(Obj(Iobj).(Args.ImageProp).(Args.ImagePropIn),...
```

**Comment by EastEriq** [comment]
Uff,
```
imProc.background.background(AI,'BackFun',@median,'BackFunPar',{'all','omitnan'},'VarFun',@imUtil.background.rvar);
```
Not really intuitive that you need explicitly so many arguments to avoid errors.

**Comment by EastEriq** [comment]
It may be of little importance for typical astronomical images with poissonian noise, but are you aware that the new algorithm of `modeVar_LogHist` can produce negative variance?

I am correcting the example and the code of maskTracks to take this into account, to get out of it, but I'd be careful. 
Check e.g,. a few realizations of
```
AI.Image=1000*rand(650,700);
imProc.background.background(AI);
imagesc(AI.Var);colorbar
```

**Comment by EranOfek** [comment]
Will generate an error if variance is negative.
[dev1 369f2a17]

**Comment by EastEriq** [comment]
Adding a note: I'm finding several PSF images where
```
imProc.background.background(AI, 'SubSizeXY',nwindbg*[1,1],...
    'Overlap',nwindbg/2,'BackFun',@median,...
    'BackFunPar',{'all','omitnan'},'VarFun',@imUtil.background.rvar);
```
performs much better than the new default. Much better means able to cope even with borderline garbage images, succeeding in finding sources in further processing, and not complaining about negative Var or Nan Mode. One could rightly argue that garbage images (with lots of defect, unreasonably high background, etc.) deviate from supposed Poissonian statistics. What would be a criterion to determine which background strategy is best?
