### ISSUE TITLE
error undefined `Answer` in `ds9.frame`

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#423]
```
>> ds9.frame(1)
Unrecognized function or variable 'Answer'.

Error in ds9.frame (line 432)
                Answer = sscanf(Answer,'%d');
 
```

**Comment by EastEriq** [comment]
At line [426](https://github.com/EranOfek/AstroPack/blob/e9aafcf50bfeacd21b9f9a13f2f97b10296c0666/matlab/image/%40ds9/ds9.m#L426) above it, `nargout` is 0 even if called from prompt without suppressing the output. Too bad, but it is a matlab feature. I don't know whether to change the condition at line 426, maybe there are cases in which we want to vavoid an additional xpaget for better responsiveness.

**Comment by EranOfek** [comment]
[dev1 b7fb2c93]
fixed.
