### ISSUE TITLE
Table of known asteroid has multiple complex values

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#424]
Telescope: LAST.01.01.01
Date: 2024/03/09
Visit: 223206v0

Mp.KnownAst.Table

           JD                  RA                  Dec                  R                 Delta                   SOT                     STO                   TSO                            Mag                       Desig             Dist      
    ________________    ________________    _________________    ________________    ________________    _____________________    ___________________    __________________    ___________________________________    ___________    ________________

    2460379.44116738    169.846708798659    -1.02854502431986    2.90660024410688    1.90921906275556    180-6.52772273181987i    0+2.23468218632707i    0+4.2930405454928i    17.0934555831328+0.212451243692107i    "1998 QV40"    2.36945506169527

           JD                  RA                  Dec                   R                 Delta                   SOT                     STO                    TSO                            Mag                      Desig             Dist      
    ________________    ________________    __________________    ________________    ________________    _____________________    ___________________    ___________________    ___________________________________    __________    ________________

    2460379.44116738    169.852961543216    0.0134786399979101    2.09112047642719    1.09244209585854    180-8.35896191546813i    0+3.98083160460996i    0+4.37813031085817i    17.4689810264315+0.303914327308576i    "1144 T-2"    3.96107739120817

           JD                  RA                   Dec                   R                 Delta                   SOT                     STO                    TSO                            Mag                         Desig              Dist      
    ________________    ________________    ___________________    ________________    ________________    _____________________    ___________________    ___________________    ___________________________________    _______________    _______________

    2460379.44116738    169.727745142236    -0.0923882347958392    2.74871313423642    1.75043347759458    180-7.29636849966543i    0+2.64245093336014i    0+4.65391756630529i    16.6595643756479+0.235775237969437i    "Rockwell Kent"    2.2817535022444

           JD                  RA                  Dec                   R                 Delta                   SOT                     STO                    TSO                           Mag                     Desig           Dist      
    ________________    ________________    __________________    ________________    ________________    _____________________    ___________________    ___________________    __________________________________    _______    ________________

    2460379.44116738    171.162260740741    -0.676416885420685    2.07377131440281    1.07553836331191    180-8.04587117896752i    0+3.86295823822167i    0+4.18291294074585i    16.393158657671+0.298321027036575i    "Dewar"    4.30631652929164

            JD                 RA                  Dec                   R                  Delta                  SOT                     STO                    TSO                            Mag                       Desig              Dist      
    ________________    _______________    __________________    ________________    _________________    ____________________    ___________________    ___________________    ___________________________________    ____________    ________________

    2460379.44116738    171.32088045587    -0.615855598264652    1.92338103224332    0.924990663405303    180-8.4822264883253i    0+4.39152105975256i    0+4.09070542857274i    16.8292685978597+0.322907779235179i    "2001 SE163"    4.52890865004861

**Comment by EranOfek** [comment]
The following problem was identified:
In celestial.OrbitalEl/prepEphemOutput
R was calculated as barycentric value instead of heliocentric. This causes R_obs+Delta<R, and hence complex values...
prepEphemOutput know gets as an additional argument S_B.

Fixed:
[dev1 da9e9498]
