### ISSUE TITLE
`imProc.match.match_catsHTMmerged` isn't finding a catalog file?

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#428]
First time I see running my pipeline. This happens for an image centered at about (357.22, -20.55).
```
Error using hdf5lib2
Unable to open 'MergedCat_htm_668300.hdf5'. File or folder not found.

Error in H5F.open (line 130)
file_id = H5ML.hdf5lib2('H5Fopen', filename, flags, fapl, is_remote);

Error in HDF5.load (line 145)
            FID = H5F.open(FileName);

Error in catsHTM.cone_search (line 1807)
                    C(Iid).Cat = HDF5.load(FileName,DataName).';

Error in imProc.match.match_catsHTMmerged (line 82)
                CatH  = catsHTM.cone_search(Args.MergedCatName, CircX, CircY, CircR, 'RadiusUnits','rad', 'Con',Args.Con, 'OutType','astrocatalog');

Error in full_treatment_one_image (line 540)
imProc.match.match_catsHTMmerged(AI(k));
 
```
I presume that such files should be on euler in `/home/enrico/matlab/data/`. I installed them not so long ago, I didn't get the impression that they were incomplete then.

**Comment by EastEriq** [comment]
also 'MergedCat_htm_681200.hdf5' not found, processing another image. I'm running a batch on several fields now, maybe I'll report about more missing when it completes.

**Comment by EastEriq** [comment]
I thought of reinstalling catalogs with `I.install('cats');` but I realized that it may take up 54GB of disk space on euler. If there is another way, please advise

**Comment by agioffe** [comment]
```
I.install('cats'); 
```
would not include _MergedCats_, because these are too heavy, about 260 Gb. _MergedCats_ is distributed by hand only.
The catalog chunks you mentions exist, e.g., at last08e:/last08e/data/catsHTM/MergedCat/V2/

**Comment by agioffe** [comment]
Do you use the /raid/eran/catsHTM/ collection? 
As far as I understand, Eran produces the 'MergedCat_htm_*" chunks only by himself, so probably, the most up-to-date collection is both on LAST nodes and in ~eran/matlab/data , but the latter is closed for reading.
If the list of missing chunks is not that long, I'd suggest to scp them to the directory you use on _euler_ from
last0:/last0/data2/LAST-CONTAINER/catalogs/MergedCat/V2/

**Comment by EastEriq** [comment]
I don't know what I am using, and I'm concerned about filling euler disks by duplicating unnecessarily extensive data. @EranOfek should chime in.

**Comment by EranOfek** [comment]
This is not related to 'cats' and requires catsHTM, which is available only on euler, and some LAST machines.

However, this is a real bug in the catalog content (it fails on this specific coordinates, while other coordinates works).
Likely because of some 
catsHTM.cone_search('MergedCat',357.22./RAD, -20.55./RAD,10)
Error using hdf5lib2
Unable to open 'MergedCat_htm_680600.hdf5'. File or folder not found.

Error in H5F.open (line 130)
file_id = H5ML.hdf5lib2('H5Fopen', filename, flags, fapl, is_remote);

Error in HDF5.load (line 145)
            FID = H5F.open(FileName);

Error in catsHTM.cone_search (line 1807)
                    C(Iid).Cat = HDF5.load(FileName,DataName).';

**Comment by EranOfek** [comment]
Indeed some MergedCat catalog files are missing on euler (likely from the time we lost the data on euler1).
I am copying the missing data from last01e - will be ready in a few hours.

**Comment by EastEriq** [comment]
ok keep me updated, I'll rerun my pipeline when those files are available

**Comment by EastEriq** [comment]
These are the one I didn't find so far, if it helps:
```
MergedCat_htm_668300.hdf5
MergedCat_htm_675500.hdf5
MergedCat_htm_675600.hdf5
MergedCat_htm_675700.hdf5
MergedCat_htm_675800.hdf5
MergedCat_htm_675900.hdf5
MergedCat_htm_676200.hdf5
MergedCat_htm_676400.hdf5
MergedCat_htm_677000.hdf5
MergedCat_htm_679800.hdf5
MergedCat_htm_680600.hdf5
MergedCat_htm_680700.hdf5
MergedCat_htm_681100.hdf5
MergedCat_htm_681200.hdf5
MergedCat_htm_681500.hdf5
MergedCat_htm_681900.hdf5
```

**Comment by EranOfek** [comment]
copying the files - may take some time.
