### ISSUE TITLE
Adding columns to original AstroCat when using imProc.match.match2solarSystem is limited

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#435]
When giving an AstroCat object to `imProc.match.match2solarSystem`,` imProc.match.match2solarSystem` returns a new catalog with entries from AstroCat that match an asteroid only. If I want to instead update the input AstroCat, then `imProc.match.match2solarSystem` can only do it for the distance to nearest asteroid, no other columns (such as asteroid mag). Adding additional asteroid information to the original AstroCat is thus very awkward. It would be useful if `imProc.match.match2solarSystem` gave the option to update the original AstroCat with further parameters.

**Comment by EranOfek** [comment]
Done.
Two new arguments were added to imProc.match.match2solarSystem:
```
Args.AddMag2Obj                     = false;
Args.ObjColMag                      = 'MagMP';
```

[dev1 71fd9633]
