### ISSUE TITLE
`celestial.Targets.isVisible` for negative HA bug?

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#447]
In `obsByPriority2` I found this comment
```
    % disable bug in Targets.isVisible which can't deal with negative HA,
    % remove line ones that bug is fixed
    T.VisibilityArgs.HALimit=400;
```
what is the current status of it? Was the bug solved?

**Comment by EranOfek** [comment]
I am not aware of any such bug.
Just gave a look into the code and couldn't find evidence for this problem.
Minor updates to help (new version).
[dev1 473c95ac]
