### ISSUE TITLE
Images are wrongly stored or wrongly displayed

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#45]
Images 2 & 4 were written (or displayed?) wrongly, with the first raw starting at raw ~3100, and the bottom of the image starting at zero up to ~3100 (Cyclic shift).
Images:
LAST.01.02.02_20221120.221829.993_clear_125+16_001_001_001_sci_raw_Image_1.fits
LAST.01.02.04_20221120.221830.213_clear_125+16_001_001_001_sci_raw_Image_1.fits

The images on cameras 1 & 3, taken on the same time, were OK.
The following images on cameras 2 & 4, were written OK.

**Comment by EranOfek** [comment]
We need a function that will identify this problem.
How about using Enrico's
imUtil.calib.equaliseLineMean

**Comment by EranOfek** [comment]
Origin unknown.
Closing, but need to watch for this.
