### ISSUE TITLE
Pipeline running time has increased by 200 s

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#453]
From the end of April to the beginning of June the running time of the main part of the pipeline (before anything is being written to disk) has dramatically increased from ~ 340 s up to ~ 540 s. Need to profile and see what is the reason. How could I accurately roll the AstroPack back to the end of April and then forward to the present state to measure and see what has caused it?

**Comment by EastEriq** [comment]
It's `git checkout v2.1` vs. `git checkout HEAD`. For finer control you can checkout a specific commit SHA helping yourself figuring up with the commit messages, they are all "*.m", haha.

BUT

HEAD is more or less necessary for superunit observation, hence if you revert some machines to v2.1 you have to warn observers.
If AstroPack was modular, it would be considerable to checkout different modules at different time snapshots, but as Astropack is now, I think that is hopeless.

**Comment by EranOfek** [comment]
please provide details - e.g., dataset location, and full profiling.

**Comment by EranOfek** [comment]
he is testing it on his machine...

**Comment by agioffe** [comment]
The dataset is the standard visit employed by pipeline's unit test at pipeline.DemonLAST.unitTest:
20 images starting from
LAST.01.08.03_20230616.222625.384

Here are the profiling results (first HEAD, then v. 2.1):
![HEAD](https://github.com/EranOfek/AstroPack/assets/117931420/dffb13e1-ae71-46ef-966f-5c1a981feed9)
![v2 1](https://github.com/EranOfek/AstroPack/assets/117931420/9fde7b41-819e-403c-84af-67d4dcf6b025)

**Comment by EranOfek** [comment]
How can we retrieve this data set? using the Installer?

**Comment by agioffe** [comment]
Yes, this can be installed as 
'LASTpipelineUnitTest'

**Comment by agioffe** [comment]
Changing of 1 flag suggested in https://github.com/EranOfek/AstroPack/issues/454
also cured this issue, with the processing speed of the whole pipeline going back to 380~s total, with all the disk writes and DB interactions.
