### ISSUE TITLE
Would we need to add HISTORY keywords to AstroHeader?

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#457]
Would we consider it useful to add some HISTORY cards to AstroHeaders and also write them into the FITS output (probably, even in another DB column in some cases)? Keeping some processing parameters in the HISTORY records could be useful both within the regular pipeline processing (though it could be coded as pipeline version) but especially for some post-processing and non-standard tasks (e.g., adding objects, merging catalogs, etc.).

Do I take it right that we could just add HISTORY to ~/matlab/AstroPack/config/header.yml or ~/matlab/AstroPack/config/Header.Comments.Default.yml in order to be able to write such a field in an AstroHeader? One issue could be that in the FITS standard one can have many cards with the same HISTORY keyword, but I don't know if we can do the same with AstroHeader. 

@EranOfek @EastEriq , what do you think?

**Comment by EastEriq** [comment]
No idea, on my part. What kind of information should this key contain? If it is not something related to the first step of creation of raw images, I'm not really into it.

**Comment by agioffe** [comment]
Usually such cards contain information on how the current image (or spectrum, or catalog) has been produced from some raw data. In particular, we discussed some time ago that we need to make a mark if the catalog of an AI object was augmented with another catalog of objects when their images were added ("injected") to the image contained in this AI. 

P.S. Here is a short example of how such keywords are written to a FITS header by some Chandra tools:

HISTORY dmextract binning: File EVENTS Col pi Binning 0.5:1024.5:1
HISTORY  TOOL  :dmextract   2024-04-30T09:27:07                         ASC00001
HISTORY  PARM  :infile=29384r/acisf29384_repro_evt2.fits[sky=region(SN24ASC00002
HISTORY  CONT  :ggi_ep2_0001_srcreg.fits)][bin PI]                      ASC00003
HISTORY  PARM  :outfile=SN24ggi_ep2_0001.pi                             ASC00004
HISTORY  PARM  :bkg=                                                    ASC00005
HISTORY  PARM  :error=gaussian                                          ASC00006
HISTORY  PARM  :bkgerror=gaussian                                       ASC00007
HISTORY  PARM  :bkgnorm=1                                               ASC00008
...
HISTORY  TOOL  :dmgroup   2024-04-30T09:27:14                           ASC00037
HISTORY  PARM  :infile=SN24ggi_ep2_0001.pi[SPECTRUM]                    ASC00038
HISTORY  PARM  :outfile=SN24ggi_ep2_0001_grp.pi                         ASC00039
HISTORY  PARM  :grouptype=NUM_CTS                                       ASC00040
HISTORY  PARM  :grouptypeval=15                                         ASC00041

**Comment by EastEriq** [comment]
I see. Since raw image taking is, in my view, a single pass operation, I think I should not be concerned with that in the code I mainly maintain, but please correct me if you see the need. OTOH yes, here and there there are procedure calls which allow some parameters (e.g. the steps of the focus loop), and we have empirically settled for some given value, but if we were to record all of them as HISTORY... Skeptical

**Comment by EranOfek** [comment]
no need at this stage. This is rarely useful.
