### ISSUE TITLE
Can't read images after recent changes

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#462]
Recent changes to tools.cell.isempty_cell make it so I can't read images anymore, code cannot resolve tools.cell.mex.mex_isempty_cell.

```
Unable to resolve the name 'tools.cell.mex.mex_isempty_cell'.

Error in tools.cell.isempty_cell (line 33)
    Flag = tools.cell.mex.mex_isempty_cell(Cell, UseMP);

Error in AstroWCS/read_ctype (line 366)
                    Pair     = Split(~tools.cell.isempty_cell(Split));

Error in AstroWCS.header2wcs (line 1421)
                    Result(Iobj).read_ctype;

Error in AstroImage/populateWCS (line 1708)
                Obj(Iobj).WCS = AstroWCS.header2wcs(Obj(Iobj).HeaderData, Args.header2wcsArgs{:});

Error in AstroImage.readFileNamesObj (line 740)
                Result = populateWCS(Result);

Error in SubtractAndTransearch (line 54)
    New = AstroImage.readFileNamesObj(Coadds, Path = VisitPath);
```

VisitPath = '/marvin/LAST.01.01.01/2024/03/03/proc/194855v0';
Coadds = strcat(VisitPath,'/LAST*coadd_Image_1.fits');

**Comment by EranOfek** [comment]
please check if the directory:
matlab/AstroPack/matlab/util/+tools/+cell/+mex/
contain these 3 files:
mex_isempty_cell.cpp
mex_isempty_cell.mexa64
mex_isempty_cell.mexw64

**Comment by RuslanKonno** [comment]
mex_isempty_cell.mexa64 is missing, I see it's also missing in the github repo

**Comment by RuslanKonno** [comment]
Missing file is now in the repo. I've pulled and can read images again.
