### ISSUE TITLE
Proposed Scheduler changes: 18 July

### ISSUE THREAD

**Issue by param-rekhi** [EranOfek/AstroPack#485]
When the scheduler is run globally (through the superunit), the following modifications have been proposed:
1. Add a 'mount number' field to the scheduler function for each target which indicates the allowed mount(s) used to observe said target.
1.a. The scheduler would then run mount wise, considering only the possible targets for each mount.
2. The 'mount number' field should accept a `nan` value which would indicate any mount is acceptable.
2.a. Note that the priority should be adjusted such that mount `nan` targets do not block mount-specific targets unnecessarily. I think the best way to ensure this would be to let 1-2 mounts not have any mount specific targets, while keeping the mount-specific targets at a higher priority.
3. When inserting new targets, it should be ensured that the 'observation counter' columns for the other targets are untouched, while the new ones init with 0.
4. The Scheduler export function should export the target list in a format compatible with the current.

**Comment by EranOfek** [comment]
1 and 2. done - added a MountNum (default is NaN). column to list., isVisible and selectTarget now accepts a MountNum argument.

**Comment by EranOfek** [comment]
Add static method: read2table
and method: loadTable that can also merge two tables, with/out keeping data from selected columns.
By default it will concat that non-overlapping part of the table, and replace the overlapping parts, with the exception of columns like GlobalCounter,...
