### ISSUE TITLE
Error message when running AI.subtractBackground;

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#486]
running AI.subtractBackground, I got an error shown in the attached snapshot.

The AI was constructed from 9 images after reduction (from proc directories).

The AI was constructed ok (I run on it populateWCS, transIm.imwarp, stack.coadd, background.background, and all was fine).

![Bug_subtractBackground_2024-07-22](https://github.com/user-attachments/assets/3f00050b-ddc7-4653-b98d-bfdb17b0f638)

**Comment by EranOfek** [comment]
Not enogh information.
Please provide full information including images used, how you read them
and the command you executed

**Comment by EranOfek** [comment]
bug fixed.
[dev1 b8dba37fb]
