### ISSUE TITLE
UDPPort warning when using MovingSource.read

### ISSUE THREAD

**Issue by saraylet** [EranOfek/AstroPack#487]
When warnings are turned on, I receive the following error when using MovingSource.read and also when just loading the .mat file manually using MATLAB.

```
Warning: Cannot load an object of class 'UDPPort':
Its class cannot be found. 
```

For example, this happens on a Linux/Ubuntu machine when loading LAST.01.01.01_20240108.193342.366_clear_043+18_101_001_001_sci_merged_Asteroids_1.mat

This may be related to antiquated/unsupported types in MATLAB.

**Comment by EranOfek** [comment]
us this happens with any file you are trying to load? or only with this
specific file?
Is this happening with your new computer? Is it happening on other
computers?
AstroPack doesn't use UDP directly, so its likely an internal matlab
warning.

**Comment by saraylet** [comment]
I receive this warning for every successful MovingSources.read performed on my new Linux machine.

**Comment by EranOfek** [comment]
is it happens also when you try to use the "load" function directly?
It likely related to your new linux machine, did you consult with Amir/Arie?

**Comment by EastEriq** [comment]
class `udpport` has been introduced in matlab 2020b to replace the deprecated `udp`, analogously to `serialport` aiming to replace `serial`. My educated guess is that this file `LAST.01.01.01_20240108.193342.366_clear_043+18_101_001_001_sci_merged_Asteroids_1.mat` embowels one of such objects somehow (I don't want to know how and where), has been saved by a recent Matlab and is being loaded in an older version.

**Comment by EastEriq** [comment]
Users of udp might be your system loggers, what do I know. Many AstroPack classes have a `Logging` property for purposes I prefer not to know, maybe that is the injector

**Comment by EranOfek** [comment]
Thanks Enrico, this may be the answer. I suspect this is related to the
syslog capabilities added by Arie.
Arie - any idea?

**Comment by EranOfek** [comment]
The udpport command is found in a try catch block, so this warning is harmless.
