### ISSUE TITLE
Cannot save MovingSource objects to a MATLAB workspace

### ISSUE THREAD

**Issue by saraylet** [EranOfek/AstroPack#488]
Whenever I try to save a MovingSource object or a struct of MovingSource objects to a workspace in MATLAB, I get errors and/or MATLAB crashes. This is not an issue for saving any other data type. I get the error:

```
Error using save
Unable to save file 'test.mat'. The file could not be closed, and might now be corrupt.

```
For example, if I try to save MP which was generated using

`MP = MovingSource.read(ReadFile, 'Path', Path, 'PopKA', true);`

from the file LAST.01.01.01_20240108.193342.366_clear_043+18_101_001_001_sci_merged_Asteroids_1.mat

In this case, MP is a 1x5 MovingSource object.

**Comment by saraylet** [comment]
Works with saving using -v7.3

**Comment by EranOfek** [comment]
when you open issues, please provide the full command you try to execute
and not only the output.
How did you try to dave the file? using the 'save' command? GUI? 'save
-v7.3'?

See also:
https://www.mathworks.com/matlabcentral/answers/859465-error-in-save-to-mat-file

solution is, likely, to use save -v7.3

**Comment by saraylet** [comment]
Before seeing your reply, I also eventually found that -v7.3, which partially helped. Still having issues probably with trying to save too many at once, even though it’s only 64 for unknown good. Will try breaking it up. Sarah A. Spitzer, Ph.D. (She/Her/Hers)Research FellowUniversity of MichiganSolar and Heliospheric Research GroupDepartment of Climate and Space Sciences & Engineering!!!!! Please DO NOT SEND confidential, export controlled, or otherwise restricted data or files to this email address.  Please contact me to set up a secure file transfer as needed. !!!!!On Jul 22, 2024, at 4:07 PM, Eran Ofek ***@***.***> wrote:﻿
when you open issues, please provide the full command you try to execute

and not only the output.

How did you try to dave the file? using the 'save' command? GUI? 'save

-v7.3'?



See also:

https://www.mathworks.com/matlabcentral/answers/859465-error-in-save-to-mat-file



solution is, likely, to use save -v7.3
