### ISSUE TITLE
Need a way to have Matchedsources class to handle coadd catalogs results 

### ISSUE THREAD

**Issue by simonegarrappa** [EranOfek/AstroPack#490]
Currently,  "_sci_merged_MergedMat_" files are created for single images. In many cases, extracting a light curve from coadd catalogs is more useful (many faint sources are not detected in single exposures), but there is currently no such MergedMat file created for these products. 

Suggested: 
- get MergedMat files by default in the pipeline also for coadd images.

Alternative:
- have some tools to produce them on the fly (offline) when analyzing specific targets/visits.

**Comment by EranOfek** [comment]
To summarize: we will add a method that match the sources in the MargedMad
with a single AstroCatalog and for each found source, extract requested
information from the AstroCatalog object and att it as an entry in the
SrcData property.

**Comment by EranOfek** [comment]
New method available: MatchedSources/match2AstroCatalog
[dev1 3105d71d]
