### ISSUE TITLE
findTransients code improvments

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#491]
in imProc.sources.findTransients
We use the following lines:

0. For variable names, first letter should be upper case.

1.  Re:  BDlnt = BitDictionary('BitMask.Image.Default');
 Make it possible to pass BDInt as an input (via "Args."), or as a char array:
e.g., Args.BitDic    = 'BitMaks.Image.Default';
if isa(Args.BitDic, 'BitDictionary')
    BDInt = Args.BitDic;
else
   BDInt = BitDictionary(Args.BitDic)
end 

2. Re: 

 TranTable.ColUnits = {'','','','',...
            '','','',...
            '','','','',...
            '','','','','','','',...
            '','','','',...
            '','','','',...
            '','','',...
            };

you can use the cell function instead, but in any case I think this can be omitted and it should have no effect.

3.
Re lines of the form:

    Saturated = cell2mat(cellfun(@(c)any(strcmp(c,{'Saturated'})), ...
        BM_new, 'UniformOutput', false));
    Near_Edge = cell2mat(cellfun(@(c)any(strcmp(c,{'NearEdge'})), ...
        BM_new, 'UniformOutput', false));
....

why not using the findBit method (of BitDictionary)?

**Comment by RuslanKonno** [comment]
Ah, actually, do we want to keep this function? It's superseded by AstroDiff and isn't part of the pipeline. If yes, there'll be a lot more changes needed, personally I'd just remove it.

**Comment by EranOfek** [comment]
sure.

**Comment by RuslanKonno** [comment]
Removed
