### ISSUE TITLE
`tools.git.getVersion` works only if astropack is installed in $HOME/matab/AstroPack

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#495]
On my computer, it is not, and the function errors out. You can easily make it work getting the actual installation path using `mfilename()` , i.e. replacing
```
    HomePath = tools.os.get_userhome;

    cd(sprintf('%s%s%s',HomePath,filesep,Args.Path));
```
with
```
cd(fileparts(mfilename('fullpath')));
```
at line 18 in tools.git.getVersion.m. Shall I?

**Comment by EranOfek** [comment]
Fixed as suggested.

**Comment by EranOfek** [comment]
[dev1 314fc0a1]
