### ISSUE TITLE
New header value needed in coadds for effective exposure 

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#499]
For a coadded image, we derive a mean flux with respect to number of coadded images. We track the total exposure time and number of coadds in the header, but not the mean exposure per coadded image. For a visit coadd in LAST we can generally assume 20s per image, but this is not true in the general case and it may also not be true when we stack coadds to deeper coadds. Thus we need information in the header that tells us the exposure to which the flux in the coadd is normalized to.

**Comment by EranOfek** [comment]
In imProc.stack.coadd - the output header now includes 'MEXPTIME' - which is the mean exposure time of all the coadd images.
Note that we stack images more then once this is not enough.

**Comment by EranOfek** [comment]
[dev1 007b8a63]
