### ISSUE TITLE
pipeline.DemonLAST object does not allow to change NewPath once BasePath is changed

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#502]
@EranOfek , @YarinMS :

Here's what I found:

ocs@last05w:~$ matlab -nodisplay
                                                        
AstroPack startup addpath count: 35
AstroPack startup done: /home/ocs/matlab/AstroPack/matlab/startup/startup
>> 
>> D = pipeline.DemonLAST;
>> D.BasePath ='/last05w/data2/archive/LAST.01.05.04'

D = 

  DemonLAST with properties:

             CI: [1x1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 1
      CamNumber: []
       HostName: []
       BasePath: '/last05w/data2/archive/LAST.01.05.04'
        NewPath: '/last05w/data2/archive/LAST.01.05.04/new'
      CalibPath: '/last05w/data2/archive/LAST.01.05.04/calib'
     FailedPath: '/last05w/data2/archive/LAST.01.05.04/failed'
        LogPath: '/last05w/data2/archive/LAST.01.05.04/log'
        RefPath: '/last05w/data/references'
         ObsCoo: [35 30 415]
       UserData: []

>> D.NewPath = '/last05w/data2/archive/LAST.01.05.04/new1'

D = 

  DemonLAST with properties:

             CI: [1x1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 1
      CamNumber: []
       HostName: []
       BasePath: '/last05w/data2/archive/LAST.01.05.04'
        NewPath: '/last05w/data2/archive/LAST.01.05.04/new'
      CalibPath: '/last05w/data2/archive/LAST.01.05.04/calib'
     FailedPath: '/last05w/data2/archive/LAST.01.05.04/failed'
        LogPath: '/last05w/data2/archive/LAST.01.05.04/log'
        RefPath: '/last05w/data/references'
         ObsCoo: [35 30 415]
       UserData: []

>> 

NB: If I don't change the BasePath, I am able to change the NewPath successfully.

**Comment by EranOfek** [comment]
Can you explain exactly how you tried to modify the dir name?
Did you use:
D.NewPath = 'new1'
or
D.NewPath = '/<fullpath>/new1'

Note that the first option will not work. You must provide the full path.

**Comment by agioffe** [comment]
You can see above that I used
D.NewPath = '/last05w/data2/archive/LAST.01.05.04/new1'
i.e., the full path.

**Comment by agioffe** [comment]
This way it does not update as well:

D.setPath('/Data1/AstroPackData/pipeline/LAST/','NewPath','/Data1/AstroPackData/pipeline/LAST/2023/06/16/raw/')

ans = 

  DemonLAST with properties:

             CI: [1×1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 1
      CamNumber: []
       HostName: []
       BasePath: '/Data1/AstroPackData/pipeline/LAST/'
        NewPath: '/Data1/AstroPackData/pipeline/LAST/new'
      CalibPath: '/Data1/AstroPackData/pipeline/LAST/calib'
     FailedPath: '/Data1/AstroPackData/pipeline/LAST/failed'
        LogPath: '/Data1/AstroPackData/pipeline/LAST/log'
        RefPath: '/WRX80/data/references'
         ObsCoo: [35 30 415]
       UserData: []
>> 

I suppose the issue is in the hidden property
DefNewPath      = 'new';

**Comment by EranOfek** [comment]
I can't reproduce this problem - here is what i do and get:
D=pipeline.DemonLAST

D =

  DemonLAST with properties:

             CI: [1x1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 1
      CamNumber: []
       HostName: []
       BasePath: '/last01e/data1/archive/LAST.01.01.01'
        NewPath: '/last01e/data1/archive/LAST.01.01.01/new'
      CalibPath: '/last01e/data1/archive/LAST.01.01.01/calib'
     FailedPath: '/last01e/data1/archive/LAST.01.01.01/failed'
        LogPath: '/last01e/data1/archive/LAST.01.01.01/log'
        RefPath: '/euler/data/references'
         ObsCoo: [35 30 415]
       UserData: []

>> D.NewPath='/last01e/data1/archive/LAST.01.01.01/new1';
>> D

D =

  DemonLAST with properties:

             CI: [1x1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 1
      CamNumber: []
       HostName: []
       BasePath: '/last01e/data1/archive/LAST.01.01.01'
        NewPath: '/last01e/data1/archive/LAST.01.01.01/new1'
      CalibPath: '/last01e/data1/archive/LAST.01.01.01/calib'
     FailedPath: '/last01e/data1/archive/LAST.01.01.01/failed'
        LogPath: '/last01e/data1/archive/LAST.01.01.01/log'
        RefPath: '/euler/data/references'
         ObsCoo: [35 30 415]
       UserData: []

**Comment by agioffe** [comment]
This is because you do not change the BasePath after you create the object. Once you do
D.BasePath = '\somepath';
you won't be able to change the NewPath any more.

**Comment by agioffe** [comment]
The conclusion is that one must either use BasePath (and then all the names are standard), or not touch it at all (if one of the subdir names need to be non-standard). One way to deal with it is to set
D.BasePath = [];
before introducing changes to one of the subdir names.
