### ISSUE TITLE
 incorrect barycentric velocity in the outputs of celestial.time.barycentricJD

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#504]
At comparison of the outputs of celestial.time.barycentricJD with reference calculations from here:
https://astroutils.astronomy.osu.edu/time/utc2bjd.html
showed discrepancy at ~ km/s level for the following parameters:
JD = celestial.time.date2jd([2010 08 01 10 30 0]);
[BJD, BVel] = celestial.time.barycentricJD(JD,180,-20,'CooUnits','deg','InTimeScale','UTC','VelOutUnits','km/s','GeoPos',[0,0,0]);

**Comment by agioffe** [comment]
@EranOfek found a bug (wrong dimension), now the discrepancy is < 1 cm/s.

**Comment by EranOfek** [comment]
In: celestial.coo.topocentricVector - unit conversion and transformation
bug fix in Gdot
