### ISSUE TITLE
celestial.time.tt_utc for the dates in the near past 

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#505]
To calculate the BJD time for a particular sky object and time we employ
**celestial.time.barycentricJD** which calls **celestial.time.tt_utc** to calculate the TT-UTC shift.
In turn, **celestial.time.tt_utc** employs **celestial.time.ut1_tai** to get the UT1-TAI shift.
These shifts are read from the tables downloaded from the IERS service (see https://hpiers.obspm.fr/eoppc/bul/bulb/explanatory.html),
namely, the _EOP_C01_IAU2000_1846-now.txt_ text table. These tables are updated once a month, so today (14.10.2024) they are full only 30.09.2024. Hence, with
> JD = celestial.time.date2jd([2024 10 09 10 30 0]);
> [UT1mTAI, ~] = celestial.time.ut1_tai(JD) 
gives NaN, while with
> JD = celestial.time.date2jd([2024 09 30 15 00 00]); 
> [UT1mTAI, ~] = celestial.time.ut1_tai(JD) 
gives -36.9274
Now the **celestial.time.tt_utc** has an option to take two more dates, 30 and 60 days before the requested JD, and make a linear extrapolation into the future instead of calculating the TT-UTC directly from the relevant UT1-TAI (for the requested JD). 

So we need to choose between two options:
1) In **celestial.time.barycentricJD** call **celestial.time.tt_utc** with ('NearFutureInterp',true) every time when JDnow-JD < 31 or 32 days
2) In **celestial.time.tt_utc** call [UT1mTAI, ~] = celestial.time.ut1_tai(JD) and if UT1mTAI == NaN, switch to extrapolation. 

Also, the  _EOP_C01_IAU2000_1846-now.txt_ table should be updated on every data processing machine at the 2nd-3rd day of each month (see, e.g. https://datacenter.iers.org/calendar.php?id=186#thismonth). However, it is not clear which function should be responsible for the update (e.g. **pipeline.DemonLAST**?)

@EranOfek , what do you think?

**Comment by EranOfek** [comment]
good!
1. In: celestial.time.tt_utc - I know check if the interpolation is larger
than 60 days relative to now - if this is the case, then I issue a warning.
The user is still responsible to get update the file.
2. In the startup file I am now checking how old are the IERS files and
downloading new versions if needed (this may take ~30 s).

**Comment by agioffe** [comment]
Thank you, Eran!
1. It is good that **celestial.time.tt_utc** now knows to warn the user if the extrapolation is too long, but we still need to decide where and how to call this function with the extrapolation flag (option 1 or option 2). 
2. In regards of downloading a new table at startup: what if I have the same matlab session open for a month or more? Not that I can suggest a good solution, but probably, it is indeed worth making another check at every run of the pipeline (however, a production pipeline can also run within a month or more without a restart..). Moreover, [here](https://datacenter.iers.org/calendar.php?id=186&year=2024&month=10&view=1) we can see that sometimes they don't update the table for much more than a month, and sometimes -- twice a month.

**Comment by EranOfek** [comment]
changed the default extrapolation true.
re point 2, in principle, we can have open a singelton installer class in
the "base", and add a timer object that download the Time table every 30
days..., but not sure I want to do this.

**Comment by agioffe** [comment]
It looks like the default extrapolation=true that you set actually leads to non-optimal results, because now the function extrapolates the values from just the two points [now-30,now-60] **both** forward and backward for any set of input JD values. 

Hence, I suggest to change the code so that instead
```
UT1mTAI =interp1(JDnear, UT1mTAI(1:2), JD, 'linear', 'extrap');
UT1mUTC =interp1(JDnear, UT1mUTC(1:2), JD, 'linear', 'extrap');
```
in lines 45-46 there is
```
Ind = JD > JDnear(2);
UT1mTAI(Ind) =interp1(JDnear, UT1mTAI(1:2), JD(Ind), 'linear', 'extrap');
UT1mUTC(Ind) =interp1(JDnear, UT1mUTC(1:2), JD(Ind), 'linear', 'extrap');
UT1mTAI(1:2) = []; UT1mUTC(1:2) = [];
```
so that we extrapolate or interpolate for only the JDs of last 2 months or in the future, but keep the real table values for those in the past. 

@EranOfek, do you agree?

**Comment by EranOfek** [comment]
yes - please proceed
