### ISSUE TITLE
`telescope.Scheduler`: wrong bookkeeping of targets already assigned to other mounts?

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#510]
Example run, abridged. Targets are requested by `Unit.observeList('SimulationJD',celestial.time.julday)` running on several mounts. This causes requests every 15 secs or so. Mount 4 was the first one ready:
```
>> telescope.Scheduler.demon
selecting target for mount 4, JD=2460614.239775
17:45:17.018 [INF] Mount=  4  Target =                 1397  RA=357.662338  Dec= 33.000000 Priority=  0.10  Nexp= 20 ExpTime= 20.0
selecting target for mount 4, JD=2460614.240091
17:45:44.430 [INF] Mount=  4  Target =                 1320  RA=357.777778  Dec= 27.000000 Priority=  0.10  Nexp= 20 ExpTime= 20.0
selecting target for mount 4, JD=2460614.240296
17:46:02.057 [INF] Mount=  4  Target =                 1469  RA=357.500000  Dec= 39.000000 Priority=  0.10  Nexp= 20 ExpTime= 20.0
selecting target for mount 4, JD=2460614.240513
17:46:20.749 [INF] Mount=  4  Target =                 1239  RA=357.857143  Dec= 21.000000 Priority=  0.10  Nexp= 20 ExpTime= 20.0
selecting target for mount 2, JD=2460614.240578
```
at this point a new request comes in from mount 2. At line 1810 JD is checked against LastJD of *all* fields, and as can be checked setting a breakpoint,
```
K>> find(LastJD>0)

ans =

        1239
        1320
        1397
        1469
```
and
```
K>> JD-LastJD(find(LastJD>0))

ans =

  -0.00075439
  -0.00033285
   -1.429e-05
  -0.00053805
```
This produces the error at line 1811
```
Error using telescope.Scheduler/weight (line 1811)
JD must be larger then LastJD

Error in telescope.Scheduler/selectTarget (line 1731)
            W   = Obj.weight(JD);

Error in telescope.Scheduler/serviceTargetRequests (line 945)
                [TargetInd, Priority, Tbl, Struct] = S.selectTarget(JD,...

Error in telescope.Scheduler.demon (line 1039)
                S.serviceTargetRequests('ToO_File',Args.ToO_File,...
```
However, is the test the right one? What is the problem with other targets which have already been assigned at times posterior to this request? (the new request may for some reason have come in late) Shouldn't we just look at targets which either have LastJD==0, or have an old enough LastJD, to choose candidates for the next target?

**Comment by EranOfek** [comment]
If I understand correctly:
in real life JD>LastJD (always), and therefore this is the correct test.
The fact that you get JD<LastJD, means either:
1. Bug in the scheduler.
2. You are not sending the correct JD to the scheduler.

LastJD is updated in the table by the increaseCounter function.
How do you calculate the value of LastJD in the simulation mode?

**Comment by EastEriq** [comment]
will debug more tomorrow

**Comment by EranOfek** [comment]
Can we close this one?

**Comment by EastEriq** [comment]
Not yet sure - the moment I'll see the scheduler demon working fine in dry and wet mode on several units I'll tell

**Comment by EastEriq** [comment]
Let's close it for now.

**Comment by EastEriq** [comment]
```
09:47:38.963 [INF] Mount=  8  Target =                  326  RA= 52.500000  Dec=-39.000000 Priority=  1.10  Nexp= 20 ExpTime= 20.0
09:47:57.146 [INF] selecting target for mount 3, requested at JD=2460625.408298, now 2460625.908300
09:47:57.779 [INF] Mount=  3  Target =                  474  RA= 42.222222  Dec=-27.000000 Priority=  1.10  Nexp= 20 ExpTime= 20.0
09:47:58.366 [INF] selecting target for mount 2, requested at JD=2460625.408298, now 2460625.908314
Error using telescope.Scheduler/weight (line 1875)
JD must be larger then LastJD

Error in telescope.Scheduler/selectTarget (line 1795)
            W   = Obj.weight(JD);

Error in telescope.Scheduler/serviceTargetRequests (line 980)
                [TargetInd, Priority, Tbl, Struct] = S.selectTarget(JD,...

Error in telescope.Scheduler.demon (line 1099)
                S.serviceTargetRequests('ToO_File',Args.ToO_File,...
```
Requests serviced out of order (or with equal JD truncated to the 6th figure) have a certain probability of happening.  I'll go for the quick and dirty solution of try-catching the failed dispatch, and letting the Unit ask again.

**Comment by EranOfek** [comment]
I guess the target file is corrupted.
