### ISSUE TITLE
value-lock in imUtil.psf.fwhm_fromBank

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#511]
Judging from what is seen when computing FWHM of the observed images, which is done with `imUtil.psf.fwhm_fromBank(Image, 'HalfSize',1000)`, the results show recurring values, hinting at a possible nonuniform distribution. For instance the values (rounded at two decimals) 2.81, 3.13, 3.49 are particularly frequent. In PIV parlancy, this phenomenon is called pixel-locking, and is caused by biased estimations of the subpixel position of the autocorrelation peak. Are you sure that something similar is not happening here too?
For the purpose of a coarse estimation of the seeing or of the goodness of focus we can probably live with it, but are you using the function anywhere else in the pipeline, e.g. in PSF estimations? Are there any risks that the bias is propagated, for instance, to photometry?

**Comment by EranOfek** [comment]
This is simply due to the resolution of the search (which is a kind of
binary-search using a template-bank with up to five levels).
I am considering some changes.

**Comment by EranOfek** [comment]
This function is used only for focus.
Added a new function that should be used far from focus:
imUtil.psf.fwhm_fromACF

**Comment by EastEriq** [comment]
No you don't get the point. `imUtil.psf.fwhm_fromBank` is used to get the seeing. It appears to give biased values, and that has no relation with the focus routine. You may say that it is a bias you can live with, but is present.

**Comment by EranOfek** [comment]
imUtil.psf.fwhm_fromBank is used only by the focus routine - it implements one method (out of several possible methods).
If you want to avoid the discretization, all you need to do is to increase the number of iterations. However, this is not very interesting, as getting results to the level of 0.1" is more than enough.
imUtil.psf.fwhm_fromACF is another function, and soon I will write at least one more function (fwhm_fromMoments). At the end we will use the best functions...

**Comment by EastEriq** [comment]
As a matter of fact `imUtil.psf.fwhm_fromBank` is used to display the datum as FWHM in the monitor. If you say that this is not really to be interpreted as seeing, be that. Perhaps the users should be made aware of it.

**Comment by EranOfek** [comment]
It is an estimate of the seeing. Providing a value more accurate than 0.1
arcsec is meaningless, so the value locking is not an issue.
