### ISSUE TITLE
error imUtil.psf.fwhm_fromACF with a completely saturated image

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#518]
This happens with an image whose values are all 65534 except for those in the overscan coulmns. A corner case, but can happen while attempting to focus (imagine that a light has been forgotten on in the observatory). It should be handled.
```
Error using matlab.internal.math.interp1
The sample points must be finite.

Error in interp1 (line 188)
        VqLite = matlab.internal.math.interp1(X,V,method,method,Xqcol);

Error in imUtil.psf.fwhm_fromACF (line 74)
    FWHM = interp1(CumVal, Rad, Args.CorrFrac);

Error in focus_search>blockingExposure (line 251)
    FWHM_ACF = imUtil.psf.fwhm_fromACF(CameraObj.LastImage);

```

**Comment by EranOfek** [comment]
Added saturation treatment.
Also return: Result.Status indicating if not saturated.
[dev1 01f0f16f0]

**Comment by EastEriq** [comment]
Ah, it happens also for a nonsaturated noisy image

**Comment by EastEriq** [comment]
```
>> imUtil.psf.fwhm_fromACF(1000*rand(1000,1000))
Error using matlab.internal.math.interp1
The sample points must be finite.

Error in interp1 (line 188)
        VqLite = matlab.internal.math.interp1(X,V,method,method,Xqcol);

Error in imUtil.psf.fwhm_fromACF (line 74)
    FWHM = interp1(CumVal, Rad, Args.CorrFrac);
```
and here you have no excuse of "but this is not an astronomical image".

**Comment by EranOfek** [comment]
Now also check that the ACF radial profile is ok.
[dev1 44d0c8b3e]

**Comment by EastEriq** [comment]
going through now, i.e. not throwing error for non astronomical images. I close for now, will open a separate issue if I find other problems when I'll shoot at the sky.
