### ISSUE TITLE
`tools.math.fit.ransacLinearModel` errors if it receives no points

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#519]
and this can happen in the focus loop. It's a pathological situation, so I'll try catch it, but maybe you want to make the function more robust to such calls.
```
>> tools.math.fit.ransacLinearModel([],[])
Error using randi
First input must be a positive scalar integer value IMAX, or two integer values
[IMIN IMAX] with IMIN less than or equal to IMAX.

Error in tools.math.fit.ransacLinearModel (line 53)
        IndRand = randi([1 Npt], NptSim, 1);
```

**Comment by EranOfek** [comment]
I added a comment to the help that H can't be empty.
This should be checked by the upper level, and in this case, it make sense that the focus code will check this.

**Comment by EranOfek** [comment]
from your point of view what should be the function output in this case?

**Comment by EastEriq** [comment]
Agree with what you wrote above. For anomalous cases you could eventually output []; it's difficult for me now what could be best in use cases different than the focus routine. If I come up with ideas I'll let you know.

**Comment by EranOfek** [comment]
Modify it such that if H=[], then all the outputs will be [].
[dev1 b3234207d]
