### ISSUE TITLE
field in filename as RA larger than 360deg

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#52]
100 files taken on 20221103 have an RA larger than 360 in their target id

/last02e/data1/archive/LAST.01.02.01/2022/11/03/raw/LAST.01.02.01_20221103.191257.641_clear_416+16_091_001_001_sci_raw_Image_1.fits

In the header the coordinates are:
RA      =     56.9613410921575 /                                                
DEC     =     17.8325354742095 /

**Comment by EastEriq** [comment]
Seems to be an Astropack thing. FIELDID is set by AstroPack/matlab/image/+imProc/+stack/coadd.m, reading `FieldId`, probably from here (?)
https://github.com/EranOfek/AstroPack/blob/dev1/matlab/util/%2Bdb/draft/%40ImagePathDb/ImagePathDb.m

Complicate.

**Comment by EastEriq** [comment]
It comes actually from https://github.com/PolishookDavid/LAST_OCS/blob/9f53d3f5dc9d2fa68a1994247e7c6f8bb359e55c/%2Bobs/%40mount/j2000.m#L30, i.e. `celestial.coo.convert2equatorial()`. I could correct it downstream, for instance in https://github.com/PolishookDavid/LAST_OCS/blob/9f53d3f5dc9d2fa68a1994247e7c6f8bb359e55c/%2Bobs/%40unitCS/takeExposure.m#L72 or better in https://github.com/PolishookDavid/LAST_OCS/blob/9f53d3f5dc9d2fa68a1994247e7c6f8bb359e55c/%2Bobs/%40mount/j2000.m#L34

**Comment by EastEriq** [comment]
I note the following, though, on one image taken with the mount at park position:
```
M_RA    =     137.676774362084 /                                                
M_DEC   =     29.9862653017044 /                                                
M_HA    =     179.997360788988 /                                                
M_JRA   =     497.335860740408 /                                                
M_JDEC  =     30.0503529636136 /                                                
M_JHA   =    -179.658553934127 /                                                
RA      =     137.335860740408 /                                                
DEC     =     30.0503529636136 /                                                
HA      =    -179.661725589336 /                                                
```
It could be a decision whether to keep M_JRA>360

**Comment by EranOfek** [comment]
I added
DistRA = mod(DistRA,2.*pi);
in convert2equatorial.
