### ISSUE TITLE
imProc.db.generateImageID: old LAST coadds lead to error due to lack of some keywords

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#523]
Some of the old LAST coadds, e.g. /mnt/marvin/LAST.01.01.01/2023/04/24/proc/185438v0/*coadd*Ima*fits, do not contain neither "NODENUMB" nor "MOUNTNUM" keywords in the header, which leads to an error in **imProc.db.generateImageID** if it is run with
'ErrorOnNaN' = true (default). 
Hence, there is a question how to correct it without influencing all the images during a bulk processing.

**Comment by EastEriq** [comment]
I think that these keys were added at some point in the raw images, with minimal research I could find out exactly with which commit of LAST_OCS if that is relevant.
Anyway, the easiest solution seem to me to set NODENUMB=1 and derive MOUNTNUM from the file location, i.e. /LAST.01.**01**.01/

**Comment by EranOfek** [comment]
A function that correct a user defined set of keywords will be useful - add
it to the FITS class.

**Comment by agioffe** [comment]
OK, added it to my plan.

**Comment by agioffe** [comment]
I wrote such a function by the name **FITS.correctHeaders** , but there is still a safety issue: do we wish it to overwrite the existing keyword values? By now, I set the 'Overwrite' flag and made it false by default.

**Comment by EranOfek** [comment]
Add the following options:
ChecIfKeyExist default true.
If true the lookk for eack key and if exist then fo nothing.
If false, then override the vslue even if exist.

Rhe msin input can be a struct array:
KeysStruct.KeyName - key name
KeyStruct.Val - value or fun handle that generate the value. The fun is of
the form: fun(filename,header)

**Comment by agioffe** [comment]
OK, I coded it this way and tested it with another new function (a wrapper), **pipeline.last.correctFITShead**, on COADD image files of a local copy of some of the LAST PROC catalogs from Marvin (10 catalogs, 1 night of 1 node). 

Do you think it would be safe to run it on the whole LAST archive, node by node, with 'CheckKeyExist' = true? 
I would start with COADD image files only, and later would come back to correct other FITS products, i.e., the source catalogs.

**Comment by EranOfek** [comment]
If the test was successful (on a few different cases) then this is ok...
make sure that you were able to open the files after modification...

**Comment by agioffe** [comment]
After some more tests I ran the new function **pipeline.last.insertArchive2DB** on /mnt/marvin/LAST01.01.01/2023/ .
Please, have a look at the DB table _visit_images_ at _socsrv_ (if you lack the credentials, I'll send them in a separate way) in order to check once more if the DB entries look normal. If you find it OK, I will run the function on the whole volume of LAST data on Marvin. 
P.S. Probably, it is not the function's location is not optimal, but I couldn't think of a better one. If you'd wish to rename or move it somewhere, I'll do it with ease.

**Comment by EranOfek** [comment]
re function name - location is ok, if this function treats only images (not
sources) then I suggest that the name will say this.

**Comment by agioffe** [comment]
Currently the function treats only images, but I was intending to extend its functionality to catalogs as soon as Chen finishes his part of work and we test catalog injection.

**Comment by EranOfek** [comment]
suggest to separate it to two functions - one for images and one for sources

**Comment by agioffe** [comment]
OK, I renamed it to **pipeline.last.insertArchiveImages2DB** . Please, tell me if you had the time to look into the _visit_images_ table at **socsrv**. If you find it ok, I will proceed with data injection.

**Comment by EranOfek** [comment]
I executed the following:
```
% LAST example:
D=db.Db;
D.Password = <>
D.Conn;
D.useDB('ast');
D.showCurrentDB
D.showTables
T=D.query("SELECT * FROM last.visit_images;");
```

Issues:
* T.id_* are stored in double format, while they should be in int64.
* T.temp_* (including T.temp_mnt) are 0 - any idea why? If they are zero in headers, then need to open an issue about it in LAST_issues.
* T.lst are all zeros.
* why only m_jra and m_jdec are available?

**Comment by agioffe** [comment]
* **id**s are seen as _int64_ in the DataGrip, so they are stored in the right format, and this is an issue of the query function, and not of the DB itself; I will look into it
* **temp_mnt** is erroneously written in the XLS template as **temp_mmt**, that's why it is 0; I will rename it in the table and change the template; actually, this value is present in the **mnttemp** column
* **lst** needs some investigation
* for LAST _visit images_ only **m_jra** and **m_jdec** are marked with 1 in the XLS template; would you like to change it?

**Comment by EranOfek** [comment]
I modified the XLS to include the missing m_* ra/dec/ha coordinates.

**Comment by agioffe** [comment]
Good! Meanwhile, in regards of **lst** I found that the corresponding field in the _header_col_name_ column of the template was empty, and that was the reason this k/w did not come into the output structure; fixed it.

**Comment by agioffe** [comment]
Chen recreated the tables according to the updated template. I checked the injector and the produces DB records and started filling the visit_images table from Marvin once again. Please, have a look at the table being filled and tell me if you see any anomalies.
