### ISSUE TITLE
AstroFilename.genFile FileType separator

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#525]
I do not succeed in building a file name with AstroFilename.genFile, because it does not separate file extension by dot (.), but rather by underscore (_):
K>> A

A = 

  AstroFileName with properties:

                   ProjName: "LAST.01.01.01"
                       Time: "20241102.001215.532"
                         JD: 2.4606e+06
                     Filter: "clear"
                    FieldID: "1244"
                    Counter: "000"
                      CCDID: "001"
                     CropID: "000"
                       Type: "sci"
                      Level: "coadd"
                    Product: "Image"
                    Version: "1"
                   FileType: "csv"
                     SubDir: '001225v0'
                   BasePath: "/marvin"
                BasePathRef: "/marvin/ref"
                       Path: []
    BasePathIncludeProjName: 1
                  AddSubDir: 1
                   TimeZone: 2
                   UserData: []

K>> A.genFile

ans = 

    "LAST.01.01.01_20241102.001215.532_clear_1244_000_001_000_sci_coadd_Image_1_csv"

instead of "LAST.01.01.01_20241102.001215.532_clear_1244_000_001_000_sci_coadd_Image_1.csv"

**Comment by EranOfek** [comment]
Bug fixed in AstroFileName/genFile.
[dev1 287a6b5f3]
