### ISSUE TITLE
Scheduler: BasePriority not used?

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#526]
The priority of a target is given by the function `telescope.Scheduler.weight`. However, it only uses Obj.List.Catalog.BasePriority when the night counter is equal to or greater than the max night counter

lines 1907-1909
```
MaxNC = Obj.List.Catalog.MaxNightN;
FlagNC = NightCounter>=MaxNC;
W(FlagNC) = Obj.List.Catalog.BasePriority(FlagNC);
```
So BasePriority only matters when a target meets this criteria and otherwise all targets have the same base priority set in `telescope.Scheduler.fermiExpWeight` at line 2321

```
W = Ones;
```

When I run the scheduler with e.g. 

```
S=telescope.Scheduler
S.loadTable('/home/ocs/Scheduler/ObservationSchedule.csv','replace')
S.loadTable('/home/ocs/ToOs/output/ToO.csv','merge_replace')
[TargetInd, Priority, Tbl, Struct] = S.selectTarget(2460633.16,'MountNum',3, 'SelectMethod','minam')
```

then the scheduler does not return the target with the highest BasePriority since the `telescope.Scheduler.weight` sets the priority of all targets to 1 or 1.1 (1.1 comes from line 1917).

I see on line 1911

```
%W = W + Obj.List.Catalog.BasePriority;
```

that BasePriority was added but the line has been commented out.

**Comment by EranOfek** [comment]
fixed.
[dev1 4d7b6de6f]
but please test it, and if it is ok you close the issue.

**Comment by RuslanKonno** [comment]
From a quick test selectTarget now provides highest priority target.
