### ISSUE TITLE
Scheduler: telescope.Scheduler.weight uses current JD for hour angle instead of given JD

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#527]
`telescope.Scheduler.weight` on lines 1915-1917

```
            HA_Day  = Obj.HA./360;  % [day]
            Flag_HA = HA_Day> Obj.List.Catalog.MinHA1 & HA_Day<Obj.List.Catalog.MaxHA1 & Obj.List.Catalog.NightCounter==0;
            W(Flag_HA) = W(Flag_HA) + Obj.List.Catalog.ExtraPriorityHA(Flag_HA);
```

checks to see if a target is being observed for the first time during the night. If yes, it increases its priority. However, when giving a custom JD for e.g. simulation purposes, the hour angle `HA_Day` is not adjusted for the simulated time and is equal to current time retrieved from the `Obj.HA` getter.

**Comment by EranOfek** [comment]
You are right, and it seems that the instructions I gave you and Enrico
before were incorrect.

I just noticed, that the correct way to run simulations is the following:

S = telescope.Scheduler;
1. set:    S.UseRealTime = false;
2. In each step of the simulation set: S.JD to simulated JD...
3. when you call selectTarget (or any other function) provide it with an
empty JD.

The UseRealTime=false, means that the JD property is not updated from the
clock every time you need it, instead it is provided by the user and all
functions use it.

**Comment by EastEriq** [comment]
Yeah, and `telescope.Scheduler.demon`? So far I assumed that it had to be agnostic to time, and that simulated requests had only to be handled according to the simulated time written in the request posted. What you write above contradicts it, and means that for simulated requests mode also the demon has to be started with a special parameter which forces `S.UseRealTime = false`. Anything else?

**Comment by EastEriq** [comment]
Including, among the rest, https://github.com/EranOfek/AstroPack/blob/4d7b6de6f4c5dda4792d649f9aea09ae5004c9ab/matlab/astro/%2Btelescope/%40Scheduler/Scheduler.m#L993-L997 ff.

**Comment by EranOfek** [comment]
S.UseRealTime = false
and also
S.JD = value, when ever the simulator time changes.

**Comment by EastEriq** [comment]
We have two options for running the whole target dispatching mechanism and at the same time allow testing. I can't figure out which is the less confusing. Both require proper bookkeeping of what is done.
1. start the demon in a special simulation mode, leave the unit request as they are even when they provide a simulated time
2. no special simulation mode passed at the demon, but an additional flag to the request posted in the mailbox. `telescope.Scheduler.serviceTargetRequests` reads this flag and acts accordingly.

Where both fall is the whether the persistence file `TargetList.mat` is updated or not, and we're back to #516.
Why don't you solve it, this time?

3. abolish simulation mode.

**Comment by EranOfek** [comment]
option #2 sounds good

**Comment by EastEriq** [comment]
236faaf21 good luck debugging it

**Comment by EastEriq** [comment]
LIKE I SAID
```
>> S.send("Unit.observeAskingTargets('NoHardware',true,'SimulationJD',celestial.time.julday+0.5)",u)
```
```
>> telescope.Scheduler.demon
14:43:40.550 [INF] selecting target for mount 1, requested at JD=2460634.613656, now 2460634.113664
Error using  + 
Matrix dimensions must agree.

Error in telescope.Scheduler/timeSinceSunSet (line 1663)
            VecJD = JD+(-1:0.005:1).';

Error in telescope.Scheduler/isNewNight (line 1737)
            TimeSinceLastSunSet = Obj.timeSinceSunSet(JD);

Error in telescope.Scheduler/initNightCounter (line 1764)
                InitC = Obj.isNewNight;

Error in telescope.Scheduler/serviceTargetRequests (line 1020)
                S.initNightCounter(false);

Error in telescope.Scheduler.demon (line 1149)
                S.serviceTargetRequests('ToO_File',Args.ToO_File,... 
```

**Comment by EranOfek** [comment]
main bug reported in this ticket (i.e., weight uses HA with current JD
instead of user-provided JD) is now fixed.
If this is ok, please close this issue.

**Comment by EranOfek** [comment]
fixed by using computer time.
[dev1 31b4488b8]

**Comment by EastEriq** [comment]
So now I get
```
>> telescope.Scheduler.demon('TargetList','~/Scheduler/ObservationSchedule.csv')
14:28:31.149 [INF] selecting target for mount 1, requested at JD=2460635.603135, now 2460635.103138
14:28:31.178 [ERR] Undefined function 'getHA' for input arguments of type 'double'.
14:28:31.241 [WRN] No target for unit 1 at this time
14:28:41.970 [INF] selecting target for mount 5, requested at JD=2460635.603146, now 2460635.103264
14:28:42.004 [ERR] Undefined function 'getHA' for input arguments of type 'double'.
14:28:42.029 [WRN] No target for unit 5 at this time
14:28:42.224 [INF] selecting target for mount 6, requested at JD=2460635.603147, now 2460635.103266
14:28:42.251 [ERR] Undefined function 'getHA' for input arguments of type 'double'.
```
Logging [ERR] comes from https://github.com/EranOfek/AstroPack/blob/31b4488b8eed4574d5fc8550b9ac88ee8e08f874/matlab/astro/%2Btelescope/%40Scheduler/Scheduler.m#L1023-L1032, the error possibly introduced by 99f2b4c1f04cdfa4293a06469e559ad897e415d6. Debugging, again.

**Comment by EastEriq** [comment]
Probably solved by the commit above
