### ISSUE TITLE
implement mount obstruction constraints in Scheduler

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#530]
Copying here Eran's message, to have traceable progress:

>Hi Enrico,

>The telescope scheduler class now takes into account the individual mount altitude constraints due to telescope-to-telescope and wall obstruction (assuming all walls are lowered).

>To use it:
>1. Copy:
euler:/home/eran/work/LAST/obstraction/MountConst*.txt
to the scheduler directory in last0.
>2. In your script that brings up the demon, after you construct the scheduler object add the following lines:

>% load and use individual mount altitude constraints due to obstractions
```
PathMC = '/home/last0/Scheduler';  % modify to the scheduler dir...
CMC = tools.cell.sprintf2cell('MountConst%d.txt',(1:1:12)');
S.populateMountAltConstraints(CMC,PathMC);
```

>Thanks,
Eran

**Comment by EastEriq** [comment]
```
enrico@euler:~$ cd /home/eran/work
-bash: cd: /home/eran/work: Permission denied
```
Can you attach the files here?

**Comment by EranOfek** [comment]
Mounts constraints files attached:

[MountConst2.txt](https://github.com/user-attachments/files/17870829/MountConst2.txt)
[MountConst1.txt](https://github.com/user-attachments/files/17870830/MountConst1.txt)
[MountConst12.txt](https://github.com/user-attachments/files/17870812/MountConst12.txt)
[MountConst3.txt](https://github.com/user-attachments/files/17870826/MountConst3.txt)
[MountConst6.txt](https://github.com/user-attachments/files/17870822/MountConst6.txt)
[MountConst4.txt](https://github.com/user-attachments/files/17870824/MountConst4.txt)
[MountConst5.txt](https://github.com/user-attachments/files/17870823/MountConst5.txt)
[MountConst11.txt](https://github.com/user-attachments/files/17870813/MountConst11.txt)
[MountConst10.txt](https://github.com/user-attachments/files/17870814/MountConst10.txt)
[MountConst9.txt](https://github.com/user-attachments/files/17870815/MountConst9.txt)
[MountConst8.txt](https://github.com/user-attachments/files/17870816/MountConst8.txt)
[MountConst7.txt](https://github.com/user-attachments/files/17870820/MountConst7.txt)

**Comment by EastEriq** [comment]
Do you have a script for generating them? It may be good to reference it here. Notably for the future arrangement of mounts in the new observatory.

**Comment by EastEriq** [comment]
Files copied on last0 and code inserted in demon. I won't close the ticket till the procedure for generating the constraints files and deploy them is clarified.

**Comment by EranOfek** [comment]
telescope.geometry.obstractionModelLAST - Construct and plot enclosure and telescope obstraction model for LAST.
[dev1 5343d28fc]

**Comment by EastEriq** [comment]
https://he.wikipedia.org/wiki/%D7%90%D7%95%D7%A1%D7%98%D7%A8%D7%A7%D7%95%D7%9F
gimmea break

**Comment by EranOfek** [comment]
No clue what do you want to say.
Anyway I added an option to generate the abstraction file:
R=telescope.geometry.obstractionModelLAST('Step',0.5, 'ObstractionFile','MyFile.txt');

**Comment by EastEriq** [comment]
abstraction? obstruction? ostracism? excession?

**Comment by EranOfek** [comment]
Thanks - name corrected.
telescope.geometry.obstructionModelLAST
