### ISSUE TITLE
Scheduler: put ToO injection in try catch block

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#532]
If the user generates an invalid ToO list it may fail the scheduler demon.
1. Put the ToO injection process in a try catch block.
2. If it fail, the best behavior is to send an e-mail and slack message to user in real time.

**Comment by EastEriq** [comment]
Done try-catch, for failure I implemented only a `LogLevel.Error` logger message. As for slartibartifack messages or what, wait for a definite policy about them. Having random points in the code emit random emails and pushes will only create a noisy mess at best, or dump irrelevant message to a garbage dump which nobody reads.
