### ISSUE TITLE
Identification of bad images/nights 

### ISSUE THREAD

**Issue by yossishv** [EranOfek/AstroPack#551]
From the study mentioned in issue #550:
One bad night was not idetified (JD=2.460613610483451e+06)
Potenitally due to bad focusing?

Should improve the algortihm for identifiying bad images/nights

**Comment by EranOfek** [comment]
Changed the identifyBadImages function. Now uses the fwhm_fromACF. It is more reliable in rejecting bad images. Also demanding that there are at least 5 good images.
