### ISSUE TITLE
Add variable source flag to GAIADR3 catalog

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#554]
The catsHTM catalog of GAIADR2 has a column VarFlag which denotes if the source is variable, in the original GAIA catalog this is given by the phot_variable_flag field. In the GAIADR3 catsHTM this column is missing. It would be very helpful to include this column in the GAIADR3 catalog as well.

**Comment by EranOfek** [comment]
Note that there is a : GAIADR3extraGal
It is not large and can be copied to LAST machines.

Re variability: adding a new catalog: GAIADR3var with about 10M entries.
