### ISSUE TITLE
Missing Visits in LAST_Visits*.mat

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#560]
I have encountered missing visits in the LAST_Visits*.mat tables that should allegedly be included.

Specifically, visits that are present in Marvin appear to be absent from the LAST_Visits*.mat tables ranging from August 2 to December 12, 2024. BUT are presented in`LAST_Visits20240716.mat`

### Examples:

The directory:
`~/marvin/LAST.01.02.*/2024/03/07/proc/`
contains processed visits, but the corresponding entry:
`OT(OT.Mount == 2 & OT.Month == 3 & OT.Day == 7, :)` is **empty**.

### Another missing example:
`~/marvin/LAST.01.02.*/2024/03/06/proc/`
contains data for all four Cameras. The LAST_Visits table contain data for 3/4 cameras, the following entry is **empty**:
`OT(OT.Mount == 4 & OT.Month == 3 & OT.Day == 6 & OT.Camera == 1, :)`

**Please Note:**

The visits do appear in LAST_Visits20240716.mat. However, any versions of the table generated after July 16, 2024, seem to be missing this data, which might pin the issue to a specific version or a change in generating these tables.

+ This should be taken into account by anyone who works with the LAST_Visits tables.

**Comment by EranOfek** [comment]
The LAST_Visits catalog is no longer supported.
Instead, use the last_visits DB.
Wiki pages are not ready yet, but a few examples are in:
https://github.com/EranOfek/AstroPack/wiki/db.DbQueryExamples

In addition check out for the following functions:
pipeline.last.coadd.coadd
pipeline.last.path.construct*
pipeline.last.queryDB.coo2fieldid/loadProducts/table2path
