### ISSUE TITLE
missing JD column in Coadd catalogs 

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#564]
In all the Coadd catalogs of 
LAST.01.03.01/2024/03/09/proc/025046v0
the JD column is missing (however it is present in the Proc catalogs of this visit and in the headers of the relevant Coadd images).
This prevents DB injection, where a JD column is mandatory. 
Shall I skip this or import JD from the Coadd images in this particular case?

**Comment by EranOfek** [comment]
In procMergeCoadd - added (line 260):
```
Coadd(Ifields) = imProc.cat.insertCol(Coadd(Ifields), 'InsertJD',true,
'ColNameJD','JD', 'InsertId',true, 'ColNameId','CropID');
```

1. Please check if this solves the problem.
2. In the new extractor add this as an optional step.
3. For the DB insertion, please add an option that reads the JD from the
image or file name(?)

**Comment by agioffe** [comment]
I think this is not the optimal solution and I would not use it in procMergeCoadd.
First, it relies on Cat.JD, and as in my case it is also empty, it does not insert any column (even an empty one). 
Second, it inserts CropID just counting the objects in the input Cat array, while in reality some of the crops may be missing (e.g., due to the bad astrometry or just a bad proc image) and then the numbers it inserts for the next crops will be all wrong.
In the DB case I'd better try reading the JDs from the relevant images.

**Comment by agioffe** [comment]
Solved with the following block:
```
if ~all(Cat.isColumn('JD'))
                for Crop=1:Nobj
                    if ~Cat(Crop).isColumn('JD')                        
                        Cat(Crop).insertCol(repmat(AH(Crop).getVal('JD'), height(Cat(Crop).Table),1), Inf, 'JD', 'day');
                    end
                end
 end
```
But again, I would have commented out the line 260 in procMergeCoadd, because it is dangerous. @EranOfek , do you agree?

**Comment by EranOfek** [comment]
ok - you are calling: Cat.isColumn('JD') twice.
Just keep it in: IsColJD=Cat.isColumn('JD'); and then use it...

**Comment by agioffe** [comment]
You are right, thank you!

**Comment by agioffe** [comment]
In accordance to the change introduced above to  pipeline.general.procMergeCoadd, 
in order to avoid error of adding to the table another column with the same name (JD), I changed in pipeline.DemonLAST.main
```
MergedKnownAst = merge(OnlyMP,'IsTable',1,'AddEntryPerElement',[[OnlyMP.JD].',(1:1:numel(OnlyMP)).'],'AddColNames',{'JD','SubImageIndex'});
```
to just
```
MergedKnownAst = merge(OnlyMP,'IsTable',1,'AddEntryPerElement',(1:1:numel(OnlyMP)).','AddColNames',{'SubImageIndex'});                               
```
