### ISSUE TITLE
Photometric solutions differences in overlapping regions of sub images 

### ISSUE THREAD

**Issue by YarinMS** [EranOfek/AstroPack#57]
We get a slightly different photometric solution to sources within an overlapping region between 2 sub-images.

- The differences are of the order of 0.1 mag
- The differences might be caused due to correlation between the parameters of the photometric fit over sub images. 
- The fit is given in eq. (1) in LAST Pipeline I :
  $m_s-G_s = \alpha_1 +\alpha_2(B_{p,s}-R_{p,s}) + alpha_3(B_{p,s}-R_{p,s}) ^2+\alpha_4(W_s-\bar{W})$

- A clear example : 
 Lets consider a source from sub image 001, say source with the index 4. (circled in green, indexed in red)
<img width="818" alt="image" src="https://user-images.githubusercontent.com/118757319/207948725-70389ae8-df00-40e6-9257-2a7114c25915.png">
Since it is located at the bottom edge of a sub image it is most probably presented in another sub image top edge (an overlapping source). We can find it in sub image 002, this time with a different index, 747:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/118757319/207948919-e945afed-7f84-4589-b75e-ca036fc4ca2e.png">
While considering the photometric solutions of this source in both of the sub images, the differences between them are greater than the reported error of each solution.
<img width="997" alt="image" src="https://user-images.githubusercontent.com/118757319/207949821-caae2b87-249f-4052-a71d-47bac08f9af1.png">
Plotting the differences in log scale as a function of magnitude for all overlapping sources in these sub images : 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/118757319/207951184-427072a2-d6ab-4c51-8e4e-2da84589bec1.png">

Considering the whole 24 sub images, we find clear correlation between $ \alpha_1 $ and $ \alpha_{2,3} $ . A plot of $ \alpha_1 Vs. \alpha_{2,3}$ is presented :

<img width="668" alt="image" src="https://user-images.githubusercontent.com/118757319/207939293-458583df-f89b-48e0-97f7-b65cf471895b.png">

**Comment by EranOfek** [comment]
by running the pipeline and then:
for I=1:1:24, S(I)=AllSI(I).HeaderData.getStructKey({'PH_ZP','PH_COL1'}); end
plot([S.PH_ZP], [S.PH_COL1],'o')
I see a clear, very strong, correlation between the ZP and color term.
This is probably the source of the problem.
Looking into this.

**Comment by EranOfek** [comment]
Bug corrected.
The problem was that the mean color was not subtracted from the color prior to the fit and this introduced a covariance between the ZP and color term.
Now a new header keyword 'PH_MEDC' is containing the median color subtracted from the color.
Requires additional testing

**Comment by EranOfek** [comment]
Improved substantially but not solved + may have large RMS

**Comment by EranOfek** [comment]
The prolem may be related to the floating zero (MeanVec).
Check if ZP - ColorTerm*MeanVec is correlated with ZP

**Comment by EranOfek** [comment]
Simplified the fit : only color term is now included.
Better outlier rejection.
Dramatic improvment.
