### ISSUE TITLE
AstroCatalog basic transformations

### ISSUE THREAD

**Issue by yossishv** [EranOfek/AstroPack#59]
Might be useful to have basic affine transformation as functions of AstroCatalog:
AC.shift(val,axisname)
AC.rotate(Angle)
AC.scale(val,opt_axis) - i.e., possibly different scale to x and y
AC.shear(val,axisname)

**Comment by EranOfek** [comment]
A new function was added:
imProc.cat.affine2d - Apply affine transformation to AstroCatalog, or catalog in AstroImage
