### ISSUE TITLE
yaml -> matlab type mapping [Configuration.loadFile]

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#6]
With `c.loadFile(filename,'Field',false)`:
please document what have been your choices for mapping what. I initially thought that yml fields where read as strings and `eval()`d in matlab but probably that is neither safe nor wanted.

My discoveries so far

```
Pippo   : {inst.QHYccd} # this makes Data.Pippo.inst0x2EQHYccd = []
Pertica : [inst.QHYccd] # this makes Data.Pertica = {'inst.QHYccd'}
Papalla : 'inst.QHYccd' # this makes Data.Papalla = 'inst.QHYccd'
Zagar   : inst.QHYccd   # this makes Data.Zagar = 'inst.QHYccd' too
```
I was hoping that the last one produced directly a class object of that type. I think I can workaround that, but it would have been convenient for LAST configurations.

**Comment by EranOfek** [comment]
Three is now some documentation in the wiki:
https://github.com/EranOfek/AstroPack/wiki/Configuration
