### ISSUE TITLE
failed setCoordinateJ.m

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#64]
for Eran: 
setCoordinateJ.m fails to update the coordinates of the mount

**Comment by EastEriq** [comment]
Is this a n issue of Astropack or LAST_OCS? LAST_OCS/+obs/@mount/setCoordinateJ.m
What is "fails to update?" moves the mount or not?

**Comment by PolishookDavid** [comment]
Eran asked to insert this in the AstroPack.

setCoordinateJ does not suppose to move the mount, but to update its coordinates - which it fails to do.

David

________________________________

**Comment by EastEriq** [comment]
need more info. What mount was this on? In which respect the updated coordinate reference was wrong?
In the code I have a puzzling comment (surprised me then, but the behavior was ok on mounts 01 and 02):
https://github.com/EastEriq/LAST_XerxesMount/blob/ba12e811a640573c67270392b3ae1456e3c23757/%2Binst/%40XerxesMount/setCoordinate.m#L44

Was the problem observed on mount 8?

**Comment by PolishookDavid** [comment]
I tried it on mount 8, and failed, and Eran says it fails also on mount 2.

It failed - i.e., the coordinates were not updated. I don't know if it updates with the wrong numbers or updates the wrong parameters, or does not update at all.


David


________________________________

**Comment by EastEriq** [comment]
Can't reproduce on mount 8, with corrections of +1° separately on RA and Dec at home position. The properties `DecZeroPositionTicks` and `HAZeroPositionTicks` are consistently updated in the object and in the configuration file, and the reported RA and Dec reflect that. You have to show me what goes wrong.

The only nuisance I find is the question `'This function works in Jdate coordinates (use setCoordinateJ instead)'` in `setCoordinate` which is asked also when calling `setCoordinateJ` (I find moot such questions anyway)

**Comment by EastEriq** [comment]
Retested on mount 8. I really see no issue neither in `setCoordinate()` nor in `setCoordinateJ()`, when sample shifts of few integer degrees are asked. The coordinates Ra and Dec reported immediately after the call are consistent with the command, and the original ones are restored by a call with the opposite difference. E.g.
```
P.Mount.setCoordinateJ(P.Mount.LST+30,20,P.Mount.LST+32,19)
PP.Mount.setCoordinateJ(P.Mount.LST+30,20,P.Mount.LST+28,21)
```

**Comment by EranOfek** [comment]
The reason is not clear, but when the distortion is empty, the function works properly.
Anyway, this function must be run without the distortion.

**Comment by EastEriq** [comment]
As per discussion, if you still see this, and have a proven way of reproducing it, go on reporting here. Please figure out also whether the test must involve looking at the sky or not.
Eran was saying that
- deleting and recreating the distortion model did not help [_please specify the exact steps_]
- shutting down the main unit and reconnecting didn't either [_ditto]
- quitting matlab and restarting the unit in a new matlab "automatically brought the mount to the intended position". Please detail.
The suspicion is that either the properties of some instantiated matlab object are not updated correctly, or that parameters are not written in correctly into the controllers (though it appears that they are), or become effective only after controller reinitialization.

**Comment by EranOfek** [comment]
relevant for LAST_OCS - opened issue is LAST_issues

**Comment by EastEriq** [comment]
In technical terms, you should *transfer* the issue. Here it is probably not possible because the repos Astropack, LAST_OCS and LAST_issues are not set as belonging to the same organization.
