### ISSUE TITLE
stop using concatenations with `filesep`, for readability sake

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#68]
E.g. https://github.com/EranOfek/AstroPack/blob/890c9c6b07af0ac9022709f85cc8f57b2df932dc/matlab/startup/startup_LAST.m#L31

```
 grep -r filesep AstroPack/matlab/ |wc -l
201
```
Never heard of `fullfile()?` Or a specific reason for not using it?

**Comment by EranOfek** [comment]
started using fullfile in some places, but sprintf is about 10 times faster, so I am not going to remove it everywhere.
