### ISSUE TITLE
Suppress stupid blabber when creating and loading configurations

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#7]
As of now for me `C=Configuration;` in matlab outputs
```
Configuration Path: /home/xxxxxx/AstroPack/matlab/base/../../config
Configuration External: /home/xxxxx/AstroPack/matlab/base/../external
Master Configuration files are located in AstroPack/config
```
Where does this come from? `AstroPack/matlab/startup/startup.m` perhaps?  Why startup is called each time an object is created? I don't want to see any of them. (besides, I don't know what use to make of the two paths - I store LAST configurations elsewhere)

Furthermore, calling `C.loadFile(/home/yyyyyyyyyyyy/LAST_config/config/obs.unitCS.0.create.yml,'Field',false);` I get this output:
```
[INF] Adding property: obs.unitCS.0.create
[INF] loadYaml: Loading file: /home/yyyyyyyyyyyy/LAST_config/config/obs.unitCS.0.create.yml

Obj = 

  Configuration with properties:

    ConfigName: []
          Path: '/home/xxxxxx/AstroPack/matlab/base/../../config'
      External: '/home/xxxxxx/AstroPack/matlab/base/../external'
          Data: [1×1 struct]
```
The second part is probably just a missing semicolon (but again, I don't know what to make of the properties Path and External), and the first `[INF] Adding property: obs.unitCS.0.create` I don't know what should be (I might also want to squelch the second [INF], in future.

Please suppress all this!

**Comment by EranOfek** [comment]
Done
