### ISSUE TITLE
imProc.astrometry.astrometryCropped fails for 16bit images

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#73]
The images does not contain negative numbers, but some zeros. However, replacing the zeros with ones didn't help. We tried a 32bit image (which also contained zeros) and it did not fail the same way. Instead astrometry crashed because it did not find a solution.

ImgName = '/last02w/data2/archive/LAST.01.02.04/new/LAST.01.02.04_20230309.194700.968_clear_137+31_001_001_001_sci_raw_Image_1.fits';

>> [R, CAI, S] = imProc.astrometry.astrometryCropped(ImgName);
Check for missing argument or incorrect argument data type in call to function 'log'.

Error in imUtil.background.mode (line 61)
            Array = log(Array(Array>0));

Error in imUtil.background.background (line 138)
        [SubImage(Isub).Back, SubImage(Isub).Var] = Args.BackFun(SubI,Args.BackFunPar{:});

Error in imProc.background.background (line 137)
                            imUtil.background.background(Obj(Iobj).(Args.ImageProp).(Args.ImagePropIn),...

Error in imProc.astrometry.astrometryCropped (line 105)
        CroppedAI(Iim) = imProc.background.background(CroppedAI(Iim),
        Args.backgroundArgs{:});

**Comment by EranOfek** [comment]
it doesn't suppose to work on 16bit images.
Use AI.cast('single') to convert the image to a single format and than run astrometry.
