### ISSUE TITLE
Naming of coadd and merged data products inconsistent

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#76]
(for processed data from 20221204, M2C1)

It seems that the file names of all merged data products end with:

000_001_0*_sci_merged_Cat_1.fits

But coadded data products have:

001_001_0*_sci_coadd_Cat_1.fits

So 001 instead of 000. I guess it should be 000 for all of them?

**Comment by EranOfek** [comment]
Fixed.
