### ISSUE TITLE
Some bright pixels are not interpolated correctly

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#79]
(for processed data from 20221204, M2C1)

When looking for new sources (that are not in any catalog), single bright pixels cause elongated positive and negative sources in coadded images.

Example: RA, Dec: 41.340095, 38.38190 in LAST.01.02.01_20221204.164153.093_clear_400+39_001_001_005_sci_coadd_...

Coadded image:
![Screenshot from 2023-04-23 15-53-19](https://user-images.githubusercontent.com/14293969/233841162-5a9f48c3-118c-4073-b62c-74218fcb797f.png)

The first 3 single images show that the "source" is caused by a single bright pixel:
![Screenshot from 2023-04-23 15-53-42](https://user-images.githubusercontent.com/14293969/233841206-8118e6d4-9691-4e2e-b5cf-1050a52f7fee.png)

**Comment by noralinn** [comment]
It seems that the interpolation is simply turned off.

In pipeline.generic.singleRaw2proc line 98 it says:
Args.InterpolateOverProblems logical  = false; %true;

If interpolation is turned off these pixels should be ignored when searching for sources.

**Comment by EranOfek** [comment]
Not a bug as far as I can tell.
