### ISSUE TITLE
matlab startup broken

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#83]
This I get as matlab greeter on last12w
```
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should be resolved as soon as possible.  Error detected was:
MATLAB:scriptNotAFunction
Attempt to execute SCRIPT startup as a function:
/home/ocs/matlab/AstroPack/matlab/startup/startup.m
```
and also on my desktop machine. Both have been recently pulled from dev1

**Comment by EastEriq** [comment]
By binary search, the bug was introduced by commit 7ab54e9c9d2a4ca50d3895b7177dc390d6dcc376

**Comment by EranOfek** [comment]
Chen - please return to the previous version - your startup changes cause problems all over the place.
