### ISSUE TITLE
jpl_horizons

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#85]
The constructed URL for the JPL website is wrong.

Bug 1:
There is a %27 at the end of the URL that should be removed. See example:

Current constructed URL - DOES NOT WORK:
https://ssd.jpl.nasa.gov/horizons_batch.cgi?batch=1&COMMAND=%272015%20RN35%27&CENTER=%27500%27&MAKE_EPHEM=%27YES%27&TABLE_TYPE=%27OBSERVER%27&START_TIME=%272022-12-15%27&STOP_TIME=%272022-12-16%27&STEP_SIZE=%271h%27&QUANTITIES=%271,9,10,13,19,20,23,24%27&CSV_FORMAT=%27YES%27&EXTRA_PREC=%27YES%27%27

Corrected URL - DOES WORK:
https://ssd.jpl.nasa.gov/horizons_batch.cgi?batch=1&COMMAND=%272015%20RN35%27&CENTER=%27500%27&MAKE_EPHEM=%27YES%27&TABLE_TYPE=%27OBSERVER%27&START_TIME=%272022-12-15%27&STOP_TIME=%272022-12-16%27&STEP_SIZE=%271h%27&QUANTITIES=%271,9,10,13,19,20,23,24%27&CSV_FORMAT=%27YES%27&EXTRA_PREC=%27YES%27

Bug 2:
If the asteroid name is a temporal designation (such as 2015RN35) it should be submitted with a spacebar between the year and the designation (i.e. 2015 RN35). Current code translate the space to plus ('+'), but it should be '%20' instead.

Bug 3:
Call for celestial.time.julday should take into account the fraction of the day.

**Comment by EranOfek** [comment]
can't recreate problem 1 and 2
