### ISSUE TITLE
Bug at AstroImage.readFileNamesObj 

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#93]
It used to work when the method name was: readFileNames...

FN=FileNames.generateFromFileName('LAST.01.08.04_20221215.192510.792_clear_2015RN35_017__016_sci_proc_Image_1.fits');

>> AI=AstroImage.readFileNamesObj(FN)
Index exceeds the number of array elements (0).

Error in AstroWCS.header2wcs (line 1358)
                if isnumeric(Result(Iobj).CTYPE{1}) && any(isnan(Result(Iobj).CTYPE{1}))

Error in AstroImage/populateWCS (line 1598)
                Obj(Iobj).WCS = AstroWCS.header2wcs(Obj(Iobj).HeaderData, Args.header2wcsArgs{:});

Error in AstroImage.readFileNamesObj (line 683)
                Result = populateWCS(Result);
 
>>

**Comment by EranOfek** [comment]
Can not recover bug.
