### ISSUE TITLE
FileNames.generateFromFileName

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#94]
Add a warning comment when a file is not found by FileNames.generateFromFileName.

e.g.:
FN=FileNames.generateFromFileName('LAST.01.08.04_20221215.192510.792_clear_2015RN35_017__016_sci_proc_Image_1.fits');
ERROR - NO SUCH FILE!

**Comment by EranOfek** [comment]
FileNames.generateFromFileName now include an WarningIfEmpty argument (default is true), which print a warning in case no files found.
