### ISSUE TITLE
mount keyword is missing in LAST RAW image header

### ISSUE THREAD

**Issue by agioffe** [EranOfek/AstroPack#96]
The mount keyword is also 0, but this is because there is no such keyword in the headers of the FITS images. Should we update the pipeline so that it appears? 
I would also suggest adding a campos keyword both to the pipeline and to the DB a full identificator of the camera.

**Comment by EastEriq** [comment]
Being the one responsible for the code writing raw images and their headers: what value do you expect in that key?

**Comment by agioffe** [comment]
I would expect something like
LAST.01.02 or at least 01.02
The "campos" keyword would be "E" or "W"

**Comment by EranOfek** [comment]
Enrico - can you please modify the content of the PROJNAME keyword in the raw images, from 'LAST'
to e.g., 'LAST.01.02.03'.
Thanks,
Eran

**Comment by EastEriq** [comment]
I think that PROJNAME should remain 'LAST' and not mix information of node, mount and camera. Rather, there should be keys for each of them if relevant. Please advise on which. Keep in mind that the header already has CAMNUM and CAMPOS for the last entry. Key names for node and mount may be invented; the data is known.

**Comment by EranOfek** [comment]
How about:
PROJNAME = 'LAST';

and add:

FULLPROJ = 'LAST.01.02.03'
LASTNODE = 1;
LASTMNT    = 2;
TIMESTAM  = '20230415.010101.671' <- should be identical to the file name
time stamp.

CAMNUM is already there.
Thanks,
Eran

**Comment by EastEriq** [comment]
I'm skeptical about TIMESTAMP in that format, because it is generated by the bowels of ImagePath.genfile(), which I'm not eager to duplicate. Note that there are already the keys FILENAME and JD and DATE-OBS, with similar content.

Shall I also add TIMEZONE (which is normally specified in the obs.unitCS.NN.create.yml config)?

**Comment by EastEriq** [comment]
I would also use MOUNTNUM and NODENUMB instead of LASTNODE and LASTMNT in anticipation that the images could come from projects other than LAST

**Comment by EranOfek** [comment]
ok - please do.
eran

**Comment by EastEriq** [comment]
Done with commit https://github.com/PolishookDavid/LAST_OCS/commit/d5567275f2685cbc2a577d1aab27ec268504ee3b and pulled to all computers in the observatory.
